// Copyright (c) 2025 Jimmy O'Rourke
// Licensed under and subject to the terms of the LICENSE file accompanying this distribution.
// Official repository: https://github.com/jimmyorourke/plotlypp

// Autogenerated by plotlypp/generator, from official Plotly sources.
// See https://plotly.com/graphing-libraries.
// Do not edit, changes may be overwritten!

#pragma once

namespace plotlypp {

inline std::string Choropleth::to_string(Locationmode e) {
    switch(e) {
        case Locationmode::Iso3: return "ISO-3";
        case Locationmode::UsaStates: return "USA-states";
        case Locationmode::CountryNames: return "country names";
        case Locationmode::GeojsonId: return "geojson-id";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Choropleth::to_string(Visible e) {
    switch(e) {
        case Visible::True: return "True";
        case Visible::False: return "False";
        case Visible::Legendonly: return "legendonly";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

inline Choropleth& Choropleth::autocolorscale(bool f) {
    json["autocolorscale"] = std::move(f);
    return *this;
}

inline Choropleth& Choropleth::coloraxis(std::string f) {
    json["coloraxis"] = std::move(f);
    return *this;
}

inline Choropleth& Choropleth::colorbar(Colorbar f) {
    json["colorbar"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Choropleth& Choropleth::colorbar(Callable&& c) {
    Colorbar f{};
    std::forward<Callable>(c)(f);
    return colorbar(std::move(f));
}

inline Choropleth& Choropleth::colorscale(std::string f) {
    json["colorscale"] = std::move(f);
    return *this;
}
inline Choropleth& Choropleth::colorscale(const std::vector<std::pair<double, std::string>>& f) {
    json["colorscale"] = f;
    return *this;
}

template <typename Range, typename>
inline Choropleth& Choropleth::customdata(Range&& f) {
    json["customdata"] = f;
    return *this;
}

inline Choropleth& Choropleth::customdatasrc(std::string f) {
    json["customdatasrc"] = std::move(f);
    return *this;
}

inline Choropleth& Choropleth::featureidkey(std::string f) {
    json["featureidkey"] = std::move(f);
    return *this;
}

inline Choropleth& Choropleth::geo(std::string f) {
    json["geo"] = std::move(f);
    return *this;
}

template <typename T>
inline Choropleth& Choropleth::geojson(T f) {
    json["geojson"] = std::move(f);
    return *this;
}

inline Choropleth& Choropleth::hoverinfo(std::string f) {
    json["hoverinfo"] = std::move(f);
    return *this;
}
inline Choropleth& Choropleth::hoverinfo(const std::vector<std::string>& f) {
    json["hoverinfo"] = f;
    return *this;
}

inline Choropleth& Choropleth::hoverinfosrc(std::string f) {
    json["hoverinfosrc"] = std::move(f);
    return *this;
}

inline Choropleth& Choropleth::hoverlabel(Hoverlabel f) {
    json["hoverlabel"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Choropleth& Choropleth::hoverlabel(Callable&& c) {
    Hoverlabel f{};
    std::forward<Callable>(c)(f);
    return hoverlabel(std::move(f));
}

inline Choropleth& Choropleth::hovertemplate(std::string f) {
    json["hovertemplate"] = std::move(f);
    return *this;
}
inline Choropleth& Choropleth::hovertemplate(const std::vector<std::string>& f) {
    json["hovertemplate"] = f;
    return *this;
}

inline Choropleth& Choropleth::hovertemplatesrc(std::string f) {
    json["hovertemplatesrc"] = std::move(f);
    return *this;
}

inline Choropleth& Choropleth::hovertext(std::string f) {
    json["hovertext"] = std::move(f);
    return *this;
}
inline Choropleth& Choropleth::hovertext(const std::vector<std::string>& f) {
    json["hovertext"] = f;
    return *this;
}

inline Choropleth& Choropleth::hovertextsrc(std::string f) {
    json["hovertextsrc"] = std::move(f);
    return *this;
}

template <typename Range, typename>
inline Choropleth& Choropleth::ids(Range&& f) {
    json["ids"] = f;
    return *this;
}

inline Choropleth& Choropleth::idssrc(std::string f) {
    json["idssrc"] = std::move(f);
    return *this;
}

inline Choropleth& Choropleth::legend(std::string f) {
    json["legend"] = std::move(f);
    return *this;
}

inline Choropleth& Choropleth::legendgroup(std::string f) {
    json["legendgroup"] = std::move(f);
    return *this;
}

inline Choropleth& Choropleth::legendgrouptitle(Legendgrouptitle f) {
    json["legendgrouptitle"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Choropleth& Choropleth::legendgrouptitle(Callable&& c) {
    Legendgrouptitle f{};
    std::forward<Callable>(c)(f);
    return legendgrouptitle(std::move(f));
}

inline Choropleth& Choropleth::legendrank(double f) {
    json["legendrank"] = std::move(f);
    return *this;
}

inline Choropleth& Choropleth::legendwidth(double f) {
    json["legendwidth"] = std::move(f);
    return *this;
}

inline Choropleth& Choropleth::locationmode(enum Locationmode f) {
    json["locationmode"] = to_string(f);
    return *this;
}

template <typename Range, typename>
inline Choropleth& Choropleth::locations(Range&& f) {
    json["locations"] = f;
    return *this;
}

inline Choropleth& Choropleth::locationssrc(std::string f) {
    json["locationssrc"] = std::move(f);
    return *this;
}

inline Choropleth& Choropleth::marker(Marker f) {
    json["marker"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Choropleth& Choropleth::marker(Callable&& c) {
    Marker f{};
    std::forward<Callable>(c)(f);
    return marker(std::move(f));
}

template <typename T>
inline Choropleth& Choropleth::meta(T f) {
    json["meta"] = std::move(f);
    return *this;
}
template <typename T>
inline Choropleth& Choropleth::meta(const std::vector<T>& f) {
    json["meta"] = f;
    return *this;
}

inline Choropleth& Choropleth::metasrc(std::string f) {
    json["metasrc"] = std::move(f);
    return *this;
}

inline Choropleth& Choropleth::name(std::string f) {
    json["name"] = std::move(f);
    return *this;
}

inline Choropleth& Choropleth::reversescale(bool f) {
    json["reversescale"] = std::move(f);
    return *this;
}

inline Choropleth& Choropleth::selected(Selected f) {
    json["selected"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Choropleth& Choropleth::selected(Callable&& c) {
    Selected f{};
    std::forward<Callable>(c)(f);
    return selected(std::move(f));
}

template <typename T>
inline Choropleth& Choropleth::selectedpoints(T f) {
    json["selectedpoints"] = std::move(f);
    return *this;
}

inline Choropleth& Choropleth::showlegend(bool f) {
    json["showlegend"] = std::move(f);
    return *this;
}

inline Choropleth& Choropleth::showscale(bool f) {
    json["showscale"] = std::move(f);
    return *this;
}

inline Choropleth& Choropleth::stream(Stream f) {
    json["stream"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Choropleth& Choropleth::stream(Callable&& c) {
    Stream f{};
    std::forward<Callable>(c)(f);
    return stream(std::move(f));
}

inline Choropleth& Choropleth::text(std::string f) {
    json["text"] = std::move(f);
    return *this;
}
inline Choropleth& Choropleth::text(const std::vector<std::string>& f) {
    json["text"] = f;
    return *this;
}

inline Choropleth& Choropleth::textsrc(std::string f) {
    json["textsrc"] = std::move(f);
    return *this;
}

inline Choropleth& Choropleth::uid(std::string f) {
    json["uid"] = std::move(f);
    return *this;
}

template <typename T>
inline Choropleth& Choropleth::uirevision(T f) {
    json["uirevision"] = std::move(f);
    return *this;
}

inline Choropleth& Choropleth::unselected(Unselected f) {
    json["unselected"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Choropleth& Choropleth::unselected(Callable&& c) {
    Unselected f{};
    std::forward<Callable>(c)(f);
    return unselected(std::move(f));
}

inline Choropleth& Choropleth::visible(enum Visible f) {
    json["visible"] = to_string(f);
    return *this;
}

template <typename Range, typename>
inline Choropleth& Choropleth::z(Range&& f) {
    json["z"] = f;
    return *this;
}

inline Choropleth& Choropleth::zauto(bool f) {
    json["zauto"] = std::move(f);
    return *this;
}

inline Choropleth& Choropleth::zmax(double f) {
    json["zmax"] = std::move(f);
    return *this;
}

inline Choropleth& Choropleth::zmid(double f) {
    json["zmid"] = std::move(f);
    return *this;
}

inline Choropleth& Choropleth::zmin(double f) {
    json["zmin"] = std::move(f);
    return *this;
}

inline Choropleth& Choropleth::zsrc(std::string f) {
    json["zsrc"] = std::move(f);
    return *this;
}

inline std::string Choropleth::Colorbar::to_string(Exponentformat e) {
    switch(e) {
        case Exponentformat::None: return "none";
        case Exponentformat::E: return "E";
        case Exponentformat::Power: return "power";
        case Exponentformat::Si: return "SI";
        case Exponentformat::B: return "B";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Choropleth::Colorbar::to_string(Lenmode e) {
    switch(e) {
        case Lenmode::Fraction: return "fraction";
        case Lenmode::Pixels: return "pixels";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Choropleth::Colorbar::to_string(Orientation e) {
    switch(e) {
        case Orientation::H: return "h";
        case Orientation::V: return "v";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Choropleth::Colorbar::to_string(Showexponent e) {
    switch(e) {
        case Showexponent::All: return "all";
        case Showexponent::First: return "first";
        case Showexponent::Last: return "last";
        case Showexponent::None: return "none";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Choropleth::Colorbar::to_string(Showtickprefix e) {
    switch(e) {
        case Showtickprefix::All: return "all";
        case Showtickprefix::First: return "first";
        case Showtickprefix::Last: return "last";
        case Showtickprefix::None: return "none";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Choropleth::Colorbar::to_string(Showticksuffix e) {
    switch(e) {
        case Showticksuffix::All: return "all";
        case Showticksuffix::First: return "first";
        case Showticksuffix::Last: return "last";
        case Showticksuffix::None: return "none";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Choropleth::Colorbar::to_string(Thicknessmode e) {
    switch(e) {
        case Thicknessmode::Fraction: return "fraction";
        case Thicknessmode::Pixels: return "pixels";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Choropleth::Colorbar::to_string(Ticklabeloverflow e) {
    switch(e) {
        case Ticklabeloverflow::Allow: return "allow";
        case Ticklabeloverflow::HidePastDiv: return "hide past div";
        case Ticklabeloverflow::HidePastDomain: return "hide past domain";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Choropleth::Colorbar::to_string(Ticklabelposition e) {
    switch(e) {
        case Ticklabelposition::Outside: return "outside";
        case Ticklabelposition::Inside: return "inside";
        case Ticklabelposition::OutsideTop: return "outside top";
        case Ticklabelposition::InsideTop: return "inside top";
        case Ticklabelposition::OutsideLeft: return "outside left";
        case Ticklabelposition::InsideLeft: return "inside left";
        case Ticklabelposition::OutsideRight: return "outside right";
        case Ticklabelposition::InsideRight: return "inside right";
        case Ticklabelposition::OutsideBottom: return "outside bottom";
        case Ticklabelposition::InsideBottom: return "inside bottom";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Choropleth::Colorbar::to_string(Tickmode e) {
    switch(e) {
        case Tickmode::Auto: return "auto";
        case Tickmode::Linear: return "linear";
        case Tickmode::Array: return "array";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Choropleth::Colorbar::to_string(Ticks e) {
    switch(e) {
        case Ticks::Outside: return "outside";
        case Ticks::Inside: return "inside";
        case Ticks::Empty: return "";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Choropleth::Colorbar::to_string(Xanchor e) {
    switch(e) {
        case Xanchor::Left: return "left";
        case Xanchor::Center: return "center";
        case Xanchor::Right: return "right";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Choropleth::Colorbar::to_string(Xref e) {
    switch(e) {
        case Xref::Container: return "container";
        case Xref::Paper: return "paper";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Choropleth::Colorbar::to_string(Yanchor e) {
    switch(e) {
        case Yanchor::Top: return "top";
        case Yanchor::Middle: return "middle";
        case Yanchor::Bottom: return "bottom";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Choropleth::Colorbar::to_string(Yref e) {
    switch(e) {
        case Yref::Container: return "container";
        case Yref::Paper: return "paper";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

inline Choropleth::Colorbar& Choropleth::Colorbar::bgcolor(std::string f) {
    json["bgcolor"] = std::move(f);
    return *this;
}
inline Choropleth::Colorbar& Choropleth::Colorbar::bgcolor(double f) {
    json["bgcolor"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::bordercolor(std::string f) {
    json["bordercolor"] = std::move(f);
    return *this;
}
inline Choropleth::Colorbar& Choropleth::Colorbar::bordercolor(double f) {
    json["bordercolor"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::borderwidth(double f) {
    json["borderwidth"] = std::move(f);
    return *this;
}

template <typename T>
inline Choropleth::Colorbar& Choropleth::Colorbar::dtick(T f) {
    json["dtick"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::exponentformat(enum Exponentformat f) {
    json["exponentformat"] = to_string(f);
    return *this;
}

template <typename T>
inline Choropleth::Colorbar& Choropleth::Colorbar::labelalias(T f) {
    json["labelalias"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::len(double f) {
    json["len"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::lenmode(enum Lenmode f) {
    json["lenmode"] = to_string(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::minexponent(double f) {
    json["minexponent"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::nticks(int f) {
    json["nticks"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::orientation(enum Orientation f) {
    json["orientation"] = to_string(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::outlinecolor(std::string f) {
    json["outlinecolor"] = std::move(f);
    return *this;
}
inline Choropleth::Colorbar& Choropleth::Colorbar::outlinecolor(double f) {
    json["outlinecolor"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::outlinewidth(double f) {
    json["outlinewidth"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::separatethousands(bool f) {
    json["separatethousands"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::showexponent(enum Showexponent f) {
    json["showexponent"] = to_string(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::showticklabels(bool f) {
    json["showticklabels"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::showtickprefix(enum Showtickprefix f) {
    json["showtickprefix"] = to_string(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::showticksuffix(enum Showticksuffix f) {
    json["showticksuffix"] = to_string(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::thickness(double f) {
    json["thickness"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::thicknessmode(enum Thicknessmode f) {
    json["thicknessmode"] = to_string(f);
    return *this;
}

template <typename T>
inline Choropleth::Colorbar& Choropleth::Colorbar::tick0(T f) {
    json["tick0"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::tickangle(double f) {
    json["tickangle"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::tickcolor(std::string f) {
    json["tickcolor"] = std::move(f);
    return *this;
}
inline Choropleth::Colorbar& Choropleth::Colorbar::tickcolor(double f) {
    json["tickcolor"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::tickfont(Tickfont f) {
    json["tickfont"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Choropleth::Colorbar& Choropleth::Colorbar::tickfont(Callable&& c) {
    Tickfont f{};
    std::forward<Callable>(c)(f);
    return tickfont(std::move(f));
}

inline Choropleth::Colorbar& Choropleth::Colorbar::tickformat(std::string f) {
    json["tickformat"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::tickformatstops(const std::vector<Tickformatstop>& f) {
    std::vector<Json> jsonified(f.size());
    std::transform(f.begin(), f.end(), jsonified.begin(), [](auto& e){ return e.json; });
    json["tickformatstops"] = std::move(jsonified);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::ticklabeloverflow(enum Ticklabeloverflow f) {
    json["ticklabeloverflow"] = to_string(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::ticklabelposition(enum Ticklabelposition f) {
    json["ticklabelposition"] = to_string(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::ticklabelstep(int f) {
    json["ticklabelstep"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::ticklen(double f) {
    json["ticklen"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::tickmode(enum Tickmode f) {
    json["tickmode"] = to_string(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::tickprefix(std::string f) {
    json["tickprefix"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::ticks(enum Ticks f) {
    json["ticks"] = to_string(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::ticksuffix(std::string f) {
    json["ticksuffix"] = std::move(f);
    return *this;
}

template <typename Range, typename>
inline Choropleth::Colorbar& Choropleth::Colorbar::ticktext(Range&& f) {
    json["ticktext"] = f;
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::ticktextsrc(std::string f) {
    json["ticktextsrc"] = std::move(f);
    return *this;
}

template <typename Range, typename>
inline Choropleth::Colorbar& Choropleth::Colorbar::tickvals(Range&& f) {
    json["tickvals"] = f;
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::tickvalssrc(std::string f) {
    json["tickvalssrc"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::tickwidth(double f) {
    json["tickwidth"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::title(Title f) {
    json["title"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Choropleth::Colorbar& Choropleth::Colorbar::title(Callable&& c) {
    Title f{};
    std::forward<Callable>(c)(f);
    return title(std::move(f));
}

inline Choropleth::Colorbar& Choropleth::Colorbar::x(double f) {
    json["x"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::xanchor(enum Xanchor f) {
    json["xanchor"] = to_string(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::xpad(double f) {
    json["xpad"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::xref(enum Xref f) {
    json["xref"] = to_string(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::y(double f) {
    json["y"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::yanchor(enum Yanchor f) {
    json["yanchor"] = to_string(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::ypad(double f) {
    json["ypad"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar& Choropleth::Colorbar::yref(enum Yref f) {
    json["yref"] = to_string(f);
    return *this;
}

inline std::string Choropleth::Colorbar::Tickfont::to_string(Style e) {
    switch(e) {
        case Style::Normal: return "normal";
        case Style::Italic: return "italic";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Choropleth::Colorbar::Tickfont::to_string(Textcase e) {
    switch(e) {
        case Textcase::Normal: return "normal";
        case Textcase::WordCaps: return "word caps";
        case Textcase::Upper: return "upper";
        case Textcase::Lower: return "lower";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Choropleth::Colorbar::Tickfont::to_string(Variant e) {
    switch(e) {
        case Variant::Normal: return "normal";
        case Variant::SmallCaps: return "small-caps";
        case Variant::AllSmallCaps: return "all-small-caps";
        case Variant::AllPetiteCaps: return "all-petite-caps";
        case Variant::PetiteCaps: return "petite-caps";
        case Variant::Unicase: return "unicase";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

inline Choropleth::Colorbar::Tickfont& Choropleth::Colorbar::Tickfont::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Choropleth::Colorbar::Tickfont& Choropleth::Colorbar::Tickfont::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar::Tickfont& Choropleth::Colorbar::Tickfont::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar::Tickfont& Choropleth::Colorbar::Tickfont::lineposition(std::string f) {
    json["lineposition"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar::Tickfont& Choropleth::Colorbar::Tickfont::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar::Tickfont& Choropleth::Colorbar::Tickfont::size(double f) {
    json["size"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar::Tickfont& Choropleth::Colorbar::Tickfont::style(enum Style f) {
    json["style"] = to_string(f);
    return *this;
}

inline Choropleth::Colorbar::Tickfont& Choropleth::Colorbar::Tickfont::textcase(enum Textcase f) {
    json["textcase"] = to_string(f);
    return *this;
}

inline Choropleth::Colorbar::Tickfont& Choropleth::Colorbar::Tickfont::variant(enum Variant f) {
    json["variant"] = to_string(f);
    return *this;
}

inline Choropleth::Colorbar::Tickfont& Choropleth::Colorbar::Tickfont::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}


inline Choropleth::Colorbar::Tickformatstop& Choropleth::Colorbar::Tickformatstop::dtickrange(const std::vector<double>& f) {
    json["dtickrange"] = f;
    return *this;
}
inline Choropleth::Colorbar::Tickformatstop& Choropleth::Colorbar::Tickformatstop::dtickrange(const std::vector<std::string>& f) {
    json["dtickrange"] = f;
    return *this;
}
inline Choropleth::Colorbar::Tickformatstop& Choropleth::Colorbar::Tickformatstop::dtickrange(const std::vector<std::vector<std::string>>& f) {
    json["dtickrange"] = f;
    return *this;
}
inline Choropleth::Colorbar::Tickformatstop& Choropleth::Colorbar::Tickformatstop::dtickrange(const std::vector<std::vector<double>>& f) {
    json["dtickrange"] = f;
    return *this;
}

inline Choropleth::Colorbar::Tickformatstop& Choropleth::Colorbar::Tickformatstop::enabled(bool f) {
    json["enabled"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar::Tickformatstop& Choropleth::Colorbar::Tickformatstop::name(std::string f) {
    json["name"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar::Tickformatstop& Choropleth::Colorbar::Tickformatstop::templateitemname(std::string f) {
    json["templateitemname"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar::Tickformatstop& Choropleth::Colorbar::Tickformatstop::value(std::string f) {
    json["value"] = std::move(f);
    return *this;
}

inline std::string Choropleth::Colorbar::Title::to_string(Side e) {
    switch(e) {
        case Side::Right: return "right";
        case Side::Top: return "top";
        case Side::Bottom: return "bottom";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

inline Choropleth::Colorbar::Title& Choropleth::Colorbar::Title::font(Font f) {
    json["font"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Choropleth::Colorbar::Title& Choropleth::Colorbar::Title::font(Callable&& c) {
    Font f{};
    std::forward<Callable>(c)(f);
    return font(std::move(f));
}

inline Choropleth::Colorbar::Title& Choropleth::Colorbar::Title::side(enum Side f) {
    json["side"] = to_string(f);
    return *this;
}

inline Choropleth::Colorbar::Title& Choropleth::Colorbar::Title::text(std::string f) {
    json["text"] = std::move(f);
    return *this;
}

inline std::string Choropleth::Colorbar::Title::Font::to_string(Style e) {
    switch(e) {
        case Style::Normal: return "normal";
        case Style::Italic: return "italic";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Choropleth::Colorbar::Title::Font::to_string(Textcase e) {
    switch(e) {
        case Textcase::Normal: return "normal";
        case Textcase::WordCaps: return "word caps";
        case Textcase::Upper: return "upper";
        case Textcase::Lower: return "lower";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Choropleth::Colorbar::Title::Font::to_string(Variant e) {
    switch(e) {
        case Variant::Normal: return "normal";
        case Variant::SmallCaps: return "small-caps";
        case Variant::AllSmallCaps: return "all-small-caps";
        case Variant::AllPetiteCaps: return "all-petite-caps";
        case Variant::PetiteCaps: return "petite-caps";
        case Variant::Unicase: return "unicase";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

inline Choropleth::Colorbar::Title::Font& Choropleth::Colorbar::Title::Font::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Choropleth::Colorbar::Title::Font& Choropleth::Colorbar::Title::Font::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar::Title::Font& Choropleth::Colorbar::Title::Font::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar::Title::Font& Choropleth::Colorbar::Title::Font::lineposition(std::string f) {
    json["lineposition"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar::Title::Font& Choropleth::Colorbar::Title::Font::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar::Title::Font& Choropleth::Colorbar::Title::Font::size(double f) {
    json["size"] = std::move(f);
    return *this;
}

inline Choropleth::Colorbar::Title::Font& Choropleth::Colorbar::Title::Font::style(enum Style f) {
    json["style"] = to_string(f);
    return *this;
}

inline Choropleth::Colorbar::Title::Font& Choropleth::Colorbar::Title::Font::textcase(enum Textcase f) {
    json["textcase"] = to_string(f);
    return *this;
}

inline Choropleth::Colorbar::Title::Font& Choropleth::Colorbar::Title::Font::variant(enum Variant f) {
    json["variant"] = to_string(f);
    return *this;
}

inline Choropleth::Colorbar::Title::Font& Choropleth::Colorbar::Title::Font::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}

inline std::string Choropleth::Hoverlabel::to_string(Align e) {
    switch(e) {
        case Align::Left: return "left";
        case Align::Right: return "right";
        case Align::Auto: return "auto";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

inline Choropleth::Hoverlabel& Choropleth::Hoverlabel::align(enum Align f) {
    json["align"] = to_string(f);
    return *this;
}
inline Choropleth::Hoverlabel& Choropleth::Hoverlabel::align(const std::vector<enum Align>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["align"] = std::move(stringified);
    return *this;
}

inline Choropleth::Hoverlabel& Choropleth::Hoverlabel::alignsrc(std::string f) {
    json["alignsrc"] = std::move(f);
    return *this;
}

inline Choropleth::Hoverlabel& Choropleth::Hoverlabel::bgcolor(std::string f) {
    json["bgcolor"] = std::move(f);
    return *this;
}
inline Choropleth::Hoverlabel& Choropleth::Hoverlabel::bgcolor(double f) {
    json["bgcolor"] = std::move(f);
    return *this;
}
inline Choropleth::Hoverlabel& Choropleth::Hoverlabel::bgcolor(const std::vector<std::string>& f) {
    json["bgcolor"] = f;
    return *this;
}
inline Choropleth::Hoverlabel& Choropleth::Hoverlabel::bgcolor(const std::vector<double>& f) {
    json["bgcolor"] = f;
    return *this;
}

inline Choropleth::Hoverlabel& Choropleth::Hoverlabel::bgcolorsrc(std::string f) {
    json["bgcolorsrc"] = std::move(f);
    return *this;
}

inline Choropleth::Hoverlabel& Choropleth::Hoverlabel::bordercolor(std::string f) {
    json["bordercolor"] = std::move(f);
    return *this;
}
inline Choropleth::Hoverlabel& Choropleth::Hoverlabel::bordercolor(double f) {
    json["bordercolor"] = std::move(f);
    return *this;
}
inline Choropleth::Hoverlabel& Choropleth::Hoverlabel::bordercolor(const std::vector<std::string>& f) {
    json["bordercolor"] = f;
    return *this;
}
inline Choropleth::Hoverlabel& Choropleth::Hoverlabel::bordercolor(const std::vector<double>& f) {
    json["bordercolor"] = f;
    return *this;
}

inline Choropleth::Hoverlabel& Choropleth::Hoverlabel::bordercolorsrc(std::string f) {
    json["bordercolorsrc"] = std::move(f);
    return *this;
}

inline Choropleth::Hoverlabel& Choropleth::Hoverlabel::font(Font f) {
    json["font"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Choropleth::Hoverlabel& Choropleth::Hoverlabel::font(Callable&& c) {
    Font f{};
    std::forward<Callable>(c)(f);
    return font(std::move(f));
}

inline Choropleth::Hoverlabel& Choropleth::Hoverlabel::namelength(int f) {
    json["namelength"] = std::move(f);
    return *this;
}
inline Choropleth::Hoverlabel& Choropleth::Hoverlabel::namelength(const std::vector<int>& f) {
    json["namelength"] = f;
    return *this;
}

inline Choropleth::Hoverlabel& Choropleth::Hoverlabel::namelengthsrc(std::string f) {
    json["namelengthsrc"] = std::move(f);
    return *this;
}

inline std::string Choropleth::Hoverlabel::Font::to_string(Style e) {
    switch(e) {
        case Style::Normal: return "normal";
        case Style::Italic: return "italic";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Choropleth::Hoverlabel::Font::to_string(Textcase e) {
    switch(e) {
        case Textcase::Normal: return "normal";
        case Textcase::WordCaps: return "word caps";
        case Textcase::Upper: return "upper";
        case Textcase::Lower: return "lower";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Choropleth::Hoverlabel::Font::to_string(Variant e) {
    switch(e) {
        case Variant::Normal: return "normal";
        case Variant::SmallCaps: return "small-caps";
        case Variant::AllSmallCaps: return "all-small-caps";
        case Variant::AllPetiteCaps: return "all-petite-caps";
        case Variant::PetiteCaps: return "petite-caps";
        case Variant::Unicase: return "unicase";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

inline Choropleth::Hoverlabel::Font& Choropleth::Hoverlabel::Font::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Choropleth::Hoverlabel::Font& Choropleth::Hoverlabel::Font::color(double f) {
    json["color"] = std::move(f);
    return *this;
}
inline Choropleth::Hoverlabel::Font& Choropleth::Hoverlabel::Font::color(const std::vector<std::string>& f) {
    json["color"] = f;
    return *this;
}
inline Choropleth::Hoverlabel::Font& Choropleth::Hoverlabel::Font::color(const std::vector<double>& f) {
    json["color"] = f;
    return *this;
}

inline Choropleth::Hoverlabel::Font& Choropleth::Hoverlabel::Font::colorsrc(std::string f) {
    json["colorsrc"] = std::move(f);
    return *this;
}

inline Choropleth::Hoverlabel::Font& Choropleth::Hoverlabel::Font::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}
inline Choropleth::Hoverlabel::Font& Choropleth::Hoverlabel::Font::family(const std::vector<std::string>& f) {
    json["family"] = f;
    return *this;
}

inline Choropleth::Hoverlabel::Font& Choropleth::Hoverlabel::Font::familysrc(std::string f) {
    json["familysrc"] = std::move(f);
    return *this;
}

inline Choropleth::Hoverlabel::Font& Choropleth::Hoverlabel::Font::lineposition(std::string f) {
    json["lineposition"] = std::move(f);
    return *this;
}
inline Choropleth::Hoverlabel::Font& Choropleth::Hoverlabel::Font::lineposition(const std::vector<std::string>& f) {
    json["lineposition"] = f;
    return *this;
}

inline Choropleth::Hoverlabel::Font& Choropleth::Hoverlabel::Font::linepositionsrc(std::string f) {
    json["linepositionsrc"] = std::move(f);
    return *this;
}

inline Choropleth::Hoverlabel::Font& Choropleth::Hoverlabel::Font::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}
inline Choropleth::Hoverlabel::Font& Choropleth::Hoverlabel::Font::shadow(const std::vector<std::string>& f) {
    json["shadow"] = f;
    return *this;
}

inline Choropleth::Hoverlabel::Font& Choropleth::Hoverlabel::Font::shadowsrc(std::string f) {
    json["shadowsrc"] = std::move(f);
    return *this;
}

inline Choropleth::Hoverlabel::Font& Choropleth::Hoverlabel::Font::size(double f) {
    json["size"] = std::move(f);
    return *this;
}
inline Choropleth::Hoverlabel::Font& Choropleth::Hoverlabel::Font::size(const std::vector<double>& f) {
    json["size"] = f;
    return *this;
}

inline Choropleth::Hoverlabel::Font& Choropleth::Hoverlabel::Font::sizesrc(std::string f) {
    json["sizesrc"] = std::move(f);
    return *this;
}

inline Choropleth::Hoverlabel::Font& Choropleth::Hoverlabel::Font::style(enum Style f) {
    json["style"] = to_string(f);
    return *this;
}
inline Choropleth::Hoverlabel::Font& Choropleth::Hoverlabel::Font::style(const std::vector<enum Style>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["style"] = std::move(stringified);
    return *this;
}

inline Choropleth::Hoverlabel::Font& Choropleth::Hoverlabel::Font::stylesrc(std::string f) {
    json["stylesrc"] = std::move(f);
    return *this;
}

inline Choropleth::Hoverlabel::Font& Choropleth::Hoverlabel::Font::textcase(enum Textcase f) {
    json["textcase"] = to_string(f);
    return *this;
}
inline Choropleth::Hoverlabel::Font& Choropleth::Hoverlabel::Font::textcase(const std::vector<enum Textcase>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["textcase"] = std::move(stringified);
    return *this;
}

inline Choropleth::Hoverlabel::Font& Choropleth::Hoverlabel::Font::textcasesrc(std::string f) {
    json["textcasesrc"] = std::move(f);
    return *this;
}

inline Choropleth::Hoverlabel::Font& Choropleth::Hoverlabel::Font::variant(enum Variant f) {
    json["variant"] = to_string(f);
    return *this;
}
inline Choropleth::Hoverlabel::Font& Choropleth::Hoverlabel::Font::variant(const std::vector<enum Variant>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["variant"] = std::move(stringified);
    return *this;
}

inline Choropleth::Hoverlabel::Font& Choropleth::Hoverlabel::Font::variantsrc(std::string f) {
    json["variantsrc"] = std::move(f);
    return *this;
}

inline Choropleth::Hoverlabel::Font& Choropleth::Hoverlabel::Font::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}
inline Choropleth::Hoverlabel::Font& Choropleth::Hoverlabel::Font::weight(const std::vector<int>& f) {
    json["weight"] = f;
    return *this;
}

inline Choropleth::Hoverlabel::Font& Choropleth::Hoverlabel::Font::weightsrc(std::string f) {
    json["weightsrc"] = std::move(f);
    return *this;
}


inline Choropleth::Legendgrouptitle& Choropleth::Legendgrouptitle::font(Font f) {
    json["font"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Choropleth::Legendgrouptitle& Choropleth::Legendgrouptitle::font(Callable&& c) {
    Font f{};
    std::forward<Callable>(c)(f);
    return font(std::move(f));
}

inline Choropleth::Legendgrouptitle& Choropleth::Legendgrouptitle::text(std::string f) {
    json["text"] = std::move(f);
    return *this;
}

inline std::string Choropleth::Legendgrouptitle::Font::to_string(Style e) {
    switch(e) {
        case Style::Normal: return "normal";
        case Style::Italic: return "italic";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Choropleth::Legendgrouptitle::Font::to_string(Textcase e) {
    switch(e) {
        case Textcase::Normal: return "normal";
        case Textcase::WordCaps: return "word caps";
        case Textcase::Upper: return "upper";
        case Textcase::Lower: return "lower";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Choropleth::Legendgrouptitle::Font::to_string(Variant e) {
    switch(e) {
        case Variant::Normal: return "normal";
        case Variant::SmallCaps: return "small-caps";
        case Variant::AllSmallCaps: return "all-small-caps";
        case Variant::AllPetiteCaps: return "all-petite-caps";
        case Variant::PetiteCaps: return "petite-caps";
        case Variant::Unicase: return "unicase";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

inline Choropleth::Legendgrouptitle::Font& Choropleth::Legendgrouptitle::Font::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Choropleth::Legendgrouptitle::Font& Choropleth::Legendgrouptitle::Font::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

inline Choropleth::Legendgrouptitle::Font& Choropleth::Legendgrouptitle::Font::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}

inline Choropleth::Legendgrouptitle::Font& Choropleth::Legendgrouptitle::Font::lineposition(std::string f) {
    json["lineposition"] = std::move(f);
    return *this;
}

inline Choropleth::Legendgrouptitle::Font& Choropleth::Legendgrouptitle::Font::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}

inline Choropleth::Legendgrouptitle::Font& Choropleth::Legendgrouptitle::Font::size(double f) {
    json["size"] = std::move(f);
    return *this;
}

inline Choropleth::Legendgrouptitle::Font& Choropleth::Legendgrouptitle::Font::style(enum Style f) {
    json["style"] = to_string(f);
    return *this;
}

inline Choropleth::Legendgrouptitle::Font& Choropleth::Legendgrouptitle::Font::textcase(enum Textcase f) {
    json["textcase"] = to_string(f);
    return *this;
}

inline Choropleth::Legendgrouptitle::Font& Choropleth::Legendgrouptitle::Font::variant(enum Variant f) {
    json["variant"] = to_string(f);
    return *this;
}

inline Choropleth::Legendgrouptitle::Font& Choropleth::Legendgrouptitle::Font::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}


inline Choropleth::Marker& Choropleth::Marker::line(Line f) {
    json["line"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Choropleth::Marker& Choropleth::Marker::line(Callable&& c) {
    Line f{};
    std::forward<Callable>(c)(f);
    return line(std::move(f));
}

inline Choropleth::Marker& Choropleth::Marker::opacity(double f) {
    json["opacity"] = std::move(f);
    return *this;
}
inline Choropleth::Marker& Choropleth::Marker::opacity(const std::vector<double>& f) {
    json["opacity"] = f;
    return *this;
}

inline Choropleth::Marker& Choropleth::Marker::opacitysrc(std::string f) {
    json["opacitysrc"] = std::move(f);
    return *this;
}


inline Choropleth::Marker::Line& Choropleth::Marker::Line::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Choropleth::Marker::Line& Choropleth::Marker::Line::color(double f) {
    json["color"] = std::move(f);
    return *this;
}
inline Choropleth::Marker::Line& Choropleth::Marker::Line::color(const std::vector<std::string>& f) {
    json["color"] = f;
    return *this;
}
inline Choropleth::Marker::Line& Choropleth::Marker::Line::color(const std::vector<double>& f) {
    json["color"] = f;
    return *this;
}

inline Choropleth::Marker::Line& Choropleth::Marker::Line::colorsrc(std::string f) {
    json["colorsrc"] = std::move(f);
    return *this;
}

inline Choropleth::Marker::Line& Choropleth::Marker::Line::width(double f) {
    json["width"] = std::move(f);
    return *this;
}
inline Choropleth::Marker::Line& Choropleth::Marker::Line::width(const std::vector<double>& f) {
    json["width"] = f;
    return *this;
}

inline Choropleth::Marker::Line& Choropleth::Marker::Line::widthsrc(std::string f) {
    json["widthsrc"] = std::move(f);
    return *this;
}


inline Choropleth::Selected& Choropleth::Selected::marker(Marker f) {
    json["marker"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Choropleth::Selected& Choropleth::Selected::marker(Callable&& c) {
    Marker f{};
    std::forward<Callable>(c)(f);
    return marker(std::move(f));
}


inline Choropleth::Selected::Marker& Choropleth::Selected::Marker::opacity(double f) {
    json["opacity"] = std::move(f);
    return *this;
}


inline Choropleth::Stream& Choropleth::Stream::maxpoints(double f) {
    json["maxpoints"] = std::move(f);
    return *this;
}

inline Choropleth::Stream& Choropleth::Stream::token(std::string f) {
    json["token"] = std::move(f);
    return *this;
}


inline Choropleth::Unselected& Choropleth::Unselected::marker(Marker f) {
    json["marker"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Choropleth::Unselected& Choropleth::Unselected::marker(Callable&& c) {
    Marker f{};
    std::forward<Callable>(c)(f);
    return marker(std::move(f));
}


inline Choropleth::Unselected::Marker& Choropleth::Unselected::Marker::opacity(double f) {
    json["opacity"] = std::move(f);
    return *this;
}

} // namespace plotlypp

