// Copyright (c) 2025-2026 Jimmy O'Rourke
// Licensed under and subject to the terms of the LICENSE file accompanying this distribution.
// Official repository: https://github.com/jimmyorourke/plotlypp

// Autogenerated by plotlypp/generator, from official Plotly sources.
// See https://plotly.com/graphing-libraries.
// Do not edit, changes may be overwritten!

#pragma once

#include <plotlypp/detail/flaglist_helpers.hpp>

namespace plotlypp {

inline std::string Contour::to_string(Hoverinfo e) {
    switch(e) {
        case Hoverinfo::X: return "x";
        case Hoverinfo::Y: return "y";
        case Hoverinfo::Z: return "z";
        case Hoverinfo::Text: return "text";
        case Hoverinfo::Name: return "name";
    }
    throw std::invalid_argument{"Unknown flag value for hoverinfo."};
}
inline std::string Contour::to_string(HoverinfoExtra e) {
    switch(e) {
        case HoverinfoExtra::All: return "all";
        case HoverinfoExtra::None: return "none";
        case HoverinfoExtra::Skip: return "skip";
    }
    throw std::invalid_argument{"Unknown extra value for hoverinfo."};
}

inline Contour& Contour::autocolorscale(bool f) {
    json["autocolorscale"] = std::move(f);
    return *this;
}

inline Contour& Contour::autocontour(bool f) {
    json["autocontour"] = std::move(f);
    return *this;
}

inline Contour& Contour::coloraxis(std::string f) {
    json["coloraxis"] = std::move(f);
    return *this;
}

inline Contour& Contour::colorbar(Colorbar f) {
    json["colorbar"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Contour& Contour::colorbar(Callable&& c) {
    Colorbar f{};
    std::forward<Callable>(c)(f);
    return colorbar(std::move(f));
}

inline Contour& Contour::colorscale(std::string f) {
    json["colorscale"] = std::move(f);
    return *this;
}
inline Contour& Contour::colorscale(const std::vector<std::pair<double, std::string>>& f) {
    json["colorscale"] = f;
    return *this;
}

inline Contour& Contour::connectgaps(bool f) {
    json["connectgaps"] = std::move(f);
    return *this;
}

inline Contour& Contour::contours(Contours f) {
    json["contours"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Contour& Contour::contours(Callable&& c) {
    Contours f{};
    std::forward<Callable>(c)(f);
    return contours(std::move(f));
}

template <typename Range, typename>
inline Contour& Contour::customdata(Range&& f) {
    json["customdata"] = f;
    return *this;
}

inline Contour& Contour::customdatasrc(std::string f) {
    json["customdatasrc"] = std::move(f);
    return *this;
}

inline Contour& Contour::dx(double f) {
    json["dx"] = std::move(f);
    return *this;
}

inline Contour& Contour::dy(double f) {
    json["dy"] = std::move(f);
    return *this;
}

inline Contour& Contour::fillcolor(std::string f) {
    json["fillcolor"] = std::move(f);
    return *this;
}
inline Contour& Contour::fillcolor(double f) {
    json["fillcolor"] = std::move(f);
    return *this;
}

inline Contour& Contour::hoverinfo(std::initializer_list<Hoverinfo> flags) {
    json["hoverinfo"] = detail::joinFlaglist(flags, [](auto f){ return to_string(f); });
    return *this;
}
inline Contour& Contour::hoverinfo(HoverinfoExtra extra) {
    json["hoverinfo"] = to_string(extra);
    return *this;
}

inline Contour& Contour::hoverinfosrc(std::string f) {
    json["hoverinfosrc"] = std::move(f);
    return *this;
}

inline Contour& Contour::hoverlabel(Hoverlabel f) {
    json["hoverlabel"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Contour& Contour::hoverlabel(Callable&& c) {
    Hoverlabel f{};
    std::forward<Callable>(c)(f);
    return hoverlabel(std::move(f));
}

inline Contour& Contour::hoverongaps(bool f) {
    json["hoverongaps"] = std::move(f);
    return *this;
}

inline Contour& Contour::hovertemplate(std::string f) {
    json["hovertemplate"] = std::move(f);
    return *this;
}
inline Contour& Contour::hovertemplate(const std::vector<std::string>& f) {
    json["hovertemplate"] = f;
    return *this;
}

inline Contour& Contour::hovertemplatesrc(std::string f) {
    json["hovertemplatesrc"] = std::move(f);
    return *this;
}

template <typename Range, typename>
inline Contour& Contour::hovertext(Range&& f) {
    json["hovertext"] = f;
    return *this;
}

inline Contour& Contour::hovertextsrc(std::string f) {
    json["hovertextsrc"] = std::move(f);
    return *this;
}

template <typename Range, typename>
inline Contour& Contour::ids(Range&& f) {
    json["ids"] = f;
    return *this;
}

inline Contour& Contour::idssrc(std::string f) {
    json["idssrc"] = std::move(f);
    return *this;
}

inline Contour& Contour::legend(std::string f) {
    json["legend"] = std::move(f);
    return *this;
}

inline Contour& Contour::legendgroup(std::string f) {
    json["legendgroup"] = std::move(f);
    return *this;
}

inline Contour& Contour::legendgrouptitle(Legendgrouptitle f) {
    json["legendgrouptitle"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Contour& Contour::legendgrouptitle(Callable&& c) {
    Legendgrouptitle f{};
    std::forward<Callable>(c)(f);
    return legendgrouptitle(std::move(f));
}

inline Contour& Contour::legendrank(double f) {
    json["legendrank"] = std::move(f);
    return *this;
}

inline Contour& Contour::legendwidth(double f) {
    json["legendwidth"] = std::move(f);
    return *this;
}

inline Contour& Contour::line(Line f) {
    json["line"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Contour& Contour::line(Callable&& c) {
    Line f{};
    std::forward<Callable>(c)(f);
    return line(std::move(f));
}

template <typename T>
inline Contour& Contour::meta(T f) {
    json["meta"] = std::move(f);
    return *this;
}
template <typename T>
inline Contour& Contour::meta(const std::vector<T>& f) {
    json["meta"] = f;
    return *this;
}

inline Contour& Contour::metasrc(std::string f) {
    json["metasrc"] = std::move(f);
    return *this;
}

inline Contour& Contour::name(std::string f) {
    json["name"] = std::move(f);
    return *this;
}

inline Contour& Contour::ncontours(int f) {
    json["ncontours"] = std::move(f);
    return *this;
}

inline Contour& Contour::opacity(double f) {
    json["opacity"] = std::move(f);
    return *this;
}

inline Contour& Contour::reversescale(bool f) {
    json["reversescale"] = std::move(f);
    return *this;
}

inline Contour& Contour::showlegend(bool f) {
    json["showlegend"] = std::move(f);
    return *this;
}

inline Contour& Contour::showscale(bool f) {
    json["showscale"] = std::move(f);
    return *this;
}

inline Contour& Contour::stream(Stream f) {
    json["stream"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Contour& Contour::stream(Callable&& c) {
    Stream f{};
    std::forward<Callable>(c)(f);
    return stream(std::move(f));
}

template <typename Range, typename>
inline Contour& Contour::text(Range&& f) {
    json["text"] = f;
    return *this;
}

inline Contour& Contour::textfont(Textfont f) {
    json["textfont"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Contour& Contour::textfont(Callable&& c) {
    Textfont f{};
    std::forward<Callable>(c)(f);
    return textfont(std::move(f));
}

inline Contour& Contour::textsrc(std::string f) {
    json["textsrc"] = std::move(f);
    return *this;
}

inline Contour& Contour::texttemplate(std::string f) {
    json["texttemplate"] = std::move(f);
    return *this;
}

inline Contour& Contour::transpose(bool f) {
    json["transpose"] = std::move(f);
    return *this;
}

inline Contour& Contour::uid(std::string f) {
    json["uid"] = std::move(f);
    return *this;
}

template <typename T>
inline Contour& Contour::uirevision(T f) {
    json["uirevision"] = std::move(f);
    return *this;
}

inline Contour& Contour::visible(enum Visible f) {
    switch(f) {
        case Visible::True: json["visible"] = true; break;
        case Visible::False: json["visible"] = false; break;
        case Visible::Legendonly: json["visible"] = "legendonly"; break;
    }
    return *this;
}

template <typename Range, typename>
inline Contour& Contour::x(Range&& f) {
    json["x"] = f;
    return *this;
}

template <typename T>
inline Contour& Contour::x0(T f) {
    json["x0"] = std::move(f);
    return *this;
}

inline Contour& Contour::xaxis(std::string f) {
    json["xaxis"] = std::move(f);
    return *this;
}

inline Contour& Contour::xcalendar(enum Xcalendar f) {
    switch(f) {
        case Xcalendar::Chinese: json["xcalendar"] = "chinese"; break;
        case Xcalendar::Coptic: json["xcalendar"] = "coptic"; break;
        case Xcalendar::Discworld: json["xcalendar"] = "discworld"; break;
        case Xcalendar::Ethiopian: json["xcalendar"] = "ethiopian"; break;
        case Xcalendar::Gregorian: json["xcalendar"] = "gregorian"; break;
        case Xcalendar::Hebrew: json["xcalendar"] = "hebrew"; break;
        case Xcalendar::Islamic: json["xcalendar"] = "islamic"; break;
        case Xcalendar::Jalali: json["xcalendar"] = "jalali"; break;
        case Xcalendar::Julian: json["xcalendar"] = "julian"; break;
        case Xcalendar::Mayan: json["xcalendar"] = "mayan"; break;
        case Xcalendar::Nanakshahi: json["xcalendar"] = "nanakshahi"; break;
        case Xcalendar::Nepali: json["xcalendar"] = "nepali"; break;
        case Xcalendar::Persian: json["xcalendar"] = "persian"; break;
        case Xcalendar::Taiwan: json["xcalendar"] = "taiwan"; break;
        case Xcalendar::Thai: json["xcalendar"] = "thai"; break;
        case Xcalendar::Ummalqura: json["xcalendar"] = "ummalqura"; break;
    }
    return *this;
}

inline Contour& Contour::xhoverformat(std::string f) {
    json["xhoverformat"] = std::move(f);
    return *this;
}

template <typename T>
inline Contour& Contour::xperiod(T f) {
    json["xperiod"] = std::move(f);
    return *this;
}

template <typename T>
inline Contour& Contour::xperiod0(T f) {
    json["xperiod0"] = std::move(f);
    return *this;
}

inline Contour& Contour::xperiodalignment(enum Xperiodalignment f) {
    switch(f) {
        case Xperiodalignment::Start: json["xperiodalignment"] = "start"; break;
        case Xperiodalignment::Middle: json["xperiodalignment"] = "middle"; break;
        case Xperiodalignment::End: json["xperiodalignment"] = "end"; break;
    }
    return *this;
}

inline Contour& Contour::xsrc(std::string f) {
    json["xsrc"] = std::move(f);
    return *this;
}

inline Contour& Contour::xtype(enum Xtype f) {
    switch(f) {
        case Xtype::Array: json["xtype"] = "array"; break;
        case Xtype::Scaled: json["xtype"] = "scaled"; break;
    }
    return *this;
}

template <typename Range, typename>
inline Contour& Contour::y(Range&& f) {
    json["y"] = f;
    return *this;
}

template <typename T>
inline Contour& Contour::y0(T f) {
    json["y0"] = std::move(f);
    return *this;
}

inline Contour& Contour::yaxis(std::string f) {
    json["yaxis"] = std::move(f);
    return *this;
}

inline Contour& Contour::ycalendar(enum Ycalendar f) {
    switch(f) {
        case Ycalendar::Chinese: json["ycalendar"] = "chinese"; break;
        case Ycalendar::Coptic: json["ycalendar"] = "coptic"; break;
        case Ycalendar::Discworld: json["ycalendar"] = "discworld"; break;
        case Ycalendar::Ethiopian: json["ycalendar"] = "ethiopian"; break;
        case Ycalendar::Gregorian: json["ycalendar"] = "gregorian"; break;
        case Ycalendar::Hebrew: json["ycalendar"] = "hebrew"; break;
        case Ycalendar::Islamic: json["ycalendar"] = "islamic"; break;
        case Ycalendar::Jalali: json["ycalendar"] = "jalali"; break;
        case Ycalendar::Julian: json["ycalendar"] = "julian"; break;
        case Ycalendar::Mayan: json["ycalendar"] = "mayan"; break;
        case Ycalendar::Nanakshahi: json["ycalendar"] = "nanakshahi"; break;
        case Ycalendar::Nepali: json["ycalendar"] = "nepali"; break;
        case Ycalendar::Persian: json["ycalendar"] = "persian"; break;
        case Ycalendar::Taiwan: json["ycalendar"] = "taiwan"; break;
        case Ycalendar::Thai: json["ycalendar"] = "thai"; break;
        case Ycalendar::Ummalqura: json["ycalendar"] = "ummalqura"; break;
    }
    return *this;
}

inline Contour& Contour::yhoverformat(std::string f) {
    json["yhoverformat"] = std::move(f);
    return *this;
}

template <typename T>
inline Contour& Contour::yperiod(T f) {
    json["yperiod"] = std::move(f);
    return *this;
}

template <typename T>
inline Contour& Contour::yperiod0(T f) {
    json["yperiod0"] = std::move(f);
    return *this;
}

inline Contour& Contour::yperiodalignment(enum Yperiodalignment f) {
    switch(f) {
        case Yperiodalignment::Start: json["yperiodalignment"] = "start"; break;
        case Yperiodalignment::Middle: json["yperiodalignment"] = "middle"; break;
        case Yperiodalignment::End: json["yperiodalignment"] = "end"; break;
    }
    return *this;
}

inline Contour& Contour::ysrc(std::string f) {
    json["ysrc"] = std::move(f);
    return *this;
}

inline Contour& Contour::ytype(enum Ytype f) {
    switch(f) {
        case Ytype::Array: json["ytype"] = "array"; break;
        case Ytype::Scaled: json["ytype"] = "scaled"; break;
    }
    return *this;
}

template <typename Range, typename>
inline Contour& Contour::z(Range&& f) {
    json["z"] = f;
    return *this;
}

inline Contour& Contour::zauto(bool f) {
    json["zauto"] = std::move(f);
    return *this;
}

inline Contour& Contour::zhoverformat(std::string f) {
    json["zhoverformat"] = std::move(f);
    return *this;
}

inline Contour& Contour::zmax(double f) {
    json["zmax"] = std::move(f);
    return *this;
}

inline Contour& Contour::zmid(double f) {
    json["zmid"] = std::move(f);
    return *this;
}

inline Contour& Contour::zmin(double f) {
    json["zmin"] = std::move(f);
    return *this;
}

inline Contour& Contour::zorder(int f) {
    json["zorder"] = std::move(f);
    return *this;
}

inline Contour& Contour::zsrc(std::string f) {
    json["zsrc"] = std::move(f);
    return *this;
}


inline Contour::Colorbar& Contour::Colorbar::bgcolor(std::string f) {
    json["bgcolor"] = std::move(f);
    return *this;
}
inline Contour::Colorbar& Contour::Colorbar::bgcolor(double f) {
    json["bgcolor"] = std::move(f);
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::bordercolor(std::string f) {
    json["bordercolor"] = std::move(f);
    return *this;
}
inline Contour::Colorbar& Contour::Colorbar::bordercolor(double f) {
    json["bordercolor"] = std::move(f);
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::borderwidth(double f) {
    json["borderwidth"] = std::move(f);
    return *this;
}

template <typename T>
inline Contour::Colorbar& Contour::Colorbar::dtick(T f) {
    json["dtick"] = std::move(f);
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::exponentformat(enum Exponentformat f) {
    switch(f) {
        case Exponentformat::None: json["exponentformat"] = "none"; break;
        case Exponentformat::E: json["exponentformat"] = "E"; break;
        case Exponentformat::Power: json["exponentformat"] = "power"; break;
        case Exponentformat::Si: json["exponentformat"] = "SI"; break;
        case Exponentformat::B: json["exponentformat"] = "B"; break;
    }
    return *this;
}

template <typename T>
inline Contour::Colorbar& Contour::Colorbar::labelalias(T f) {
    json["labelalias"] = std::move(f);
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::len(double f) {
    json["len"] = std::move(f);
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::lenmode(enum Lenmode f) {
    switch(f) {
        case Lenmode::Fraction: json["lenmode"] = "fraction"; break;
        case Lenmode::Pixels: json["lenmode"] = "pixels"; break;
    }
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::minexponent(double f) {
    json["minexponent"] = std::move(f);
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::nticks(int f) {
    json["nticks"] = std::move(f);
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::orientation(enum Orientation f) {
    switch(f) {
        case Orientation::H: json["orientation"] = "h"; break;
        case Orientation::V: json["orientation"] = "v"; break;
    }
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::outlinecolor(std::string f) {
    json["outlinecolor"] = std::move(f);
    return *this;
}
inline Contour::Colorbar& Contour::Colorbar::outlinecolor(double f) {
    json["outlinecolor"] = std::move(f);
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::outlinewidth(double f) {
    json["outlinewidth"] = std::move(f);
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::separatethousands(bool f) {
    json["separatethousands"] = std::move(f);
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::showexponent(enum Showexponent f) {
    switch(f) {
        case Showexponent::All: json["showexponent"] = "all"; break;
        case Showexponent::First: json["showexponent"] = "first"; break;
        case Showexponent::Last: json["showexponent"] = "last"; break;
        case Showexponent::None: json["showexponent"] = "none"; break;
    }
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::showticklabels(bool f) {
    json["showticklabels"] = std::move(f);
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::showtickprefix(enum Showtickprefix f) {
    switch(f) {
        case Showtickprefix::All: json["showtickprefix"] = "all"; break;
        case Showtickprefix::First: json["showtickprefix"] = "first"; break;
        case Showtickprefix::Last: json["showtickprefix"] = "last"; break;
        case Showtickprefix::None: json["showtickprefix"] = "none"; break;
    }
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::showticksuffix(enum Showticksuffix f) {
    switch(f) {
        case Showticksuffix::All: json["showticksuffix"] = "all"; break;
        case Showticksuffix::First: json["showticksuffix"] = "first"; break;
        case Showticksuffix::Last: json["showticksuffix"] = "last"; break;
        case Showticksuffix::None: json["showticksuffix"] = "none"; break;
    }
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::thickness(double f) {
    json["thickness"] = std::move(f);
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::thicknessmode(enum Thicknessmode f) {
    switch(f) {
        case Thicknessmode::Fraction: json["thicknessmode"] = "fraction"; break;
        case Thicknessmode::Pixels: json["thicknessmode"] = "pixels"; break;
    }
    return *this;
}

template <typename T>
inline Contour::Colorbar& Contour::Colorbar::tick0(T f) {
    json["tick0"] = std::move(f);
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::tickangle(double f) {
    json["tickangle"] = std::move(f);
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::tickcolor(std::string f) {
    json["tickcolor"] = std::move(f);
    return *this;
}
inline Contour::Colorbar& Contour::Colorbar::tickcolor(double f) {
    json["tickcolor"] = std::move(f);
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::tickfont(Tickfont f) {
    json["tickfont"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Contour::Colorbar& Contour::Colorbar::tickfont(Callable&& c) {
    Tickfont f{};
    std::forward<Callable>(c)(f);
    return tickfont(std::move(f));
}

inline Contour::Colorbar& Contour::Colorbar::tickformat(std::string f) {
    json["tickformat"] = std::move(f);
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::tickformatstops(const std::vector<Tickformatstop>& f) {
    std::vector<Json> jsonified(f.size());
    std::transform(f.begin(), f.end(), jsonified.begin(), [](auto& e){ return e.json; });
    json["tickformatstops"] = std::move(jsonified);
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::ticklabeloverflow(enum Ticklabeloverflow f) {
    switch(f) {
        case Ticklabeloverflow::Allow: json["ticklabeloverflow"] = "allow"; break;
        case Ticklabeloverflow::HidePastDiv: json["ticklabeloverflow"] = "hide past div"; break;
        case Ticklabeloverflow::HidePastDomain: json["ticklabeloverflow"] = "hide past domain"; break;
    }
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::ticklabelposition(enum Ticklabelposition f) {
    switch(f) {
        case Ticklabelposition::Outside: json["ticklabelposition"] = "outside"; break;
        case Ticklabelposition::Inside: json["ticklabelposition"] = "inside"; break;
        case Ticklabelposition::OutsideTop: json["ticklabelposition"] = "outside top"; break;
        case Ticklabelposition::InsideTop: json["ticklabelposition"] = "inside top"; break;
        case Ticklabelposition::OutsideLeft: json["ticklabelposition"] = "outside left"; break;
        case Ticklabelposition::InsideLeft: json["ticklabelposition"] = "inside left"; break;
        case Ticklabelposition::OutsideRight: json["ticklabelposition"] = "outside right"; break;
        case Ticklabelposition::InsideRight: json["ticklabelposition"] = "inside right"; break;
        case Ticklabelposition::OutsideBottom: json["ticklabelposition"] = "outside bottom"; break;
        case Ticklabelposition::InsideBottom: json["ticklabelposition"] = "inside bottom"; break;
    }
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::ticklabelstep(int f) {
    json["ticklabelstep"] = std::move(f);
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::ticklen(double f) {
    json["ticklen"] = std::move(f);
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::tickmode(enum Tickmode f) {
    switch(f) {
        case Tickmode::Auto: json["tickmode"] = "auto"; break;
        case Tickmode::Linear: json["tickmode"] = "linear"; break;
        case Tickmode::Array: json["tickmode"] = "array"; break;
    }
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::tickprefix(std::string f) {
    json["tickprefix"] = std::move(f);
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::ticks(enum Ticks f) {
    switch(f) {
        case Ticks::Outside: json["ticks"] = "outside"; break;
        case Ticks::Inside: json["ticks"] = "inside"; break;
        case Ticks::Empty: json["ticks"] = ""; break;
    }
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::ticksuffix(std::string f) {
    json["ticksuffix"] = std::move(f);
    return *this;
}

template <typename Range, typename>
inline Contour::Colorbar& Contour::Colorbar::ticktext(Range&& f) {
    json["ticktext"] = f;
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::ticktextsrc(std::string f) {
    json["ticktextsrc"] = std::move(f);
    return *this;
}

template <typename Range, typename>
inline Contour::Colorbar& Contour::Colorbar::tickvals(Range&& f) {
    json["tickvals"] = f;
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::tickvalssrc(std::string f) {
    json["tickvalssrc"] = std::move(f);
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::tickwidth(double f) {
    json["tickwidth"] = std::move(f);
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::title(Title f) {
    json["title"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Contour::Colorbar& Contour::Colorbar::title(Callable&& c) {
    Title f{};
    std::forward<Callable>(c)(f);
    return title(std::move(f));
}

inline Contour::Colorbar& Contour::Colorbar::x(double f) {
    json["x"] = std::move(f);
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::xanchor(enum Xanchor f) {
    switch(f) {
        case Xanchor::Left: json["xanchor"] = "left"; break;
        case Xanchor::Center: json["xanchor"] = "center"; break;
        case Xanchor::Right: json["xanchor"] = "right"; break;
    }
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::xpad(double f) {
    json["xpad"] = std::move(f);
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::xref(enum Xref f) {
    switch(f) {
        case Xref::Container: json["xref"] = "container"; break;
        case Xref::Paper: json["xref"] = "paper"; break;
    }
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::y(double f) {
    json["y"] = std::move(f);
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::yanchor(enum Yanchor f) {
    switch(f) {
        case Yanchor::Top: json["yanchor"] = "top"; break;
        case Yanchor::Middle: json["yanchor"] = "middle"; break;
        case Yanchor::Bottom: json["yanchor"] = "bottom"; break;
    }
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::ypad(double f) {
    json["ypad"] = std::move(f);
    return *this;
}

inline Contour::Colorbar& Contour::Colorbar::yref(enum Yref f) {
    switch(f) {
        case Yref::Container: json["yref"] = "container"; break;
        case Yref::Paper: json["yref"] = "paper"; break;
    }
    return *this;
}

inline std::string Contour::Colorbar::Tickfont::to_string(Lineposition e) {
    switch(e) {
        case Lineposition::Under: return "under";
        case Lineposition::Over: return "over";
        case Lineposition::Through: return "through";
    }
    throw std::invalid_argument{"Unknown flag value for lineposition."};
}
inline std::string Contour::Colorbar::Tickfont::to_string(LinepositionExtra e) {
    switch(e) {
        case LinepositionExtra::None: return "none";
    }
    throw std::invalid_argument{"Unknown extra value for lineposition."};
}

inline Contour::Colorbar::Tickfont& Contour::Colorbar::Tickfont::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Contour::Colorbar::Tickfont& Contour::Colorbar::Tickfont::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

inline Contour::Colorbar::Tickfont& Contour::Colorbar::Tickfont::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}

inline Contour::Colorbar::Tickfont& Contour::Colorbar::Tickfont::lineposition(std::initializer_list<Lineposition> flags) {
    json["lineposition"] = detail::joinFlaglist(flags, [](auto f){ return to_string(f); });
    return *this;
}
inline Contour::Colorbar::Tickfont& Contour::Colorbar::Tickfont::lineposition(LinepositionExtra extra) {
    json["lineposition"] = to_string(extra);
    return *this;
}

inline Contour::Colorbar::Tickfont& Contour::Colorbar::Tickfont::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}

inline Contour::Colorbar::Tickfont& Contour::Colorbar::Tickfont::size(double f) {
    json["size"] = std::move(f);
    return *this;
}

inline Contour::Colorbar::Tickfont& Contour::Colorbar::Tickfont::style(enum Style f) {
    switch(f) {
        case Style::Normal: json["style"] = "normal"; break;
        case Style::Italic: json["style"] = "italic"; break;
    }
    return *this;
}

inline Contour::Colorbar::Tickfont& Contour::Colorbar::Tickfont::textcase(enum Textcase f) {
    switch(f) {
        case Textcase::Normal: json["textcase"] = "normal"; break;
        case Textcase::WordCaps: json["textcase"] = "word caps"; break;
        case Textcase::Upper: json["textcase"] = "upper"; break;
        case Textcase::Lower: json["textcase"] = "lower"; break;
    }
    return *this;
}

inline Contour::Colorbar::Tickfont& Contour::Colorbar::Tickfont::variant(enum Variant f) {
    switch(f) {
        case Variant::Normal: json["variant"] = "normal"; break;
        case Variant::SmallCaps: json["variant"] = "small-caps"; break;
        case Variant::AllSmallCaps: json["variant"] = "all-small-caps"; break;
        case Variant::AllPetiteCaps: json["variant"] = "all-petite-caps"; break;
        case Variant::PetiteCaps: json["variant"] = "petite-caps"; break;
        case Variant::Unicase: json["variant"] = "unicase"; break;
    }
    return *this;
}

inline Contour::Colorbar::Tickfont& Contour::Colorbar::Tickfont::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}


inline Contour::Colorbar::Tickformatstop& Contour::Colorbar::Tickformatstop::dtickrange(const std::vector<double>& f) {
    json["dtickrange"] = f;
    return *this;
}
inline Contour::Colorbar::Tickformatstop& Contour::Colorbar::Tickformatstop::dtickrange(const std::vector<std::string>& f) {
    json["dtickrange"] = f;
    return *this;
}
inline Contour::Colorbar::Tickformatstop& Contour::Colorbar::Tickformatstop::dtickrange(const std::vector<std::vector<std::string>>& f) {
    json["dtickrange"] = f;
    return *this;
}
inline Contour::Colorbar::Tickformatstop& Contour::Colorbar::Tickformatstop::dtickrange(const std::vector<std::vector<double>>& f) {
    json["dtickrange"] = f;
    return *this;
}

inline Contour::Colorbar::Tickformatstop& Contour::Colorbar::Tickformatstop::enabled(bool f) {
    json["enabled"] = std::move(f);
    return *this;
}

inline Contour::Colorbar::Tickformatstop& Contour::Colorbar::Tickformatstop::name(std::string f) {
    json["name"] = std::move(f);
    return *this;
}

inline Contour::Colorbar::Tickformatstop& Contour::Colorbar::Tickformatstop::templateitemname(std::string f) {
    json["templateitemname"] = std::move(f);
    return *this;
}

inline Contour::Colorbar::Tickformatstop& Contour::Colorbar::Tickformatstop::value(std::string f) {
    json["value"] = std::move(f);
    return *this;
}


inline Contour::Colorbar::Title& Contour::Colorbar::Title::font(Font f) {
    json["font"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Contour::Colorbar::Title& Contour::Colorbar::Title::font(Callable&& c) {
    Font f{};
    std::forward<Callable>(c)(f);
    return font(std::move(f));
}

inline Contour::Colorbar::Title& Contour::Colorbar::Title::side(enum Side f) {
    switch(f) {
        case Side::Right: json["side"] = "right"; break;
        case Side::Top: json["side"] = "top"; break;
        case Side::Bottom: json["side"] = "bottom"; break;
    }
    return *this;
}

inline Contour::Colorbar::Title& Contour::Colorbar::Title::text(std::string f) {
    json["text"] = std::move(f);
    return *this;
}

inline std::string Contour::Colorbar::Title::Font::to_string(Lineposition e) {
    switch(e) {
        case Lineposition::Under: return "under";
        case Lineposition::Over: return "over";
        case Lineposition::Through: return "through";
    }
    throw std::invalid_argument{"Unknown flag value for lineposition."};
}
inline std::string Contour::Colorbar::Title::Font::to_string(LinepositionExtra e) {
    switch(e) {
        case LinepositionExtra::None: return "none";
    }
    throw std::invalid_argument{"Unknown extra value for lineposition."};
}

inline Contour::Colorbar::Title::Font& Contour::Colorbar::Title::Font::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Contour::Colorbar::Title::Font& Contour::Colorbar::Title::Font::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

inline Contour::Colorbar::Title::Font& Contour::Colorbar::Title::Font::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}

inline Contour::Colorbar::Title::Font& Contour::Colorbar::Title::Font::lineposition(std::initializer_list<Lineposition> flags) {
    json["lineposition"] = detail::joinFlaglist(flags, [](auto f){ return to_string(f); });
    return *this;
}
inline Contour::Colorbar::Title::Font& Contour::Colorbar::Title::Font::lineposition(LinepositionExtra extra) {
    json["lineposition"] = to_string(extra);
    return *this;
}

inline Contour::Colorbar::Title::Font& Contour::Colorbar::Title::Font::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}

inline Contour::Colorbar::Title::Font& Contour::Colorbar::Title::Font::size(double f) {
    json["size"] = std::move(f);
    return *this;
}

inline Contour::Colorbar::Title::Font& Contour::Colorbar::Title::Font::style(enum Style f) {
    switch(f) {
        case Style::Normal: json["style"] = "normal"; break;
        case Style::Italic: json["style"] = "italic"; break;
    }
    return *this;
}

inline Contour::Colorbar::Title::Font& Contour::Colorbar::Title::Font::textcase(enum Textcase f) {
    switch(f) {
        case Textcase::Normal: json["textcase"] = "normal"; break;
        case Textcase::WordCaps: json["textcase"] = "word caps"; break;
        case Textcase::Upper: json["textcase"] = "upper"; break;
        case Textcase::Lower: json["textcase"] = "lower"; break;
    }
    return *this;
}

inline Contour::Colorbar::Title::Font& Contour::Colorbar::Title::Font::variant(enum Variant f) {
    switch(f) {
        case Variant::Normal: json["variant"] = "normal"; break;
        case Variant::SmallCaps: json["variant"] = "small-caps"; break;
        case Variant::AllSmallCaps: json["variant"] = "all-small-caps"; break;
        case Variant::AllPetiteCaps: json["variant"] = "all-petite-caps"; break;
        case Variant::PetiteCaps: json["variant"] = "petite-caps"; break;
        case Variant::Unicase: json["variant"] = "unicase"; break;
    }
    return *this;
}

inline Contour::Colorbar::Title::Font& Contour::Colorbar::Title::Font::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}


inline Contour::Contours& Contour::Contours::coloring(enum Coloring f) {
    switch(f) {
        case Coloring::Fill: json["coloring"] = "fill"; break;
        case Coloring::Heatmap: json["coloring"] = "heatmap"; break;
        case Coloring::Lines: json["coloring"] = "lines"; break;
        case Coloring::None: json["coloring"] = "none"; break;
    }
    return *this;
}

inline Contour::Contours& Contour::Contours::end(double f) {
    json["end"] = std::move(f);
    return *this;
}

inline Contour::Contours& Contour::Contours::impliedEdits(Impliededits f) {
    json["impliedEdits"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Contour::Contours& Contour::Contours::impliedEdits(Callable&& c) {
    Impliededits f{};
    std::forward<Callable>(c)(f);
    return impliedEdits(std::move(f));
}

inline Contour::Contours& Contour::Contours::labelfont(Labelfont f) {
    json["labelfont"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Contour::Contours& Contour::Contours::labelfont(Callable&& c) {
    Labelfont f{};
    std::forward<Callable>(c)(f);
    return labelfont(std::move(f));
}

inline Contour::Contours& Contour::Contours::labelformat(std::string f) {
    json["labelformat"] = std::move(f);
    return *this;
}

inline Contour::Contours& Contour::Contours::operation(std::string f) {
    json["operation"] = std::move(f);
    return *this;
}

inline Contour::Contours& Contour::Contours::showlabels(bool f) {
    json["showlabels"] = std::move(f);
    return *this;
}

inline Contour::Contours& Contour::Contours::showlines(bool f) {
    json["showlines"] = std::move(f);
    return *this;
}

inline Contour::Contours& Contour::Contours::size(double f) {
    json["size"] = std::move(f);
    return *this;
}

inline Contour::Contours& Contour::Contours::start(double f) {
    json["start"] = std::move(f);
    return *this;
}

inline Contour::Contours& Contour::Contours::type(enum Type f) {
    switch(f) {
        case Type::Levels: json["type"] = "levels"; break;
        case Type::Constraint: json["type"] = "constraint"; break;
    }
    return *this;
}

template <typename T>
inline Contour::Contours& Contour::Contours::value(T f) {
    json["value"] = std::move(f);
    return *this;
}


inline std::string Contour::Contours::Labelfont::to_string(Lineposition e) {
    switch(e) {
        case Lineposition::Under: return "under";
        case Lineposition::Over: return "over";
        case Lineposition::Through: return "through";
    }
    throw std::invalid_argument{"Unknown flag value for lineposition."};
}
inline std::string Contour::Contours::Labelfont::to_string(LinepositionExtra e) {
    switch(e) {
        case LinepositionExtra::None: return "none";
    }
    throw std::invalid_argument{"Unknown extra value for lineposition."};
}

inline Contour::Contours::Labelfont& Contour::Contours::Labelfont::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Contour::Contours::Labelfont& Contour::Contours::Labelfont::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

inline Contour::Contours::Labelfont& Contour::Contours::Labelfont::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}

inline Contour::Contours::Labelfont& Contour::Contours::Labelfont::lineposition(std::initializer_list<Lineposition> flags) {
    json["lineposition"] = detail::joinFlaglist(flags, [](auto f){ return to_string(f); });
    return *this;
}
inline Contour::Contours::Labelfont& Contour::Contours::Labelfont::lineposition(LinepositionExtra extra) {
    json["lineposition"] = to_string(extra);
    return *this;
}

inline Contour::Contours::Labelfont& Contour::Contours::Labelfont::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}

inline Contour::Contours::Labelfont& Contour::Contours::Labelfont::size(double f) {
    json["size"] = std::move(f);
    return *this;
}

inline Contour::Contours::Labelfont& Contour::Contours::Labelfont::style(enum Style f) {
    switch(f) {
        case Style::Normal: json["style"] = "normal"; break;
        case Style::Italic: json["style"] = "italic"; break;
    }
    return *this;
}

inline Contour::Contours::Labelfont& Contour::Contours::Labelfont::textcase(enum Textcase f) {
    switch(f) {
        case Textcase::Normal: json["textcase"] = "normal"; break;
        case Textcase::WordCaps: json["textcase"] = "word caps"; break;
        case Textcase::Upper: json["textcase"] = "upper"; break;
        case Textcase::Lower: json["textcase"] = "lower"; break;
    }
    return *this;
}

inline Contour::Contours::Labelfont& Contour::Contours::Labelfont::variant(enum Variant f) {
    switch(f) {
        case Variant::Normal: json["variant"] = "normal"; break;
        case Variant::SmallCaps: json["variant"] = "small-caps"; break;
        case Variant::AllSmallCaps: json["variant"] = "all-small-caps"; break;
        case Variant::AllPetiteCaps: json["variant"] = "all-petite-caps"; break;
        case Variant::PetiteCaps: json["variant"] = "petite-caps"; break;
        case Variant::Unicase: json["variant"] = "unicase"; break;
    }
    return *this;
}

inline Contour::Contours::Labelfont& Contour::Contours::Labelfont::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}


inline Contour::Hoverlabel& Contour::Hoverlabel::align(enum Align f) {
    switch(f) {
        case Align::Left: json["align"] = "left"; break;
        case Align::Right: json["align"] = "right"; break;
        case Align::Auto: json["align"] = "auto"; break;
    }
    return *this;
}
inline Contour::Hoverlabel& Contour::Hoverlabel::align(const std::vector<enum Align>& f) {
    Json arr = Json::array();
    for(const auto& e : f) {
        switch(e) {
            case Align::Left: arr.push_back("left"); break;
            case Align::Right: arr.push_back("right"); break;
            case Align::Auto: arr.push_back("auto"); break;
        }
    }
    json["align"] = std::move(arr);
    return *this;
}

inline Contour::Hoverlabel& Contour::Hoverlabel::alignsrc(std::string f) {
    json["alignsrc"] = std::move(f);
    return *this;
}

inline Contour::Hoverlabel& Contour::Hoverlabel::bgcolor(std::string f) {
    json["bgcolor"] = std::move(f);
    return *this;
}
inline Contour::Hoverlabel& Contour::Hoverlabel::bgcolor(double f) {
    json["bgcolor"] = std::move(f);
    return *this;
}
inline Contour::Hoverlabel& Contour::Hoverlabel::bgcolor(const std::vector<std::string>& f) {
    json["bgcolor"] = f;
    return *this;
}
inline Contour::Hoverlabel& Contour::Hoverlabel::bgcolor(const std::vector<double>& f) {
    json["bgcolor"] = f;
    return *this;
}

inline Contour::Hoverlabel& Contour::Hoverlabel::bgcolorsrc(std::string f) {
    json["bgcolorsrc"] = std::move(f);
    return *this;
}

inline Contour::Hoverlabel& Contour::Hoverlabel::bordercolor(std::string f) {
    json["bordercolor"] = std::move(f);
    return *this;
}
inline Contour::Hoverlabel& Contour::Hoverlabel::bordercolor(double f) {
    json["bordercolor"] = std::move(f);
    return *this;
}
inline Contour::Hoverlabel& Contour::Hoverlabel::bordercolor(const std::vector<std::string>& f) {
    json["bordercolor"] = f;
    return *this;
}
inline Contour::Hoverlabel& Contour::Hoverlabel::bordercolor(const std::vector<double>& f) {
    json["bordercolor"] = f;
    return *this;
}

inline Contour::Hoverlabel& Contour::Hoverlabel::bordercolorsrc(std::string f) {
    json["bordercolorsrc"] = std::move(f);
    return *this;
}

inline Contour::Hoverlabel& Contour::Hoverlabel::font(Font f) {
    json["font"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Contour::Hoverlabel& Contour::Hoverlabel::font(Callable&& c) {
    Font f{};
    std::forward<Callable>(c)(f);
    return font(std::move(f));
}

inline Contour::Hoverlabel& Contour::Hoverlabel::namelength(int f) {
    json["namelength"] = std::move(f);
    return *this;
}
inline Contour::Hoverlabel& Contour::Hoverlabel::namelength(const std::vector<int>& f) {
    json["namelength"] = f;
    return *this;
}

inline Contour::Hoverlabel& Contour::Hoverlabel::namelengthsrc(std::string f) {
    json["namelengthsrc"] = std::move(f);
    return *this;
}

inline std::string Contour::Hoverlabel::Font::to_string(Lineposition e) {
    switch(e) {
        case Lineposition::Under: return "under";
        case Lineposition::Over: return "over";
        case Lineposition::Through: return "through";
    }
    throw std::invalid_argument{"Unknown flag value for lineposition."};
}
inline std::string Contour::Hoverlabel::Font::to_string(LinepositionExtra e) {
    switch(e) {
        case LinepositionExtra::None: return "none";
    }
    throw std::invalid_argument{"Unknown extra value for lineposition."};
}

inline Contour::Hoverlabel::Font& Contour::Hoverlabel::Font::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Contour::Hoverlabel::Font& Contour::Hoverlabel::Font::color(double f) {
    json["color"] = std::move(f);
    return *this;
}
inline Contour::Hoverlabel::Font& Contour::Hoverlabel::Font::color(const std::vector<std::string>& f) {
    json["color"] = f;
    return *this;
}
inline Contour::Hoverlabel::Font& Contour::Hoverlabel::Font::color(const std::vector<double>& f) {
    json["color"] = f;
    return *this;
}

inline Contour::Hoverlabel::Font& Contour::Hoverlabel::Font::colorsrc(std::string f) {
    json["colorsrc"] = std::move(f);
    return *this;
}

inline Contour::Hoverlabel::Font& Contour::Hoverlabel::Font::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}
inline Contour::Hoverlabel::Font& Contour::Hoverlabel::Font::family(const std::vector<std::string>& f) {
    json["family"] = f;
    return *this;
}

inline Contour::Hoverlabel::Font& Contour::Hoverlabel::Font::familysrc(std::string f) {
    json["familysrc"] = std::move(f);
    return *this;
}

inline Contour::Hoverlabel::Font& Contour::Hoverlabel::Font::lineposition(std::initializer_list<Lineposition> flags) {
    json["lineposition"] = detail::joinFlaglist(flags, [](auto f){ return to_string(f); });
    return *this;
}
inline Contour::Hoverlabel::Font& Contour::Hoverlabel::Font::lineposition(LinepositionExtra extra) {
    json["lineposition"] = to_string(extra);
    return *this;
}

inline Contour::Hoverlabel::Font& Contour::Hoverlabel::Font::linepositionsrc(std::string f) {
    json["linepositionsrc"] = std::move(f);
    return *this;
}

inline Contour::Hoverlabel::Font& Contour::Hoverlabel::Font::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}
inline Contour::Hoverlabel::Font& Contour::Hoverlabel::Font::shadow(const std::vector<std::string>& f) {
    json["shadow"] = f;
    return *this;
}

inline Contour::Hoverlabel::Font& Contour::Hoverlabel::Font::shadowsrc(std::string f) {
    json["shadowsrc"] = std::move(f);
    return *this;
}

inline Contour::Hoverlabel::Font& Contour::Hoverlabel::Font::size(double f) {
    json["size"] = std::move(f);
    return *this;
}
inline Contour::Hoverlabel::Font& Contour::Hoverlabel::Font::size(const std::vector<double>& f) {
    json["size"] = f;
    return *this;
}

inline Contour::Hoverlabel::Font& Contour::Hoverlabel::Font::sizesrc(std::string f) {
    json["sizesrc"] = std::move(f);
    return *this;
}

inline Contour::Hoverlabel::Font& Contour::Hoverlabel::Font::style(enum Style f) {
    switch(f) {
        case Style::Normal: json["style"] = "normal"; break;
        case Style::Italic: json["style"] = "italic"; break;
    }
    return *this;
}
inline Contour::Hoverlabel::Font& Contour::Hoverlabel::Font::style(const std::vector<enum Style>& f) {
    Json arr = Json::array();
    for(const auto& e : f) {
        switch(e) {
            case Style::Normal: arr.push_back("normal"); break;
            case Style::Italic: arr.push_back("italic"); break;
        }
    }
    json["style"] = std::move(arr);
    return *this;
}

inline Contour::Hoverlabel::Font& Contour::Hoverlabel::Font::stylesrc(std::string f) {
    json["stylesrc"] = std::move(f);
    return *this;
}

inline Contour::Hoverlabel::Font& Contour::Hoverlabel::Font::textcase(enum Textcase f) {
    switch(f) {
        case Textcase::Normal: json["textcase"] = "normal"; break;
        case Textcase::WordCaps: json["textcase"] = "word caps"; break;
        case Textcase::Upper: json["textcase"] = "upper"; break;
        case Textcase::Lower: json["textcase"] = "lower"; break;
    }
    return *this;
}
inline Contour::Hoverlabel::Font& Contour::Hoverlabel::Font::textcase(const std::vector<enum Textcase>& f) {
    Json arr = Json::array();
    for(const auto& e : f) {
        switch(e) {
            case Textcase::Normal: arr.push_back("normal"); break;
            case Textcase::WordCaps: arr.push_back("word caps"); break;
            case Textcase::Upper: arr.push_back("upper"); break;
            case Textcase::Lower: arr.push_back("lower"); break;
        }
    }
    json["textcase"] = std::move(arr);
    return *this;
}

inline Contour::Hoverlabel::Font& Contour::Hoverlabel::Font::textcasesrc(std::string f) {
    json["textcasesrc"] = std::move(f);
    return *this;
}

inline Contour::Hoverlabel::Font& Contour::Hoverlabel::Font::variant(enum Variant f) {
    switch(f) {
        case Variant::Normal: json["variant"] = "normal"; break;
        case Variant::SmallCaps: json["variant"] = "small-caps"; break;
        case Variant::AllSmallCaps: json["variant"] = "all-small-caps"; break;
        case Variant::AllPetiteCaps: json["variant"] = "all-petite-caps"; break;
        case Variant::PetiteCaps: json["variant"] = "petite-caps"; break;
        case Variant::Unicase: json["variant"] = "unicase"; break;
    }
    return *this;
}
inline Contour::Hoverlabel::Font& Contour::Hoverlabel::Font::variant(const std::vector<enum Variant>& f) {
    Json arr = Json::array();
    for(const auto& e : f) {
        switch(e) {
            case Variant::Normal: arr.push_back("normal"); break;
            case Variant::SmallCaps: arr.push_back("small-caps"); break;
            case Variant::AllSmallCaps: arr.push_back("all-small-caps"); break;
            case Variant::AllPetiteCaps: arr.push_back("all-petite-caps"); break;
            case Variant::PetiteCaps: arr.push_back("petite-caps"); break;
            case Variant::Unicase: arr.push_back("unicase"); break;
        }
    }
    json["variant"] = std::move(arr);
    return *this;
}

inline Contour::Hoverlabel::Font& Contour::Hoverlabel::Font::variantsrc(std::string f) {
    json["variantsrc"] = std::move(f);
    return *this;
}

inline Contour::Hoverlabel::Font& Contour::Hoverlabel::Font::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}
inline Contour::Hoverlabel::Font& Contour::Hoverlabel::Font::weight(const std::vector<int>& f) {
    json["weight"] = f;
    return *this;
}

inline Contour::Hoverlabel::Font& Contour::Hoverlabel::Font::weightsrc(std::string f) {
    json["weightsrc"] = std::move(f);
    return *this;
}


inline Contour::Legendgrouptitle& Contour::Legendgrouptitle::font(Font f) {
    json["font"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Contour::Legendgrouptitle& Contour::Legendgrouptitle::font(Callable&& c) {
    Font f{};
    std::forward<Callable>(c)(f);
    return font(std::move(f));
}

inline Contour::Legendgrouptitle& Contour::Legendgrouptitle::text(std::string f) {
    json["text"] = std::move(f);
    return *this;
}

inline std::string Contour::Legendgrouptitle::Font::to_string(Lineposition e) {
    switch(e) {
        case Lineposition::Under: return "under";
        case Lineposition::Over: return "over";
        case Lineposition::Through: return "through";
    }
    throw std::invalid_argument{"Unknown flag value for lineposition."};
}
inline std::string Contour::Legendgrouptitle::Font::to_string(LinepositionExtra e) {
    switch(e) {
        case LinepositionExtra::None: return "none";
    }
    throw std::invalid_argument{"Unknown extra value for lineposition."};
}

inline Contour::Legendgrouptitle::Font& Contour::Legendgrouptitle::Font::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Contour::Legendgrouptitle::Font& Contour::Legendgrouptitle::Font::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

inline Contour::Legendgrouptitle::Font& Contour::Legendgrouptitle::Font::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}

inline Contour::Legendgrouptitle::Font& Contour::Legendgrouptitle::Font::lineposition(std::initializer_list<Lineposition> flags) {
    json["lineposition"] = detail::joinFlaglist(flags, [](auto f){ return to_string(f); });
    return *this;
}
inline Contour::Legendgrouptitle::Font& Contour::Legendgrouptitle::Font::lineposition(LinepositionExtra extra) {
    json["lineposition"] = to_string(extra);
    return *this;
}

inline Contour::Legendgrouptitle::Font& Contour::Legendgrouptitle::Font::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}

inline Contour::Legendgrouptitle::Font& Contour::Legendgrouptitle::Font::size(double f) {
    json["size"] = std::move(f);
    return *this;
}

inline Contour::Legendgrouptitle::Font& Contour::Legendgrouptitle::Font::style(enum Style f) {
    switch(f) {
        case Style::Normal: json["style"] = "normal"; break;
        case Style::Italic: json["style"] = "italic"; break;
    }
    return *this;
}

inline Contour::Legendgrouptitle::Font& Contour::Legendgrouptitle::Font::textcase(enum Textcase f) {
    switch(f) {
        case Textcase::Normal: json["textcase"] = "normal"; break;
        case Textcase::WordCaps: json["textcase"] = "word caps"; break;
        case Textcase::Upper: json["textcase"] = "upper"; break;
        case Textcase::Lower: json["textcase"] = "lower"; break;
    }
    return *this;
}

inline Contour::Legendgrouptitle::Font& Contour::Legendgrouptitle::Font::variant(enum Variant f) {
    switch(f) {
        case Variant::Normal: json["variant"] = "normal"; break;
        case Variant::SmallCaps: json["variant"] = "small-caps"; break;
        case Variant::AllSmallCaps: json["variant"] = "all-small-caps"; break;
        case Variant::AllPetiteCaps: json["variant"] = "all-petite-caps"; break;
        case Variant::PetiteCaps: json["variant"] = "petite-caps"; break;
        case Variant::Unicase: json["variant"] = "unicase"; break;
    }
    return *this;
}

inline Contour::Legendgrouptitle::Font& Contour::Legendgrouptitle::Font::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}


inline Contour::Line& Contour::Line::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Contour::Line& Contour::Line::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

inline Contour::Line& Contour::Line::dash(std::string f) {
    json["dash"] = std::move(f);
    return *this;
}

inline Contour::Line& Contour::Line::smoothing(double f) {
    json["smoothing"] = std::move(f);
    return *this;
}

inline Contour::Line& Contour::Line::width(double f) {
    json["width"] = std::move(f);
    return *this;
}


inline Contour::Stream& Contour::Stream::maxpoints(double f) {
    json["maxpoints"] = std::move(f);
    return *this;
}

inline Contour::Stream& Contour::Stream::token(std::string f) {
    json["token"] = std::move(f);
    return *this;
}

inline std::string Contour::Textfont::to_string(Lineposition e) {
    switch(e) {
        case Lineposition::Under: return "under";
        case Lineposition::Over: return "over";
        case Lineposition::Through: return "through";
    }
    throw std::invalid_argument{"Unknown flag value for lineposition."};
}
inline std::string Contour::Textfont::to_string(LinepositionExtra e) {
    switch(e) {
        case LinepositionExtra::None: return "none";
    }
    throw std::invalid_argument{"Unknown extra value for lineposition."};
}

inline Contour::Textfont& Contour::Textfont::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Contour::Textfont& Contour::Textfont::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

inline Contour::Textfont& Contour::Textfont::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}

inline Contour::Textfont& Contour::Textfont::lineposition(std::initializer_list<Lineposition> flags) {
    json["lineposition"] = detail::joinFlaglist(flags, [](auto f){ return to_string(f); });
    return *this;
}
inline Contour::Textfont& Contour::Textfont::lineposition(LinepositionExtra extra) {
    json["lineposition"] = to_string(extra);
    return *this;
}

inline Contour::Textfont& Contour::Textfont::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}

inline Contour::Textfont& Contour::Textfont::size(double f) {
    json["size"] = std::move(f);
    return *this;
}

inline Contour::Textfont& Contour::Textfont::style(enum Style f) {
    switch(f) {
        case Style::Normal: json["style"] = "normal"; break;
        case Style::Italic: json["style"] = "italic"; break;
    }
    return *this;
}

inline Contour::Textfont& Contour::Textfont::textcase(enum Textcase f) {
    switch(f) {
        case Textcase::Normal: json["textcase"] = "normal"; break;
        case Textcase::WordCaps: json["textcase"] = "word caps"; break;
        case Textcase::Upper: json["textcase"] = "upper"; break;
        case Textcase::Lower: json["textcase"] = "lower"; break;
    }
    return *this;
}

inline Contour::Textfont& Contour::Textfont::variant(enum Variant f) {
    switch(f) {
        case Variant::Normal: json["variant"] = "normal"; break;
        case Variant::SmallCaps: json["variant"] = "small-caps"; break;
        case Variant::AllSmallCaps: json["variant"] = "all-small-caps"; break;
        case Variant::AllPetiteCaps: json["variant"] = "all-petite-caps"; break;
        case Variant::PetiteCaps: json["variant"] = "petite-caps"; break;
        case Variant::Unicase: json["variant"] = "unicase"; break;
    }
    return *this;
}

inline Contour::Textfont& Contour::Textfont::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}

} // namespace plotlypp

