// Copyright (c) 2025 Jimmy O'Rourke
// Licensed under and subject to the terms of the LICENSE file accompanying this distribution.
// Official repository: https://github.com/jimmyorourke/plotlypp

// Autogenerated by plotlypp/generator, from official Plotly sources.
// See https://plotly.com/graphing-libraries.
// Do not edit, changes may be overwritten!

#pragma once

namespace plotlypp {

inline std::string Funnel::to_string(Constraintext e) {
    switch(e) {
        case Constraintext::Inside: return "inside";
        case Constraintext::Outside: return "outside";
        case Constraintext::Both: return "both";
        case Constraintext::None: return "none";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Funnel::to_string(Insidetextanchor e) {
    switch(e) {
        case Insidetextanchor::End: return "end";
        case Insidetextanchor::Middle: return "middle";
        case Insidetextanchor::Start: return "start";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Funnel::to_string(Orientation e) {
    switch(e) {
        case Orientation::V: return "v";
        case Orientation::H: return "h";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Funnel::to_string(Textposition e) {
    switch(e) {
        case Textposition::Inside: return "inside";
        case Textposition::Outside: return "outside";
        case Textposition::Auto: return "auto";
        case Textposition::None: return "none";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Funnel::to_string(Visible e) {
    switch(e) {
        case Visible::True: return "True";
        case Visible::False: return "False";
        case Visible::Legendonly: return "legendonly";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Funnel::to_string(Xperiodalignment e) {
    switch(e) {
        case Xperiodalignment::Start: return "start";
        case Xperiodalignment::Middle: return "middle";
        case Xperiodalignment::End: return "end";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Funnel::to_string(Yperiodalignment e) {
    switch(e) {
        case Yperiodalignment::Start: return "start";
        case Yperiodalignment::Middle: return "middle";
        case Yperiodalignment::End: return "end";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

inline Funnel& Funnel::alignmentgroup(std::string f) {
    json["alignmentgroup"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::cliponaxis(bool f) {
    json["cliponaxis"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::connector(Connector f) {
    json["connector"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Funnel& Funnel::connector(Callable&& c) {
    Connector f{};
    std::forward<Callable>(c)(f);
    return connector(std::move(f));
}

inline Funnel& Funnel::constraintext(enum Constraintext f) {
    json["constraintext"] = to_string(f);
    return *this;
}

template <typename Range, typename>
inline Funnel& Funnel::customdata(Range&& f) {
    json["customdata"] = f;
    return *this;
}

inline Funnel& Funnel::customdatasrc(std::string f) {
    json["customdatasrc"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::dx(double f) {
    json["dx"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::dy(double f) {
    json["dy"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::hoverinfo(std::string f) {
    json["hoverinfo"] = std::move(f);
    return *this;
}
inline Funnel& Funnel::hoverinfo(const std::vector<std::string>& f) {
    json["hoverinfo"] = f;
    return *this;
}

inline Funnel& Funnel::hoverinfosrc(std::string f) {
    json["hoverinfosrc"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::hoverlabel(Hoverlabel f) {
    json["hoverlabel"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Funnel& Funnel::hoverlabel(Callable&& c) {
    Hoverlabel f{};
    std::forward<Callable>(c)(f);
    return hoverlabel(std::move(f));
}

inline Funnel& Funnel::hovertemplate(std::string f) {
    json["hovertemplate"] = std::move(f);
    return *this;
}
inline Funnel& Funnel::hovertemplate(const std::vector<std::string>& f) {
    json["hovertemplate"] = f;
    return *this;
}

inline Funnel& Funnel::hovertemplatesrc(std::string f) {
    json["hovertemplatesrc"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::hovertext(std::string f) {
    json["hovertext"] = std::move(f);
    return *this;
}
inline Funnel& Funnel::hovertext(const std::vector<std::string>& f) {
    json["hovertext"] = f;
    return *this;
}

inline Funnel& Funnel::hovertextsrc(std::string f) {
    json["hovertextsrc"] = std::move(f);
    return *this;
}

template <typename Range, typename>
inline Funnel& Funnel::ids(Range&& f) {
    json["ids"] = f;
    return *this;
}

inline Funnel& Funnel::idssrc(std::string f) {
    json["idssrc"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::insidetextanchor(enum Insidetextanchor f) {
    json["insidetextanchor"] = to_string(f);
    return *this;
}

inline Funnel& Funnel::insidetextfont(Insidetextfont f) {
    json["insidetextfont"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Funnel& Funnel::insidetextfont(Callable&& c) {
    Insidetextfont f{};
    std::forward<Callable>(c)(f);
    return insidetextfont(std::move(f));
}

inline Funnel& Funnel::legend(std::string f) {
    json["legend"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::legendgroup(std::string f) {
    json["legendgroup"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::legendgrouptitle(Legendgrouptitle f) {
    json["legendgrouptitle"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Funnel& Funnel::legendgrouptitle(Callable&& c) {
    Legendgrouptitle f{};
    std::forward<Callable>(c)(f);
    return legendgrouptitle(std::move(f));
}

inline Funnel& Funnel::legendrank(double f) {
    json["legendrank"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::legendwidth(double f) {
    json["legendwidth"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::marker(Marker f) {
    json["marker"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Funnel& Funnel::marker(Callable&& c) {
    Marker f{};
    std::forward<Callable>(c)(f);
    return marker(std::move(f));
}

template <typename T>
inline Funnel& Funnel::meta(T f) {
    json["meta"] = std::move(f);
    return *this;
}
template <typename T>
inline Funnel& Funnel::meta(const std::vector<T>& f) {
    json["meta"] = f;
    return *this;
}

inline Funnel& Funnel::metasrc(std::string f) {
    json["metasrc"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::name(std::string f) {
    json["name"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::offset(double f) {
    json["offset"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::offsetgroup(std::string f) {
    json["offsetgroup"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::opacity(double f) {
    json["opacity"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::orientation(enum Orientation f) {
    json["orientation"] = to_string(f);
    return *this;
}

inline Funnel& Funnel::outsidetextfont(Outsidetextfont f) {
    json["outsidetextfont"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Funnel& Funnel::outsidetextfont(Callable&& c) {
    Outsidetextfont f{};
    std::forward<Callable>(c)(f);
    return outsidetextfont(std::move(f));
}

template <typename T>
inline Funnel& Funnel::selectedpoints(T f) {
    json["selectedpoints"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::showlegend(bool f) {
    json["showlegend"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::stream(Stream f) {
    json["stream"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Funnel& Funnel::stream(Callable&& c) {
    Stream f{};
    std::forward<Callable>(c)(f);
    return stream(std::move(f));
}

inline Funnel& Funnel::text(std::string f) {
    json["text"] = std::move(f);
    return *this;
}
inline Funnel& Funnel::text(const std::vector<std::string>& f) {
    json["text"] = f;
    return *this;
}

inline Funnel& Funnel::textangle(double f) {
    json["textangle"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::textfont(Textfont f) {
    json["textfont"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Funnel& Funnel::textfont(Callable&& c) {
    Textfont f{};
    std::forward<Callable>(c)(f);
    return textfont(std::move(f));
}

inline Funnel& Funnel::textinfo(std::string f) {
    json["textinfo"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::textposition(enum Textposition f) {
    json["textposition"] = to_string(f);
    return *this;
}
inline Funnel& Funnel::textposition(const std::vector<enum Textposition>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["textposition"] = std::move(stringified);
    return *this;
}

inline Funnel& Funnel::textpositionsrc(std::string f) {
    json["textpositionsrc"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::textsrc(std::string f) {
    json["textsrc"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::texttemplate(std::string f) {
    json["texttemplate"] = std::move(f);
    return *this;
}
inline Funnel& Funnel::texttemplate(const std::vector<std::string>& f) {
    json["texttemplate"] = f;
    return *this;
}

inline Funnel& Funnel::texttemplatesrc(std::string f) {
    json["texttemplatesrc"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::uid(std::string f) {
    json["uid"] = std::move(f);
    return *this;
}

template <typename T>
inline Funnel& Funnel::uirevision(T f) {
    json["uirevision"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::visible(enum Visible f) {
    json["visible"] = to_string(f);
    return *this;
}

inline Funnel& Funnel::width(double f) {
    json["width"] = std::move(f);
    return *this;
}

template <typename Range, typename>
inline Funnel& Funnel::x(Range&& f) {
    json["x"] = f;
    return *this;
}

template <typename T>
inline Funnel& Funnel::x0(T f) {
    json["x0"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::xaxis(std::string f) {
    json["xaxis"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::xhoverformat(std::string f) {
    json["xhoverformat"] = std::move(f);
    return *this;
}

template <typename T>
inline Funnel& Funnel::xperiod(T f) {
    json["xperiod"] = std::move(f);
    return *this;
}

template <typename T>
inline Funnel& Funnel::xperiod0(T f) {
    json["xperiod0"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::xperiodalignment(enum Xperiodalignment f) {
    json["xperiodalignment"] = to_string(f);
    return *this;
}

inline Funnel& Funnel::xsrc(std::string f) {
    json["xsrc"] = std::move(f);
    return *this;
}

template <typename Range, typename>
inline Funnel& Funnel::y(Range&& f) {
    json["y"] = f;
    return *this;
}

template <typename T>
inline Funnel& Funnel::y0(T f) {
    json["y0"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::yaxis(std::string f) {
    json["yaxis"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::yhoverformat(std::string f) {
    json["yhoverformat"] = std::move(f);
    return *this;
}

template <typename T>
inline Funnel& Funnel::yperiod(T f) {
    json["yperiod"] = std::move(f);
    return *this;
}

template <typename T>
inline Funnel& Funnel::yperiod0(T f) {
    json["yperiod0"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::yperiodalignment(enum Yperiodalignment f) {
    json["yperiodalignment"] = to_string(f);
    return *this;
}

inline Funnel& Funnel::ysrc(std::string f) {
    json["ysrc"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::zorder(int f) {
    json["zorder"] = std::move(f);
    return *this;
}


inline Funnel::Connector& Funnel::Connector::fillcolor(std::string f) {
    json["fillcolor"] = std::move(f);
    return *this;
}
inline Funnel::Connector& Funnel::Connector::fillcolor(double f) {
    json["fillcolor"] = std::move(f);
    return *this;
}

inline Funnel::Connector& Funnel::Connector::line(Line f) {
    json["line"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Funnel::Connector& Funnel::Connector::line(Callable&& c) {
    Line f{};
    std::forward<Callable>(c)(f);
    return line(std::move(f));
}

inline Funnel::Connector& Funnel::Connector::visible(bool f) {
    json["visible"] = std::move(f);
    return *this;
}


inline Funnel::Connector::Line& Funnel::Connector::Line::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Funnel::Connector::Line& Funnel::Connector::Line::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

inline Funnel::Connector::Line& Funnel::Connector::Line::dash(std::string f) {
    json["dash"] = std::move(f);
    return *this;
}

inline Funnel::Connector::Line& Funnel::Connector::Line::width(double f) {
    json["width"] = std::move(f);
    return *this;
}

inline std::string Funnel::Hoverlabel::to_string(Align e) {
    switch(e) {
        case Align::Left: return "left";
        case Align::Right: return "right";
        case Align::Auto: return "auto";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

inline Funnel::Hoverlabel& Funnel::Hoverlabel::align(enum Align f) {
    json["align"] = to_string(f);
    return *this;
}
inline Funnel::Hoverlabel& Funnel::Hoverlabel::align(const std::vector<enum Align>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["align"] = std::move(stringified);
    return *this;
}

inline Funnel::Hoverlabel& Funnel::Hoverlabel::alignsrc(std::string f) {
    json["alignsrc"] = std::move(f);
    return *this;
}

inline Funnel::Hoverlabel& Funnel::Hoverlabel::bgcolor(std::string f) {
    json["bgcolor"] = std::move(f);
    return *this;
}
inline Funnel::Hoverlabel& Funnel::Hoverlabel::bgcolor(double f) {
    json["bgcolor"] = std::move(f);
    return *this;
}
inline Funnel::Hoverlabel& Funnel::Hoverlabel::bgcolor(const std::vector<std::string>& f) {
    json["bgcolor"] = f;
    return *this;
}
inline Funnel::Hoverlabel& Funnel::Hoverlabel::bgcolor(const std::vector<double>& f) {
    json["bgcolor"] = f;
    return *this;
}

inline Funnel::Hoverlabel& Funnel::Hoverlabel::bgcolorsrc(std::string f) {
    json["bgcolorsrc"] = std::move(f);
    return *this;
}

inline Funnel::Hoverlabel& Funnel::Hoverlabel::bordercolor(std::string f) {
    json["bordercolor"] = std::move(f);
    return *this;
}
inline Funnel::Hoverlabel& Funnel::Hoverlabel::bordercolor(double f) {
    json["bordercolor"] = std::move(f);
    return *this;
}
inline Funnel::Hoverlabel& Funnel::Hoverlabel::bordercolor(const std::vector<std::string>& f) {
    json["bordercolor"] = f;
    return *this;
}
inline Funnel::Hoverlabel& Funnel::Hoverlabel::bordercolor(const std::vector<double>& f) {
    json["bordercolor"] = f;
    return *this;
}

inline Funnel::Hoverlabel& Funnel::Hoverlabel::bordercolorsrc(std::string f) {
    json["bordercolorsrc"] = std::move(f);
    return *this;
}

inline Funnel::Hoverlabel& Funnel::Hoverlabel::font(Font f) {
    json["font"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Funnel::Hoverlabel& Funnel::Hoverlabel::font(Callable&& c) {
    Font f{};
    std::forward<Callable>(c)(f);
    return font(std::move(f));
}

inline Funnel::Hoverlabel& Funnel::Hoverlabel::namelength(int f) {
    json["namelength"] = std::move(f);
    return *this;
}
inline Funnel::Hoverlabel& Funnel::Hoverlabel::namelength(const std::vector<int>& f) {
    json["namelength"] = f;
    return *this;
}

inline Funnel::Hoverlabel& Funnel::Hoverlabel::namelengthsrc(std::string f) {
    json["namelengthsrc"] = std::move(f);
    return *this;
}

inline std::string Funnel::Hoverlabel::Font::to_string(Style e) {
    switch(e) {
        case Style::Normal: return "normal";
        case Style::Italic: return "italic";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Funnel::Hoverlabel::Font::to_string(Textcase e) {
    switch(e) {
        case Textcase::Normal: return "normal";
        case Textcase::WordCaps: return "word caps";
        case Textcase::Upper: return "upper";
        case Textcase::Lower: return "lower";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Funnel::Hoverlabel::Font::to_string(Variant e) {
    switch(e) {
        case Variant::Normal: return "normal";
        case Variant::SmallCaps: return "small-caps";
        case Variant::AllSmallCaps: return "all-small-caps";
        case Variant::AllPetiteCaps: return "all-petite-caps";
        case Variant::PetiteCaps: return "petite-caps";
        case Variant::Unicase: return "unicase";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::color(double f) {
    json["color"] = std::move(f);
    return *this;
}
inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::color(const std::vector<std::string>& f) {
    json["color"] = f;
    return *this;
}
inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::color(const std::vector<double>& f) {
    json["color"] = f;
    return *this;
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::colorsrc(std::string f) {
    json["colorsrc"] = std::move(f);
    return *this;
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}
inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::family(const std::vector<std::string>& f) {
    json["family"] = f;
    return *this;
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::familysrc(std::string f) {
    json["familysrc"] = std::move(f);
    return *this;
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::lineposition(std::string f) {
    json["lineposition"] = std::move(f);
    return *this;
}
inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::lineposition(const std::vector<std::string>& f) {
    json["lineposition"] = f;
    return *this;
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::linepositionsrc(std::string f) {
    json["linepositionsrc"] = std::move(f);
    return *this;
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}
inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::shadow(const std::vector<std::string>& f) {
    json["shadow"] = f;
    return *this;
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::shadowsrc(std::string f) {
    json["shadowsrc"] = std::move(f);
    return *this;
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::size(double f) {
    json["size"] = std::move(f);
    return *this;
}
inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::size(const std::vector<double>& f) {
    json["size"] = f;
    return *this;
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::sizesrc(std::string f) {
    json["sizesrc"] = std::move(f);
    return *this;
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::style(enum Style f) {
    json["style"] = to_string(f);
    return *this;
}
inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::style(const std::vector<enum Style>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["style"] = std::move(stringified);
    return *this;
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::stylesrc(std::string f) {
    json["stylesrc"] = std::move(f);
    return *this;
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::textcase(enum Textcase f) {
    json["textcase"] = to_string(f);
    return *this;
}
inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::textcase(const std::vector<enum Textcase>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["textcase"] = std::move(stringified);
    return *this;
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::textcasesrc(std::string f) {
    json["textcasesrc"] = std::move(f);
    return *this;
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::variant(enum Variant f) {
    json["variant"] = to_string(f);
    return *this;
}
inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::variant(const std::vector<enum Variant>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["variant"] = std::move(stringified);
    return *this;
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::variantsrc(std::string f) {
    json["variantsrc"] = std::move(f);
    return *this;
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}
inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::weight(const std::vector<int>& f) {
    json["weight"] = f;
    return *this;
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::weightsrc(std::string f) {
    json["weightsrc"] = std::move(f);
    return *this;
}

inline std::string Funnel::Insidetextfont::to_string(Style e) {
    switch(e) {
        case Style::Normal: return "normal";
        case Style::Italic: return "italic";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Funnel::Insidetextfont::to_string(Textcase e) {
    switch(e) {
        case Textcase::Normal: return "normal";
        case Textcase::WordCaps: return "word caps";
        case Textcase::Upper: return "upper";
        case Textcase::Lower: return "lower";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Funnel::Insidetextfont::to_string(Variant e) {
    switch(e) {
        case Variant::Normal: return "normal";
        case Variant::SmallCaps: return "small-caps";
        case Variant::AllSmallCaps: return "all-small-caps";
        case Variant::AllPetiteCaps: return "all-petite-caps";
        case Variant::PetiteCaps: return "petite-caps";
        case Variant::Unicase: return "unicase";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Funnel::Insidetextfont& Funnel::Insidetextfont::color(double f) {
    json["color"] = std::move(f);
    return *this;
}
inline Funnel::Insidetextfont& Funnel::Insidetextfont::color(const std::vector<std::string>& f) {
    json["color"] = f;
    return *this;
}
inline Funnel::Insidetextfont& Funnel::Insidetextfont::color(const std::vector<double>& f) {
    json["color"] = f;
    return *this;
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::colorsrc(std::string f) {
    json["colorsrc"] = std::move(f);
    return *this;
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}
inline Funnel::Insidetextfont& Funnel::Insidetextfont::family(const std::vector<std::string>& f) {
    json["family"] = f;
    return *this;
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::familysrc(std::string f) {
    json["familysrc"] = std::move(f);
    return *this;
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::lineposition(std::string f) {
    json["lineposition"] = std::move(f);
    return *this;
}
inline Funnel::Insidetextfont& Funnel::Insidetextfont::lineposition(const std::vector<std::string>& f) {
    json["lineposition"] = f;
    return *this;
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::linepositionsrc(std::string f) {
    json["linepositionsrc"] = std::move(f);
    return *this;
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}
inline Funnel::Insidetextfont& Funnel::Insidetextfont::shadow(const std::vector<std::string>& f) {
    json["shadow"] = f;
    return *this;
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::shadowsrc(std::string f) {
    json["shadowsrc"] = std::move(f);
    return *this;
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::size(double f) {
    json["size"] = std::move(f);
    return *this;
}
inline Funnel::Insidetextfont& Funnel::Insidetextfont::size(const std::vector<double>& f) {
    json["size"] = f;
    return *this;
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::sizesrc(std::string f) {
    json["sizesrc"] = std::move(f);
    return *this;
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::style(enum Style f) {
    json["style"] = to_string(f);
    return *this;
}
inline Funnel::Insidetextfont& Funnel::Insidetextfont::style(const std::vector<enum Style>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["style"] = std::move(stringified);
    return *this;
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::stylesrc(std::string f) {
    json["stylesrc"] = std::move(f);
    return *this;
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::textcase(enum Textcase f) {
    json["textcase"] = to_string(f);
    return *this;
}
inline Funnel::Insidetextfont& Funnel::Insidetextfont::textcase(const std::vector<enum Textcase>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["textcase"] = std::move(stringified);
    return *this;
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::textcasesrc(std::string f) {
    json["textcasesrc"] = std::move(f);
    return *this;
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::variant(enum Variant f) {
    json["variant"] = to_string(f);
    return *this;
}
inline Funnel::Insidetextfont& Funnel::Insidetextfont::variant(const std::vector<enum Variant>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["variant"] = std::move(stringified);
    return *this;
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::variantsrc(std::string f) {
    json["variantsrc"] = std::move(f);
    return *this;
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}
inline Funnel::Insidetextfont& Funnel::Insidetextfont::weight(const std::vector<int>& f) {
    json["weight"] = f;
    return *this;
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::weightsrc(std::string f) {
    json["weightsrc"] = std::move(f);
    return *this;
}


inline Funnel::Legendgrouptitle& Funnel::Legendgrouptitle::font(Font f) {
    json["font"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Funnel::Legendgrouptitle& Funnel::Legendgrouptitle::font(Callable&& c) {
    Font f{};
    std::forward<Callable>(c)(f);
    return font(std::move(f));
}

inline Funnel::Legendgrouptitle& Funnel::Legendgrouptitle::text(std::string f) {
    json["text"] = std::move(f);
    return *this;
}

inline std::string Funnel::Legendgrouptitle::Font::to_string(Style e) {
    switch(e) {
        case Style::Normal: return "normal";
        case Style::Italic: return "italic";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Funnel::Legendgrouptitle::Font::to_string(Textcase e) {
    switch(e) {
        case Textcase::Normal: return "normal";
        case Textcase::WordCaps: return "word caps";
        case Textcase::Upper: return "upper";
        case Textcase::Lower: return "lower";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Funnel::Legendgrouptitle::Font::to_string(Variant e) {
    switch(e) {
        case Variant::Normal: return "normal";
        case Variant::SmallCaps: return "small-caps";
        case Variant::AllSmallCaps: return "all-small-caps";
        case Variant::AllPetiteCaps: return "all-petite-caps";
        case Variant::PetiteCaps: return "petite-caps";
        case Variant::Unicase: return "unicase";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

inline Funnel::Legendgrouptitle::Font& Funnel::Legendgrouptitle::Font::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Funnel::Legendgrouptitle::Font& Funnel::Legendgrouptitle::Font::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

inline Funnel::Legendgrouptitle::Font& Funnel::Legendgrouptitle::Font::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}

inline Funnel::Legendgrouptitle::Font& Funnel::Legendgrouptitle::Font::lineposition(std::string f) {
    json["lineposition"] = std::move(f);
    return *this;
}

inline Funnel::Legendgrouptitle::Font& Funnel::Legendgrouptitle::Font::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}

inline Funnel::Legendgrouptitle::Font& Funnel::Legendgrouptitle::Font::size(double f) {
    json["size"] = std::move(f);
    return *this;
}

inline Funnel::Legendgrouptitle::Font& Funnel::Legendgrouptitle::Font::style(enum Style f) {
    json["style"] = to_string(f);
    return *this;
}

inline Funnel::Legendgrouptitle::Font& Funnel::Legendgrouptitle::Font::textcase(enum Textcase f) {
    json["textcase"] = to_string(f);
    return *this;
}

inline Funnel::Legendgrouptitle::Font& Funnel::Legendgrouptitle::Font::variant(enum Variant f) {
    json["variant"] = to_string(f);
    return *this;
}

inline Funnel::Legendgrouptitle::Font& Funnel::Legendgrouptitle::Font::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}


inline Funnel::Marker& Funnel::Marker::autocolorscale(bool f) {
    json["autocolorscale"] = std::move(f);
    return *this;
}

inline Funnel::Marker& Funnel::Marker::cauto(bool f) {
    json["cauto"] = std::move(f);
    return *this;
}

inline Funnel::Marker& Funnel::Marker::cmax(double f) {
    json["cmax"] = std::move(f);
    return *this;
}

inline Funnel::Marker& Funnel::Marker::cmid(double f) {
    json["cmid"] = std::move(f);
    return *this;
}

inline Funnel::Marker& Funnel::Marker::cmin(double f) {
    json["cmin"] = std::move(f);
    return *this;
}

inline Funnel::Marker& Funnel::Marker::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Funnel::Marker& Funnel::Marker::color(double f) {
    json["color"] = std::move(f);
    return *this;
}
inline Funnel::Marker& Funnel::Marker::color(const std::vector<std::string>& f) {
    json["color"] = f;
    return *this;
}
inline Funnel::Marker& Funnel::Marker::color(const std::vector<double>& f) {
    json["color"] = f;
    return *this;
}

inline Funnel::Marker& Funnel::Marker::coloraxis(std::string f) {
    json["coloraxis"] = std::move(f);
    return *this;
}

inline Funnel::Marker& Funnel::Marker::colorbar(Colorbar f) {
    json["colorbar"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Funnel::Marker& Funnel::Marker::colorbar(Callable&& c) {
    Colorbar f{};
    std::forward<Callable>(c)(f);
    return colorbar(std::move(f));
}

inline Funnel::Marker& Funnel::Marker::colorscale(std::string f) {
    json["colorscale"] = std::move(f);
    return *this;
}
inline Funnel::Marker& Funnel::Marker::colorscale(const std::vector<std::pair<double, std::string>>& f) {
    json["colorscale"] = f;
    return *this;
}

inline Funnel::Marker& Funnel::Marker::colorsrc(std::string f) {
    json["colorsrc"] = std::move(f);
    return *this;
}

inline Funnel::Marker& Funnel::Marker::line(Line f) {
    json["line"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Funnel::Marker& Funnel::Marker::line(Callable&& c) {
    Line f{};
    std::forward<Callable>(c)(f);
    return line(std::move(f));
}

inline Funnel::Marker& Funnel::Marker::opacity(double f) {
    json["opacity"] = std::move(f);
    return *this;
}
inline Funnel::Marker& Funnel::Marker::opacity(const std::vector<double>& f) {
    json["opacity"] = f;
    return *this;
}

inline Funnel::Marker& Funnel::Marker::opacitysrc(std::string f) {
    json["opacitysrc"] = std::move(f);
    return *this;
}

inline Funnel::Marker& Funnel::Marker::reversescale(bool f) {
    json["reversescale"] = std::move(f);
    return *this;
}

inline Funnel::Marker& Funnel::Marker::showscale(bool f) {
    json["showscale"] = std::move(f);
    return *this;
}

inline std::string Funnel::Marker::Colorbar::to_string(Exponentformat e) {
    switch(e) {
        case Exponentformat::None: return "none";
        case Exponentformat::E: return "E";
        case Exponentformat::Power: return "power";
        case Exponentformat::Si: return "SI";
        case Exponentformat::B: return "B";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Funnel::Marker::Colorbar::to_string(Lenmode e) {
    switch(e) {
        case Lenmode::Fraction: return "fraction";
        case Lenmode::Pixels: return "pixels";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Funnel::Marker::Colorbar::to_string(Orientation e) {
    switch(e) {
        case Orientation::H: return "h";
        case Orientation::V: return "v";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Funnel::Marker::Colorbar::to_string(Showexponent e) {
    switch(e) {
        case Showexponent::All: return "all";
        case Showexponent::First: return "first";
        case Showexponent::Last: return "last";
        case Showexponent::None: return "none";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Funnel::Marker::Colorbar::to_string(Showtickprefix e) {
    switch(e) {
        case Showtickprefix::All: return "all";
        case Showtickprefix::First: return "first";
        case Showtickprefix::Last: return "last";
        case Showtickprefix::None: return "none";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Funnel::Marker::Colorbar::to_string(Showticksuffix e) {
    switch(e) {
        case Showticksuffix::All: return "all";
        case Showticksuffix::First: return "first";
        case Showticksuffix::Last: return "last";
        case Showticksuffix::None: return "none";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Funnel::Marker::Colorbar::to_string(Thicknessmode e) {
    switch(e) {
        case Thicknessmode::Fraction: return "fraction";
        case Thicknessmode::Pixels: return "pixels";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Funnel::Marker::Colorbar::to_string(Ticklabeloverflow e) {
    switch(e) {
        case Ticklabeloverflow::Allow: return "allow";
        case Ticklabeloverflow::HidePastDiv: return "hide past div";
        case Ticklabeloverflow::HidePastDomain: return "hide past domain";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Funnel::Marker::Colorbar::to_string(Ticklabelposition e) {
    switch(e) {
        case Ticklabelposition::Outside: return "outside";
        case Ticklabelposition::Inside: return "inside";
        case Ticklabelposition::OutsideTop: return "outside top";
        case Ticklabelposition::InsideTop: return "inside top";
        case Ticklabelposition::OutsideLeft: return "outside left";
        case Ticklabelposition::InsideLeft: return "inside left";
        case Ticklabelposition::OutsideRight: return "outside right";
        case Ticklabelposition::InsideRight: return "inside right";
        case Ticklabelposition::OutsideBottom: return "outside bottom";
        case Ticklabelposition::InsideBottom: return "inside bottom";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Funnel::Marker::Colorbar::to_string(Tickmode e) {
    switch(e) {
        case Tickmode::Auto: return "auto";
        case Tickmode::Linear: return "linear";
        case Tickmode::Array: return "array";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Funnel::Marker::Colorbar::to_string(Ticks e) {
    switch(e) {
        case Ticks::Outside: return "outside";
        case Ticks::Inside: return "inside";
        case Ticks::Empty: return "";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Funnel::Marker::Colorbar::to_string(Xanchor e) {
    switch(e) {
        case Xanchor::Left: return "left";
        case Xanchor::Center: return "center";
        case Xanchor::Right: return "right";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Funnel::Marker::Colorbar::to_string(Xref e) {
    switch(e) {
        case Xref::Container: return "container";
        case Xref::Paper: return "paper";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Funnel::Marker::Colorbar::to_string(Yanchor e) {
    switch(e) {
        case Yanchor::Top: return "top";
        case Yanchor::Middle: return "middle";
        case Yanchor::Bottom: return "bottom";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Funnel::Marker::Colorbar::to_string(Yref e) {
    switch(e) {
        case Yref::Container: return "container";
        case Yref::Paper: return "paper";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::bgcolor(std::string f) {
    json["bgcolor"] = std::move(f);
    return *this;
}
inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::bgcolor(double f) {
    json["bgcolor"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::bordercolor(std::string f) {
    json["bordercolor"] = std::move(f);
    return *this;
}
inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::bordercolor(double f) {
    json["bordercolor"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::borderwidth(double f) {
    json["borderwidth"] = std::move(f);
    return *this;
}

template <typename T>
inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::dtick(T f) {
    json["dtick"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::exponentformat(enum Exponentformat f) {
    json["exponentformat"] = to_string(f);
    return *this;
}

template <typename T>
inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::labelalias(T f) {
    json["labelalias"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::len(double f) {
    json["len"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::lenmode(enum Lenmode f) {
    json["lenmode"] = to_string(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::minexponent(double f) {
    json["minexponent"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::nticks(int f) {
    json["nticks"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::orientation(enum Orientation f) {
    json["orientation"] = to_string(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::outlinecolor(std::string f) {
    json["outlinecolor"] = std::move(f);
    return *this;
}
inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::outlinecolor(double f) {
    json["outlinecolor"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::outlinewidth(double f) {
    json["outlinewidth"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::separatethousands(bool f) {
    json["separatethousands"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::showexponent(enum Showexponent f) {
    json["showexponent"] = to_string(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::showticklabels(bool f) {
    json["showticklabels"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::showtickprefix(enum Showtickprefix f) {
    json["showtickprefix"] = to_string(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::showticksuffix(enum Showticksuffix f) {
    json["showticksuffix"] = to_string(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::thickness(double f) {
    json["thickness"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::thicknessmode(enum Thicknessmode f) {
    json["thicknessmode"] = to_string(f);
    return *this;
}

template <typename T>
inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::tick0(T f) {
    json["tick0"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::tickangle(double f) {
    json["tickangle"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::tickcolor(std::string f) {
    json["tickcolor"] = std::move(f);
    return *this;
}
inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::tickcolor(double f) {
    json["tickcolor"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::tickfont(Tickfont f) {
    json["tickfont"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::tickfont(Callable&& c) {
    Tickfont f{};
    std::forward<Callable>(c)(f);
    return tickfont(std::move(f));
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::tickformat(std::string f) {
    json["tickformat"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::tickformatstops(const std::vector<Tickformatstop>& f) {
    std::vector<Json> jsonified(f.size());
    std::transform(f.begin(), f.end(), jsonified.begin(), [](auto& e){ return e.json; });
    json["tickformatstops"] = std::move(jsonified);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::ticklabeloverflow(enum Ticklabeloverflow f) {
    json["ticklabeloverflow"] = to_string(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::ticklabelposition(enum Ticklabelposition f) {
    json["ticklabelposition"] = to_string(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::ticklabelstep(int f) {
    json["ticklabelstep"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::ticklen(double f) {
    json["ticklen"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::tickmode(enum Tickmode f) {
    json["tickmode"] = to_string(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::tickprefix(std::string f) {
    json["tickprefix"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::ticks(enum Ticks f) {
    json["ticks"] = to_string(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::ticksuffix(std::string f) {
    json["ticksuffix"] = std::move(f);
    return *this;
}

template <typename Range, typename>
inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::ticktext(Range&& f) {
    json["ticktext"] = f;
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::ticktextsrc(std::string f) {
    json["ticktextsrc"] = std::move(f);
    return *this;
}

template <typename Range, typename>
inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::tickvals(Range&& f) {
    json["tickvals"] = f;
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::tickvalssrc(std::string f) {
    json["tickvalssrc"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::tickwidth(double f) {
    json["tickwidth"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::title(Title f) {
    json["title"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::title(Callable&& c) {
    Title f{};
    std::forward<Callable>(c)(f);
    return title(std::move(f));
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::x(double f) {
    json["x"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::xanchor(enum Xanchor f) {
    json["xanchor"] = to_string(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::xpad(double f) {
    json["xpad"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::xref(enum Xref f) {
    json["xref"] = to_string(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::y(double f) {
    json["y"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::yanchor(enum Yanchor f) {
    json["yanchor"] = to_string(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::ypad(double f) {
    json["ypad"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::yref(enum Yref f) {
    json["yref"] = to_string(f);
    return *this;
}

inline std::string Funnel::Marker::Colorbar::Tickfont::to_string(Style e) {
    switch(e) {
        case Style::Normal: return "normal";
        case Style::Italic: return "italic";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Funnel::Marker::Colorbar::Tickfont::to_string(Textcase e) {
    switch(e) {
        case Textcase::Normal: return "normal";
        case Textcase::WordCaps: return "word caps";
        case Textcase::Upper: return "upper";
        case Textcase::Lower: return "lower";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Funnel::Marker::Colorbar::Tickfont::to_string(Variant e) {
    switch(e) {
        case Variant::Normal: return "normal";
        case Variant::SmallCaps: return "small-caps";
        case Variant::AllSmallCaps: return "all-small-caps";
        case Variant::AllPetiteCaps: return "all-petite-caps";
        case Variant::PetiteCaps: return "petite-caps";
        case Variant::Unicase: return "unicase";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

inline Funnel::Marker::Colorbar::Tickfont& Funnel::Marker::Colorbar::Tickfont::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Funnel::Marker::Colorbar::Tickfont& Funnel::Marker::Colorbar::Tickfont::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar::Tickfont& Funnel::Marker::Colorbar::Tickfont::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar::Tickfont& Funnel::Marker::Colorbar::Tickfont::lineposition(std::string f) {
    json["lineposition"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar::Tickfont& Funnel::Marker::Colorbar::Tickfont::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar::Tickfont& Funnel::Marker::Colorbar::Tickfont::size(double f) {
    json["size"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar::Tickfont& Funnel::Marker::Colorbar::Tickfont::style(enum Style f) {
    json["style"] = to_string(f);
    return *this;
}

inline Funnel::Marker::Colorbar::Tickfont& Funnel::Marker::Colorbar::Tickfont::textcase(enum Textcase f) {
    json["textcase"] = to_string(f);
    return *this;
}

inline Funnel::Marker::Colorbar::Tickfont& Funnel::Marker::Colorbar::Tickfont::variant(enum Variant f) {
    json["variant"] = to_string(f);
    return *this;
}

inline Funnel::Marker::Colorbar::Tickfont& Funnel::Marker::Colorbar::Tickfont::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}


inline Funnel::Marker::Colorbar::Tickformatstop& Funnel::Marker::Colorbar::Tickformatstop::dtickrange(const std::vector<double>& f) {
    json["dtickrange"] = f;
    return *this;
}
inline Funnel::Marker::Colorbar::Tickformatstop& Funnel::Marker::Colorbar::Tickformatstop::dtickrange(const std::vector<std::string>& f) {
    json["dtickrange"] = f;
    return *this;
}
inline Funnel::Marker::Colorbar::Tickformatstop& Funnel::Marker::Colorbar::Tickformatstop::dtickrange(const std::vector<std::vector<std::string>>& f) {
    json["dtickrange"] = f;
    return *this;
}
inline Funnel::Marker::Colorbar::Tickformatstop& Funnel::Marker::Colorbar::Tickformatstop::dtickrange(const std::vector<std::vector<double>>& f) {
    json["dtickrange"] = f;
    return *this;
}

inline Funnel::Marker::Colorbar::Tickformatstop& Funnel::Marker::Colorbar::Tickformatstop::enabled(bool f) {
    json["enabled"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar::Tickformatstop& Funnel::Marker::Colorbar::Tickformatstop::name(std::string f) {
    json["name"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar::Tickformatstop& Funnel::Marker::Colorbar::Tickformatstop::templateitemname(std::string f) {
    json["templateitemname"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar::Tickformatstop& Funnel::Marker::Colorbar::Tickformatstop::value(std::string f) {
    json["value"] = std::move(f);
    return *this;
}

inline std::string Funnel::Marker::Colorbar::Title::to_string(Side e) {
    switch(e) {
        case Side::Right: return "right";
        case Side::Top: return "top";
        case Side::Bottom: return "bottom";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

inline Funnel::Marker::Colorbar::Title& Funnel::Marker::Colorbar::Title::font(Font f) {
    json["font"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Funnel::Marker::Colorbar::Title& Funnel::Marker::Colorbar::Title::font(Callable&& c) {
    Font f{};
    std::forward<Callable>(c)(f);
    return font(std::move(f));
}

inline Funnel::Marker::Colorbar::Title& Funnel::Marker::Colorbar::Title::side(enum Side f) {
    json["side"] = to_string(f);
    return *this;
}

inline Funnel::Marker::Colorbar::Title& Funnel::Marker::Colorbar::Title::text(std::string f) {
    json["text"] = std::move(f);
    return *this;
}

inline std::string Funnel::Marker::Colorbar::Title::Font::to_string(Style e) {
    switch(e) {
        case Style::Normal: return "normal";
        case Style::Italic: return "italic";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Funnel::Marker::Colorbar::Title::Font::to_string(Textcase e) {
    switch(e) {
        case Textcase::Normal: return "normal";
        case Textcase::WordCaps: return "word caps";
        case Textcase::Upper: return "upper";
        case Textcase::Lower: return "lower";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Funnel::Marker::Colorbar::Title::Font::to_string(Variant e) {
    switch(e) {
        case Variant::Normal: return "normal";
        case Variant::SmallCaps: return "small-caps";
        case Variant::AllSmallCaps: return "all-small-caps";
        case Variant::AllPetiteCaps: return "all-petite-caps";
        case Variant::PetiteCaps: return "petite-caps";
        case Variant::Unicase: return "unicase";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

inline Funnel::Marker::Colorbar::Title::Font& Funnel::Marker::Colorbar::Title::Font::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Funnel::Marker::Colorbar::Title::Font& Funnel::Marker::Colorbar::Title::Font::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar::Title::Font& Funnel::Marker::Colorbar::Title::Font::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar::Title::Font& Funnel::Marker::Colorbar::Title::Font::lineposition(std::string f) {
    json["lineposition"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar::Title::Font& Funnel::Marker::Colorbar::Title::Font::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar::Title::Font& Funnel::Marker::Colorbar::Title::Font::size(double f) {
    json["size"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar::Title::Font& Funnel::Marker::Colorbar::Title::Font::style(enum Style f) {
    json["style"] = to_string(f);
    return *this;
}

inline Funnel::Marker::Colorbar::Title::Font& Funnel::Marker::Colorbar::Title::Font::textcase(enum Textcase f) {
    json["textcase"] = to_string(f);
    return *this;
}

inline Funnel::Marker::Colorbar::Title::Font& Funnel::Marker::Colorbar::Title::Font::variant(enum Variant f) {
    json["variant"] = to_string(f);
    return *this;
}

inline Funnel::Marker::Colorbar::Title::Font& Funnel::Marker::Colorbar::Title::Font::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}


inline Funnel::Marker::Line& Funnel::Marker::Line::autocolorscale(bool f) {
    json["autocolorscale"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Line& Funnel::Marker::Line::cauto(bool f) {
    json["cauto"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Line& Funnel::Marker::Line::cmax(double f) {
    json["cmax"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Line& Funnel::Marker::Line::cmid(double f) {
    json["cmid"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Line& Funnel::Marker::Line::cmin(double f) {
    json["cmin"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Line& Funnel::Marker::Line::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Funnel::Marker::Line& Funnel::Marker::Line::color(double f) {
    json["color"] = std::move(f);
    return *this;
}
inline Funnel::Marker::Line& Funnel::Marker::Line::color(const std::vector<std::string>& f) {
    json["color"] = f;
    return *this;
}
inline Funnel::Marker::Line& Funnel::Marker::Line::color(const std::vector<double>& f) {
    json["color"] = f;
    return *this;
}

inline Funnel::Marker::Line& Funnel::Marker::Line::coloraxis(std::string f) {
    json["coloraxis"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Line& Funnel::Marker::Line::colorscale(std::string f) {
    json["colorscale"] = std::move(f);
    return *this;
}
inline Funnel::Marker::Line& Funnel::Marker::Line::colorscale(const std::vector<std::pair<double, std::string>>& f) {
    json["colorscale"] = f;
    return *this;
}

inline Funnel::Marker::Line& Funnel::Marker::Line::colorsrc(std::string f) {
    json["colorsrc"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Line& Funnel::Marker::Line::reversescale(bool f) {
    json["reversescale"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Line& Funnel::Marker::Line::width(double f) {
    json["width"] = std::move(f);
    return *this;
}
inline Funnel::Marker::Line& Funnel::Marker::Line::width(const std::vector<double>& f) {
    json["width"] = f;
    return *this;
}

inline Funnel::Marker::Line& Funnel::Marker::Line::widthsrc(std::string f) {
    json["widthsrc"] = std::move(f);
    return *this;
}

inline std::string Funnel::Outsidetextfont::to_string(Style e) {
    switch(e) {
        case Style::Normal: return "normal";
        case Style::Italic: return "italic";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Funnel::Outsidetextfont::to_string(Textcase e) {
    switch(e) {
        case Textcase::Normal: return "normal";
        case Textcase::WordCaps: return "word caps";
        case Textcase::Upper: return "upper";
        case Textcase::Lower: return "lower";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Funnel::Outsidetextfont::to_string(Variant e) {
    switch(e) {
        case Variant::Normal: return "normal";
        case Variant::SmallCaps: return "small-caps";
        case Variant::AllSmallCaps: return "all-small-caps";
        case Variant::AllPetiteCaps: return "all-petite-caps";
        case Variant::PetiteCaps: return "petite-caps";
        case Variant::Unicase: return "unicase";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::color(double f) {
    json["color"] = std::move(f);
    return *this;
}
inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::color(const std::vector<std::string>& f) {
    json["color"] = f;
    return *this;
}
inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::color(const std::vector<double>& f) {
    json["color"] = f;
    return *this;
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::colorsrc(std::string f) {
    json["colorsrc"] = std::move(f);
    return *this;
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}
inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::family(const std::vector<std::string>& f) {
    json["family"] = f;
    return *this;
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::familysrc(std::string f) {
    json["familysrc"] = std::move(f);
    return *this;
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::lineposition(std::string f) {
    json["lineposition"] = std::move(f);
    return *this;
}
inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::lineposition(const std::vector<std::string>& f) {
    json["lineposition"] = f;
    return *this;
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::linepositionsrc(std::string f) {
    json["linepositionsrc"] = std::move(f);
    return *this;
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}
inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::shadow(const std::vector<std::string>& f) {
    json["shadow"] = f;
    return *this;
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::shadowsrc(std::string f) {
    json["shadowsrc"] = std::move(f);
    return *this;
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::size(double f) {
    json["size"] = std::move(f);
    return *this;
}
inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::size(const std::vector<double>& f) {
    json["size"] = f;
    return *this;
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::sizesrc(std::string f) {
    json["sizesrc"] = std::move(f);
    return *this;
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::style(enum Style f) {
    json["style"] = to_string(f);
    return *this;
}
inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::style(const std::vector<enum Style>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["style"] = std::move(stringified);
    return *this;
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::stylesrc(std::string f) {
    json["stylesrc"] = std::move(f);
    return *this;
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::textcase(enum Textcase f) {
    json["textcase"] = to_string(f);
    return *this;
}
inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::textcase(const std::vector<enum Textcase>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["textcase"] = std::move(stringified);
    return *this;
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::textcasesrc(std::string f) {
    json["textcasesrc"] = std::move(f);
    return *this;
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::variant(enum Variant f) {
    json["variant"] = to_string(f);
    return *this;
}
inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::variant(const std::vector<enum Variant>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["variant"] = std::move(stringified);
    return *this;
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::variantsrc(std::string f) {
    json["variantsrc"] = std::move(f);
    return *this;
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}
inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::weight(const std::vector<int>& f) {
    json["weight"] = f;
    return *this;
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::weightsrc(std::string f) {
    json["weightsrc"] = std::move(f);
    return *this;
}


inline Funnel::Stream& Funnel::Stream::maxpoints(double f) {
    json["maxpoints"] = std::move(f);
    return *this;
}

inline Funnel::Stream& Funnel::Stream::token(std::string f) {
    json["token"] = std::move(f);
    return *this;
}

inline std::string Funnel::Textfont::to_string(Style e) {
    switch(e) {
        case Style::Normal: return "normal";
        case Style::Italic: return "italic";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Funnel::Textfont::to_string(Textcase e) {
    switch(e) {
        case Textcase::Normal: return "normal";
        case Textcase::WordCaps: return "word caps";
        case Textcase::Upper: return "upper";
        case Textcase::Lower: return "lower";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Funnel::Textfont::to_string(Variant e) {
    switch(e) {
        case Variant::Normal: return "normal";
        case Variant::SmallCaps: return "small-caps";
        case Variant::AllSmallCaps: return "all-small-caps";
        case Variant::AllPetiteCaps: return "all-petite-caps";
        case Variant::PetiteCaps: return "petite-caps";
        case Variant::Unicase: return "unicase";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

inline Funnel::Textfont& Funnel::Textfont::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Funnel::Textfont& Funnel::Textfont::color(double f) {
    json["color"] = std::move(f);
    return *this;
}
inline Funnel::Textfont& Funnel::Textfont::color(const std::vector<std::string>& f) {
    json["color"] = f;
    return *this;
}
inline Funnel::Textfont& Funnel::Textfont::color(const std::vector<double>& f) {
    json["color"] = f;
    return *this;
}

inline Funnel::Textfont& Funnel::Textfont::colorsrc(std::string f) {
    json["colorsrc"] = std::move(f);
    return *this;
}

inline Funnel::Textfont& Funnel::Textfont::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}
inline Funnel::Textfont& Funnel::Textfont::family(const std::vector<std::string>& f) {
    json["family"] = f;
    return *this;
}

inline Funnel::Textfont& Funnel::Textfont::familysrc(std::string f) {
    json["familysrc"] = std::move(f);
    return *this;
}

inline Funnel::Textfont& Funnel::Textfont::lineposition(std::string f) {
    json["lineposition"] = std::move(f);
    return *this;
}
inline Funnel::Textfont& Funnel::Textfont::lineposition(const std::vector<std::string>& f) {
    json["lineposition"] = f;
    return *this;
}

inline Funnel::Textfont& Funnel::Textfont::linepositionsrc(std::string f) {
    json["linepositionsrc"] = std::move(f);
    return *this;
}

inline Funnel::Textfont& Funnel::Textfont::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}
inline Funnel::Textfont& Funnel::Textfont::shadow(const std::vector<std::string>& f) {
    json["shadow"] = f;
    return *this;
}

inline Funnel::Textfont& Funnel::Textfont::shadowsrc(std::string f) {
    json["shadowsrc"] = std::move(f);
    return *this;
}

inline Funnel::Textfont& Funnel::Textfont::size(double f) {
    json["size"] = std::move(f);
    return *this;
}
inline Funnel::Textfont& Funnel::Textfont::size(const std::vector<double>& f) {
    json["size"] = f;
    return *this;
}

inline Funnel::Textfont& Funnel::Textfont::sizesrc(std::string f) {
    json["sizesrc"] = std::move(f);
    return *this;
}

inline Funnel::Textfont& Funnel::Textfont::style(enum Style f) {
    json["style"] = to_string(f);
    return *this;
}
inline Funnel::Textfont& Funnel::Textfont::style(const std::vector<enum Style>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["style"] = std::move(stringified);
    return *this;
}

inline Funnel::Textfont& Funnel::Textfont::stylesrc(std::string f) {
    json["stylesrc"] = std::move(f);
    return *this;
}

inline Funnel::Textfont& Funnel::Textfont::textcase(enum Textcase f) {
    json["textcase"] = to_string(f);
    return *this;
}
inline Funnel::Textfont& Funnel::Textfont::textcase(const std::vector<enum Textcase>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["textcase"] = std::move(stringified);
    return *this;
}

inline Funnel::Textfont& Funnel::Textfont::textcasesrc(std::string f) {
    json["textcasesrc"] = std::move(f);
    return *this;
}

inline Funnel::Textfont& Funnel::Textfont::variant(enum Variant f) {
    json["variant"] = to_string(f);
    return *this;
}
inline Funnel::Textfont& Funnel::Textfont::variant(const std::vector<enum Variant>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["variant"] = std::move(stringified);
    return *this;
}

inline Funnel::Textfont& Funnel::Textfont::variantsrc(std::string f) {
    json["variantsrc"] = std::move(f);
    return *this;
}

inline Funnel::Textfont& Funnel::Textfont::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}
inline Funnel::Textfont& Funnel::Textfont::weight(const std::vector<int>& f) {
    json["weight"] = f;
    return *this;
}

inline Funnel::Textfont& Funnel::Textfont::weightsrc(std::string f) {
    json["weightsrc"] = std::move(f);
    return *this;
}

} // namespace plotlypp

