// Copyright (c) 2025-2026 Jimmy O'Rourke
// Licensed under and subject to the terms of the LICENSE file accompanying this distribution.
// Official repository: https://github.com/jimmyorourke/plotlypp

// Autogenerated by plotlypp/generator, from official Plotly sources.
// See https://plotly.com/graphing-libraries.
// Do not edit, changes may be overwritten!

#pragma once

#include <plotlypp/detail/flaglist_helpers.hpp>

namespace plotlypp {

inline std::string Funnel::to_string(Hoverinfo e) {
    switch(e) {
        case Hoverinfo::Name: return "name";
        case Hoverinfo::X: return "x";
        case Hoverinfo::Y: return "y";
        case Hoverinfo::Text: return "text";
        case Hoverinfo::PercentInitial: return "percent initial";
        case Hoverinfo::PercentPrevious: return "percent previous";
        case Hoverinfo::PercentTotal: return "percent total";
    }
    throw std::invalid_argument{"Unknown flag value for hoverinfo."};
}
inline std::string Funnel::to_string(HoverinfoExtra e) {
    switch(e) {
        case HoverinfoExtra::All: return "all";
        case HoverinfoExtra::None: return "none";
        case HoverinfoExtra::Skip: return "skip";
    }
    throw std::invalid_argument{"Unknown extra value for hoverinfo."};
}
inline std::string Funnel::to_string(Textinfo e) {
    switch(e) {
        case Textinfo::Label: return "label";
        case Textinfo::Text: return "text";
        case Textinfo::PercentInitial: return "percent initial";
        case Textinfo::PercentPrevious: return "percent previous";
        case Textinfo::PercentTotal: return "percent total";
        case Textinfo::Value: return "value";
    }
    throw std::invalid_argument{"Unknown flag value for textinfo."};
}
inline std::string Funnel::to_string(TextinfoExtra e) {
    switch(e) {
        case TextinfoExtra::None: return "none";
    }
    throw std::invalid_argument{"Unknown extra value for textinfo."};
}

inline Funnel& Funnel::alignmentgroup(std::string f) {
    json["alignmentgroup"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::cliponaxis(bool f) {
    json["cliponaxis"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::connector(Connector f) {
    json["connector"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Funnel& Funnel::connector(Callable&& c) {
    Connector f{};
    std::forward<Callable>(c)(f);
    return connector(std::move(f));
}

inline Funnel& Funnel::constraintext(enum Constraintext f) {
    switch(f) {
        case Constraintext::Inside: json["constraintext"] = "inside"; break;
        case Constraintext::Outside: json["constraintext"] = "outside"; break;
        case Constraintext::Both: json["constraintext"] = "both"; break;
        case Constraintext::None: json["constraintext"] = "none"; break;
    }
    return *this;
}

template <typename Range, typename>
inline Funnel& Funnel::customdata(Range&& f) {
    json["customdata"] = f;
    return *this;
}

inline Funnel& Funnel::customdatasrc(std::string f) {
    json["customdatasrc"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::dx(double f) {
    json["dx"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::dy(double f) {
    json["dy"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::hoverinfo(std::initializer_list<Hoverinfo> flags) {
    json["hoverinfo"] = detail::joinFlaglist(flags, [](auto f){ return to_string(f); });
    return *this;
}
inline Funnel& Funnel::hoverinfo(HoverinfoExtra extra) {
    json["hoverinfo"] = to_string(extra);
    return *this;
}

inline Funnel& Funnel::hoverinfosrc(std::string f) {
    json["hoverinfosrc"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::hoverlabel(Hoverlabel f) {
    json["hoverlabel"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Funnel& Funnel::hoverlabel(Callable&& c) {
    Hoverlabel f{};
    std::forward<Callable>(c)(f);
    return hoverlabel(std::move(f));
}

inline Funnel& Funnel::hovertemplate(std::string f) {
    json["hovertemplate"] = std::move(f);
    return *this;
}
inline Funnel& Funnel::hovertemplate(const std::vector<std::string>& f) {
    json["hovertemplate"] = f;
    return *this;
}

inline Funnel& Funnel::hovertemplatesrc(std::string f) {
    json["hovertemplatesrc"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::hovertext(std::string f) {
    json["hovertext"] = std::move(f);
    return *this;
}
inline Funnel& Funnel::hovertext(const std::vector<std::string>& f) {
    json["hovertext"] = f;
    return *this;
}

inline Funnel& Funnel::hovertextsrc(std::string f) {
    json["hovertextsrc"] = std::move(f);
    return *this;
}

template <typename Range, typename>
inline Funnel& Funnel::ids(Range&& f) {
    json["ids"] = f;
    return *this;
}

inline Funnel& Funnel::idssrc(std::string f) {
    json["idssrc"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::insidetextanchor(enum Insidetextanchor f) {
    switch(f) {
        case Insidetextanchor::End: json["insidetextanchor"] = "end"; break;
        case Insidetextanchor::Middle: json["insidetextanchor"] = "middle"; break;
        case Insidetextanchor::Start: json["insidetextanchor"] = "start"; break;
    }
    return *this;
}

inline Funnel& Funnel::insidetextfont(Insidetextfont f) {
    json["insidetextfont"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Funnel& Funnel::insidetextfont(Callable&& c) {
    Insidetextfont f{};
    std::forward<Callable>(c)(f);
    return insidetextfont(std::move(f));
}

inline Funnel& Funnel::legend(std::string f) {
    json["legend"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::legendgroup(std::string f) {
    json["legendgroup"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::legendgrouptitle(Legendgrouptitle f) {
    json["legendgrouptitle"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Funnel& Funnel::legendgrouptitle(Callable&& c) {
    Legendgrouptitle f{};
    std::forward<Callable>(c)(f);
    return legendgrouptitle(std::move(f));
}

inline Funnel& Funnel::legendrank(double f) {
    json["legendrank"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::legendwidth(double f) {
    json["legendwidth"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::marker(Marker f) {
    json["marker"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Funnel& Funnel::marker(Callable&& c) {
    Marker f{};
    std::forward<Callable>(c)(f);
    return marker(std::move(f));
}

template <typename T>
inline Funnel& Funnel::meta(T f) {
    json["meta"] = std::move(f);
    return *this;
}
template <typename T>
inline Funnel& Funnel::meta(const std::vector<T>& f) {
    json["meta"] = f;
    return *this;
}

inline Funnel& Funnel::metasrc(std::string f) {
    json["metasrc"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::name(std::string f) {
    json["name"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::offset(double f) {
    json["offset"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::offsetgroup(std::string f) {
    json["offsetgroup"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::opacity(double f) {
    json["opacity"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::orientation(enum Orientation f) {
    switch(f) {
        case Orientation::V: json["orientation"] = "v"; break;
        case Orientation::H: json["orientation"] = "h"; break;
    }
    return *this;
}

inline Funnel& Funnel::outsidetextfont(Outsidetextfont f) {
    json["outsidetextfont"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Funnel& Funnel::outsidetextfont(Callable&& c) {
    Outsidetextfont f{};
    std::forward<Callable>(c)(f);
    return outsidetextfont(std::move(f));
}

template <typename T>
inline Funnel& Funnel::selectedpoints(T f) {
    json["selectedpoints"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::showlegend(bool f) {
    json["showlegend"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::stream(Stream f) {
    json["stream"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Funnel& Funnel::stream(Callable&& c) {
    Stream f{};
    std::forward<Callable>(c)(f);
    return stream(std::move(f));
}

inline Funnel& Funnel::text(std::string f) {
    json["text"] = std::move(f);
    return *this;
}
inline Funnel& Funnel::text(const std::vector<std::string>& f) {
    json["text"] = f;
    return *this;
}

inline Funnel& Funnel::textangle(double f) {
    json["textangle"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::textfont(Textfont f) {
    json["textfont"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Funnel& Funnel::textfont(Callable&& c) {
    Textfont f{};
    std::forward<Callable>(c)(f);
    return textfont(std::move(f));
}

inline Funnel& Funnel::textinfo(std::initializer_list<Textinfo> flags) {
    json["textinfo"] = detail::joinFlaglist(flags, [](auto f){ return to_string(f); });
    return *this;
}
inline Funnel& Funnel::textinfo(TextinfoExtra extra) {
    json["textinfo"] = to_string(extra);
    return *this;
}

inline Funnel& Funnel::textposition(enum Textposition f) {
    switch(f) {
        case Textposition::Inside: json["textposition"] = "inside"; break;
        case Textposition::Outside: json["textposition"] = "outside"; break;
        case Textposition::Auto: json["textposition"] = "auto"; break;
        case Textposition::None: json["textposition"] = "none"; break;
    }
    return *this;
}
inline Funnel& Funnel::textposition(const std::vector<enum Textposition>& f) {
    Json arr = Json::array();
    for(const auto& e : f) {
        switch(e) {
            case Textposition::Inside: arr.push_back("inside"); break;
            case Textposition::Outside: arr.push_back("outside"); break;
            case Textposition::Auto: arr.push_back("auto"); break;
            case Textposition::None: arr.push_back("none"); break;
        }
    }
    json["textposition"] = std::move(arr);
    return *this;
}

inline Funnel& Funnel::textpositionsrc(std::string f) {
    json["textpositionsrc"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::textsrc(std::string f) {
    json["textsrc"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::texttemplate(std::string f) {
    json["texttemplate"] = std::move(f);
    return *this;
}
inline Funnel& Funnel::texttemplate(const std::vector<std::string>& f) {
    json["texttemplate"] = f;
    return *this;
}

inline Funnel& Funnel::texttemplatesrc(std::string f) {
    json["texttemplatesrc"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::uid(std::string f) {
    json["uid"] = std::move(f);
    return *this;
}

template <typename T>
inline Funnel& Funnel::uirevision(T f) {
    json["uirevision"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::visible(enum Visible f) {
    switch(f) {
        case Visible::True: json["visible"] = true; break;
        case Visible::False: json["visible"] = false; break;
        case Visible::Legendonly: json["visible"] = "legendonly"; break;
    }
    return *this;
}

inline Funnel& Funnel::width(double f) {
    json["width"] = std::move(f);
    return *this;
}

template <typename Range, typename>
inline Funnel& Funnel::x(Range&& f) {
    json["x"] = f;
    return *this;
}

template <typename T>
inline Funnel& Funnel::x0(T f) {
    json["x0"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::xaxis(std::string f) {
    json["xaxis"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::xhoverformat(std::string f) {
    json["xhoverformat"] = std::move(f);
    return *this;
}

template <typename T>
inline Funnel& Funnel::xperiod(T f) {
    json["xperiod"] = std::move(f);
    return *this;
}

template <typename T>
inline Funnel& Funnel::xperiod0(T f) {
    json["xperiod0"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::xperiodalignment(enum Xperiodalignment f) {
    switch(f) {
        case Xperiodalignment::Start: json["xperiodalignment"] = "start"; break;
        case Xperiodalignment::Middle: json["xperiodalignment"] = "middle"; break;
        case Xperiodalignment::End: json["xperiodalignment"] = "end"; break;
    }
    return *this;
}

inline Funnel& Funnel::xsrc(std::string f) {
    json["xsrc"] = std::move(f);
    return *this;
}

template <typename Range, typename>
inline Funnel& Funnel::y(Range&& f) {
    json["y"] = f;
    return *this;
}

template <typename T>
inline Funnel& Funnel::y0(T f) {
    json["y0"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::yaxis(std::string f) {
    json["yaxis"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::yhoverformat(std::string f) {
    json["yhoverformat"] = std::move(f);
    return *this;
}

template <typename T>
inline Funnel& Funnel::yperiod(T f) {
    json["yperiod"] = std::move(f);
    return *this;
}

template <typename T>
inline Funnel& Funnel::yperiod0(T f) {
    json["yperiod0"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::yperiodalignment(enum Yperiodalignment f) {
    switch(f) {
        case Yperiodalignment::Start: json["yperiodalignment"] = "start"; break;
        case Yperiodalignment::Middle: json["yperiodalignment"] = "middle"; break;
        case Yperiodalignment::End: json["yperiodalignment"] = "end"; break;
    }
    return *this;
}

inline Funnel& Funnel::ysrc(std::string f) {
    json["ysrc"] = std::move(f);
    return *this;
}

inline Funnel& Funnel::zorder(int f) {
    json["zorder"] = std::move(f);
    return *this;
}


inline Funnel::Connector& Funnel::Connector::fillcolor(std::string f) {
    json["fillcolor"] = std::move(f);
    return *this;
}
inline Funnel::Connector& Funnel::Connector::fillcolor(double f) {
    json["fillcolor"] = std::move(f);
    return *this;
}

inline Funnel::Connector& Funnel::Connector::line(Line f) {
    json["line"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Funnel::Connector& Funnel::Connector::line(Callable&& c) {
    Line f{};
    std::forward<Callable>(c)(f);
    return line(std::move(f));
}

inline Funnel::Connector& Funnel::Connector::visible(bool f) {
    json["visible"] = std::move(f);
    return *this;
}


inline Funnel::Connector::Line& Funnel::Connector::Line::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Funnel::Connector::Line& Funnel::Connector::Line::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

inline Funnel::Connector::Line& Funnel::Connector::Line::dash(std::string f) {
    json["dash"] = std::move(f);
    return *this;
}

inline Funnel::Connector::Line& Funnel::Connector::Line::width(double f) {
    json["width"] = std::move(f);
    return *this;
}


inline Funnel::Hoverlabel& Funnel::Hoverlabel::align(enum Align f) {
    switch(f) {
        case Align::Left: json["align"] = "left"; break;
        case Align::Right: json["align"] = "right"; break;
        case Align::Auto: json["align"] = "auto"; break;
    }
    return *this;
}
inline Funnel::Hoverlabel& Funnel::Hoverlabel::align(const std::vector<enum Align>& f) {
    Json arr = Json::array();
    for(const auto& e : f) {
        switch(e) {
            case Align::Left: arr.push_back("left"); break;
            case Align::Right: arr.push_back("right"); break;
            case Align::Auto: arr.push_back("auto"); break;
        }
    }
    json["align"] = std::move(arr);
    return *this;
}

inline Funnel::Hoverlabel& Funnel::Hoverlabel::alignsrc(std::string f) {
    json["alignsrc"] = std::move(f);
    return *this;
}

inline Funnel::Hoverlabel& Funnel::Hoverlabel::bgcolor(std::string f) {
    json["bgcolor"] = std::move(f);
    return *this;
}
inline Funnel::Hoverlabel& Funnel::Hoverlabel::bgcolor(double f) {
    json["bgcolor"] = std::move(f);
    return *this;
}
inline Funnel::Hoverlabel& Funnel::Hoverlabel::bgcolor(const std::vector<std::string>& f) {
    json["bgcolor"] = f;
    return *this;
}
inline Funnel::Hoverlabel& Funnel::Hoverlabel::bgcolor(const std::vector<double>& f) {
    json["bgcolor"] = f;
    return *this;
}

inline Funnel::Hoverlabel& Funnel::Hoverlabel::bgcolorsrc(std::string f) {
    json["bgcolorsrc"] = std::move(f);
    return *this;
}

inline Funnel::Hoverlabel& Funnel::Hoverlabel::bordercolor(std::string f) {
    json["bordercolor"] = std::move(f);
    return *this;
}
inline Funnel::Hoverlabel& Funnel::Hoverlabel::bordercolor(double f) {
    json["bordercolor"] = std::move(f);
    return *this;
}
inline Funnel::Hoverlabel& Funnel::Hoverlabel::bordercolor(const std::vector<std::string>& f) {
    json["bordercolor"] = f;
    return *this;
}
inline Funnel::Hoverlabel& Funnel::Hoverlabel::bordercolor(const std::vector<double>& f) {
    json["bordercolor"] = f;
    return *this;
}

inline Funnel::Hoverlabel& Funnel::Hoverlabel::bordercolorsrc(std::string f) {
    json["bordercolorsrc"] = std::move(f);
    return *this;
}

inline Funnel::Hoverlabel& Funnel::Hoverlabel::font(Font f) {
    json["font"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Funnel::Hoverlabel& Funnel::Hoverlabel::font(Callable&& c) {
    Font f{};
    std::forward<Callable>(c)(f);
    return font(std::move(f));
}

inline Funnel::Hoverlabel& Funnel::Hoverlabel::namelength(int f) {
    json["namelength"] = std::move(f);
    return *this;
}
inline Funnel::Hoverlabel& Funnel::Hoverlabel::namelength(const std::vector<int>& f) {
    json["namelength"] = f;
    return *this;
}

inline Funnel::Hoverlabel& Funnel::Hoverlabel::namelengthsrc(std::string f) {
    json["namelengthsrc"] = std::move(f);
    return *this;
}

inline std::string Funnel::Hoverlabel::Font::to_string(Lineposition e) {
    switch(e) {
        case Lineposition::Under: return "under";
        case Lineposition::Over: return "over";
        case Lineposition::Through: return "through";
    }
    throw std::invalid_argument{"Unknown flag value for lineposition."};
}
inline std::string Funnel::Hoverlabel::Font::to_string(LinepositionExtra e) {
    switch(e) {
        case LinepositionExtra::None: return "none";
    }
    throw std::invalid_argument{"Unknown extra value for lineposition."};
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::color(double f) {
    json["color"] = std::move(f);
    return *this;
}
inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::color(const std::vector<std::string>& f) {
    json["color"] = f;
    return *this;
}
inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::color(const std::vector<double>& f) {
    json["color"] = f;
    return *this;
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::colorsrc(std::string f) {
    json["colorsrc"] = std::move(f);
    return *this;
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}
inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::family(const std::vector<std::string>& f) {
    json["family"] = f;
    return *this;
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::familysrc(std::string f) {
    json["familysrc"] = std::move(f);
    return *this;
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::lineposition(std::initializer_list<Lineposition> flags) {
    json["lineposition"] = detail::joinFlaglist(flags, [](auto f){ return to_string(f); });
    return *this;
}
inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::lineposition(LinepositionExtra extra) {
    json["lineposition"] = to_string(extra);
    return *this;
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::linepositionsrc(std::string f) {
    json["linepositionsrc"] = std::move(f);
    return *this;
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}
inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::shadow(const std::vector<std::string>& f) {
    json["shadow"] = f;
    return *this;
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::shadowsrc(std::string f) {
    json["shadowsrc"] = std::move(f);
    return *this;
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::size(double f) {
    json["size"] = std::move(f);
    return *this;
}
inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::size(const std::vector<double>& f) {
    json["size"] = f;
    return *this;
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::sizesrc(std::string f) {
    json["sizesrc"] = std::move(f);
    return *this;
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::style(enum Style f) {
    switch(f) {
        case Style::Normal: json["style"] = "normal"; break;
        case Style::Italic: json["style"] = "italic"; break;
    }
    return *this;
}
inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::style(const std::vector<enum Style>& f) {
    Json arr = Json::array();
    for(const auto& e : f) {
        switch(e) {
            case Style::Normal: arr.push_back("normal"); break;
            case Style::Italic: arr.push_back("italic"); break;
        }
    }
    json["style"] = std::move(arr);
    return *this;
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::stylesrc(std::string f) {
    json["stylesrc"] = std::move(f);
    return *this;
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::textcase(enum Textcase f) {
    switch(f) {
        case Textcase::Normal: json["textcase"] = "normal"; break;
        case Textcase::WordCaps: json["textcase"] = "word caps"; break;
        case Textcase::Upper: json["textcase"] = "upper"; break;
        case Textcase::Lower: json["textcase"] = "lower"; break;
    }
    return *this;
}
inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::textcase(const std::vector<enum Textcase>& f) {
    Json arr = Json::array();
    for(const auto& e : f) {
        switch(e) {
            case Textcase::Normal: arr.push_back("normal"); break;
            case Textcase::WordCaps: arr.push_back("word caps"); break;
            case Textcase::Upper: arr.push_back("upper"); break;
            case Textcase::Lower: arr.push_back("lower"); break;
        }
    }
    json["textcase"] = std::move(arr);
    return *this;
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::textcasesrc(std::string f) {
    json["textcasesrc"] = std::move(f);
    return *this;
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::variant(enum Variant f) {
    switch(f) {
        case Variant::Normal: json["variant"] = "normal"; break;
        case Variant::SmallCaps: json["variant"] = "small-caps"; break;
        case Variant::AllSmallCaps: json["variant"] = "all-small-caps"; break;
        case Variant::AllPetiteCaps: json["variant"] = "all-petite-caps"; break;
        case Variant::PetiteCaps: json["variant"] = "petite-caps"; break;
        case Variant::Unicase: json["variant"] = "unicase"; break;
    }
    return *this;
}
inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::variant(const std::vector<enum Variant>& f) {
    Json arr = Json::array();
    for(const auto& e : f) {
        switch(e) {
            case Variant::Normal: arr.push_back("normal"); break;
            case Variant::SmallCaps: arr.push_back("small-caps"); break;
            case Variant::AllSmallCaps: arr.push_back("all-small-caps"); break;
            case Variant::AllPetiteCaps: arr.push_back("all-petite-caps"); break;
            case Variant::PetiteCaps: arr.push_back("petite-caps"); break;
            case Variant::Unicase: arr.push_back("unicase"); break;
        }
    }
    json["variant"] = std::move(arr);
    return *this;
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::variantsrc(std::string f) {
    json["variantsrc"] = std::move(f);
    return *this;
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}
inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::weight(const std::vector<int>& f) {
    json["weight"] = f;
    return *this;
}

inline Funnel::Hoverlabel::Font& Funnel::Hoverlabel::Font::weightsrc(std::string f) {
    json["weightsrc"] = std::move(f);
    return *this;
}

inline std::string Funnel::Insidetextfont::to_string(Lineposition e) {
    switch(e) {
        case Lineposition::Under: return "under";
        case Lineposition::Over: return "over";
        case Lineposition::Through: return "through";
    }
    throw std::invalid_argument{"Unknown flag value for lineposition."};
}
inline std::string Funnel::Insidetextfont::to_string(LinepositionExtra e) {
    switch(e) {
        case LinepositionExtra::None: return "none";
    }
    throw std::invalid_argument{"Unknown extra value for lineposition."};
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Funnel::Insidetextfont& Funnel::Insidetextfont::color(double f) {
    json["color"] = std::move(f);
    return *this;
}
inline Funnel::Insidetextfont& Funnel::Insidetextfont::color(const std::vector<std::string>& f) {
    json["color"] = f;
    return *this;
}
inline Funnel::Insidetextfont& Funnel::Insidetextfont::color(const std::vector<double>& f) {
    json["color"] = f;
    return *this;
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::colorsrc(std::string f) {
    json["colorsrc"] = std::move(f);
    return *this;
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}
inline Funnel::Insidetextfont& Funnel::Insidetextfont::family(const std::vector<std::string>& f) {
    json["family"] = f;
    return *this;
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::familysrc(std::string f) {
    json["familysrc"] = std::move(f);
    return *this;
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::lineposition(std::initializer_list<Lineposition> flags) {
    json["lineposition"] = detail::joinFlaglist(flags, [](auto f){ return to_string(f); });
    return *this;
}
inline Funnel::Insidetextfont& Funnel::Insidetextfont::lineposition(LinepositionExtra extra) {
    json["lineposition"] = to_string(extra);
    return *this;
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::linepositionsrc(std::string f) {
    json["linepositionsrc"] = std::move(f);
    return *this;
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}
inline Funnel::Insidetextfont& Funnel::Insidetextfont::shadow(const std::vector<std::string>& f) {
    json["shadow"] = f;
    return *this;
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::shadowsrc(std::string f) {
    json["shadowsrc"] = std::move(f);
    return *this;
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::size(double f) {
    json["size"] = std::move(f);
    return *this;
}
inline Funnel::Insidetextfont& Funnel::Insidetextfont::size(const std::vector<double>& f) {
    json["size"] = f;
    return *this;
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::sizesrc(std::string f) {
    json["sizesrc"] = std::move(f);
    return *this;
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::style(enum Style f) {
    switch(f) {
        case Style::Normal: json["style"] = "normal"; break;
        case Style::Italic: json["style"] = "italic"; break;
    }
    return *this;
}
inline Funnel::Insidetextfont& Funnel::Insidetextfont::style(const std::vector<enum Style>& f) {
    Json arr = Json::array();
    for(const auto& e : f) {
        switch(e) {
            case Style::Normal: arr.push_back("normal"); break;
            case Style::Italic: arr.push_back("italic"); break;
        }
    }
    json["style"] = std::move(arr);
    return *this;
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::stylesrc(std::string f) {
    json["stylesrc"] = std::move(f);
    return *this;
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::textcase(enum Textcase f) {
    switch(f) {
        case Textcase::Normal: json["textcase"] = "normal"; break;
        case Textcase::WordCaps: json["textcase"] = "word caps"; break;
        case Textcase::Upper: json["textcase"] = "upper"; break;
        case Textcase::Lower: json["textcase"] = "lower"; break;
    }
    return *this;
}
inline Funnel::Insidetextfont& Funnel::Insidetextfont::textcase(const std::vector<enum Textcase>& f) {
    Json arr = Json::array();
    for(const auto& e : f) {
        switch(e) {
            case Textcase::Normal: arr.push_back("normal"); break;
            case Textcase::WordCaps: arr.push_back("word caps"); break;
            case Textcase::Upper: arr.push_back("upper"); break;
            case Textcase::Lower: arr.push_back("lower"); break;
        }
    }
    json["textcase"] = std::move(arr);
    return *this;
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::textcasesrc(std::string f) {
    json["textcasesrc"] = std::move(f);
    return *this;
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::variant(enum Variant f) {
    switch(f) {
        case Variant::Normal: json["variant"] = "normal"; break;
        case Variant::SmallCaps: json["variant"] = "small-caps"; break;
        case Variant::AllSmallCaps: json["variant"] = "all-small-caps"; break;
        case Variant::AllPetiteCaps: json["variant"] = "all-petite-caps"; break;
        case Variant::PetiteCaps: json["variant"] = "petite-caps"; break;
        case Variant::Unicase: json["variant"] = "unicase"; break;
    }
    return *this;
}
inline Funnel::Insidetextfont& Funnel::Insidetextfont::variant(const std::vector<enum Variant>& f) {
    Json arr = Json::array();
    for(const auto& e : f) {
        switch(e) {
            case Variant::Normal: arr.push_back("normal"); break;
            case Variant::SmallCaps: arr.push_back("small-caps"); break;
            case Variant::AllSmallCaps: arr.push_back("all-small-caps"); break;
            case Variant::AllPetiteCaps: arr.push_back("all-petite-caps"); break;
            case Variant::PetiteCaps: arr.push_back("petite-caps"); break;
            case Variant::Unicase: arr.push_back("unicase"); break;
        }
    }
    json["variant"] = std::move(arr);
    return *this;
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::variantsrc(std::string f) {
    json["variantsrc"] = std::move(f);
    return *this;
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}
inline Funnel::Insidetextfont& Funnel::Insidetextfont::weight(const std::vector<int>& f) {
    json["weight"] = f;
    return *this;
}

inline Funnel::Insidetextfont& Funnel::Insidetextfont::weightsrc(std::string f) {
    json["weightsrc"] = std::move(f);
    return *this;
}


inline Funnel::Legendgrouptitle& Funnel::Legendgrouptitle::font(Font f) {
    json["font"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Funnel::Legendgrouptitle& Funnel::Legendgrouptitle::font(Callable&& c) {
    Font f{};
    std::forward<Callable>(c)(f);
    return font(std::move(f));
}

inline Funnel::Legendgrouptitle& Funnel::Legendgrouptitle::text(std::string f) {
    json["text"] = std::move(f);
    return *this;
}

inline std::string Funnel::Legendgrouptitle::Font::to_string(Lineposition e) {
    switch(e) {
        case Lineposition::Under: return "under";
        case Lineposition::Over: return "over";
        case Lineposition::Through: return "through";
    }
    throw std::invalid_argument{"Unknown flag value for lineposition."};
}
inline std::string Funnel::Legendgrouptitle::Font::to_string(LinepositionExtra e) {
    switch(e) {
        case LinepositionExtra::None: return "none";
    }
    throw std::invalid_argument{"Unknown extra value for lineposition."};
}

inline Funnel::Legendgrouptitle::Font& Funnel::Legendgrouptitle::Font::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Funnel::Legendgrouptitle::Font& Funnel::Legendgrouptitle::Font::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

inline Funnel::Legendgrouptitle::Font& Funnel::Legendgrouptitle::Font::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}

inline Funnel::Legendgrouptitle::Font& Funnel::Legendgrouptitle::Font::lineposition(std::initializer_list<Lineposition> flags) {
    json["lineposition"] = detail::joinFlaglist(flags, [](auto f){ return to_string(f); });
    return *this;
}
inline Funnel::Legendgrouptitle::Font& Funnel::Legendgrouptitle::Font::lineposition(LinepositionExtra extra) {
    json["lineposition"] = to_string(extra);
    return *this;
}

inline Funnel::Legendgrouptitle::Font& Funnel::Legendgrouptitle::Font::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}

inline Funnel::Legendgrouptitle::Font& Funnel::Legendgrouptitle::Font::size(double f) {
    json["size"] = std::move(f);
    return *this;
}

inline Funnel::Legendgrouptitle::Font& Funnel::Legendgrouptitle::Font::style(enum Style f) {
    switch(f) {
        case Style::Normal: json["style"] = "normal"; break;
        case Style::Italic: json["style"] = "italic"; break;
    }
    return *this;
}

inline Funnel::Legendgrouptitle::Font& Funnel::Legendgrouptitle::Font::textcase(enum Textcase f) {
    switch(f) {
        case Textcase::Normal: json["textcase"] = "normal"; break;
        case Textcase::WordCaps: json["textcase"] = "word caps"; break;
        case Textcase::Upper: json["textcase"] = "upper"; break;
        case Textcase::Lower: json["textcase"] = "lower"; break;
    }
    return *this;
}

inline Funnel::Legendgrouptitle::Font& Funnel::Legendgrouptitle::Font::variant(enum Variant f) {
    switch(f) {
        case Variant::Normal: json["variant"] = "normal"; break;
        case Variant::SmallCaps: json["variant"] = "small-caps"; break;
        case Variant::AllSmallCaps: json["variant"] = "all-small-caps"; break;
        case Variant::AllPetiteCaps: json["variant"] = "all-petite-caps"; break;
        case Variant::PetiteCaps: json["variant"] = "petite-caps"; break;
        case Variant::Unicase: json["variant"] = "unicase"; break;
    }
    return *this;
}

inline Funnel::Legendgrouptitle::Font& Funnel::Legendgrouptitle::Font::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}


inline Funnel::Marker& Funnel::Marker::autocolorscale(bool f) {
    json["autocolorscale"] = std::move(f);
    return *this;
}

inline Funnel::Marker& Funnel::Marker::cauto(bool f) {
    json["cauto"] = std::move(f);
    return *this;
}

inline Funnel::Marker& Funnel::Marker::cmax(double f) {
    json["cmax"] = std::move(f);
    return *this;
}

inline Funnel::Marker& Funnel::Marker::cmid(double f) {
    json["cmid"] = std::move(f);
    return *this;
}

inline Funnel::Marker& Funnel::Marker::cmin(double f) {
    json["cmin"] = std::move(f);
    return *this;
}

inline Funnel::Marker& Funnel::Marker::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Funnel::Marker& Funnel::Marker::color(double f) {
    json["color"] = std::move(f);
    return *this;
}
inline Funnel::Marker& Funnel::Marker::color(const std::vector<std::string>& f) {
    json["color"] = f;
    return *this;
}
inline Funnel::Marker& Funnel::Marker::color(const std::vector<double>& f) {
    json["color"] = f;
    return *this;
}

inline Funnel::Marker& Funnel::Marker::coloraxis(std::string f) {
    json["coloraxis"] = std::move(f);
    return *this;
}

inline Funnel::Marker& Funnel::Marker::colorbar(Colorbar f) {
    json["colorbar"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Funnel::Marker& Funnel::Marker::colorbar(Callable&& c) {
    Colorbar f{};
    std::forward<Callable>(c)(f);
    return colorbar(std::move(f));
}

inline Funnel::Marker& Funnel::Marker::colorscale(std::string f) {
    json["colorscale"] = std::move(f);
    return *this;
}
inline Funnel::Marker& Funnel::Marker::colorscale(const std::vector<std::pair<double, std::string>>& f) {
    json["colorscale"] = f;
    return *this;
}

inline Funnel::Marker& Funnel::Marker::colorsrc(std::string f) {
    json["colorsrc"] = std::move(f);
    return *this;
}

inline Funnel::Marker& Funnel::Marker::line(Line f) {
    json["line"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Funnel::Marker& Funnel::Marker::line(Callable&& c) {
    Line f{};
    std::forward<Callable>(c)(f);
    return line(std::move(f));
}

inline Funnel::Marker& Funnel::Marker::opacity(double f) {
    json["opacity"] = std::move(f);
    return *this;
}
inline Funnel::Marker& Funnel::Marker::opacity(const std::vector<double>& f) {
    json["opacity"] = f;
    return *this;
}

inline Funnel::Marker& Funnel::Marker::opacitysrc(std::string f) {
    json["opacitysrc"] = std::move(f);
    return *this;
}

inline Funnel::Marker& Funnel::Marker::reversescale(bool f) {
    json["reversescale"] = std::move(f);
    return *this;
}

inline Funnel::Marker& Funnel::Marker::showscale(bool f) {
    json["showscale"] = std::move(f);
    return *this;
}


inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::bgcolor(std::string f) {
    json["bgcolor"] = std::move(f);
    return *this;
}
inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::bgcolor(double f) {
    json["bgcolor"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::bordercolor(std::string f) {
    json["bordercolor"] = std::move(f);
    return *this;
}
inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::bordercolor(double f) {
    json["bordercolor"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::borderwidth(double f) {
    json["borderwidth"] = std::move(f);
    return *this;
}

template <typename T>
inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::dtick(T f) {
    json["dtick"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::exponentformat(enum Exponentformat f) {
    switch(f) {
        case Exponentformat::None: json["exponentformat"] = "none"; break;
        case Exponentformat::E: json["exponentformat"] = "E"; break;
        case Exponentformat::Power: json["exponentformat"] = "power"; break;
        case Exponentformat::Si: json["exponentformat"] = "SI"; break;
        case Exponentformat::B: json["exponentformat"] = "B"; break;
    }
    return *this;
}

template <typename T>
inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::labelalias(T f) {
    json["labelalias"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::len(double f) {
    json["len"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::lenmode(enum Lenmode f) {
    switch(f) {
        case Lenmode::Fraction: json["lenmode"] = "fraction"; break;
        case Lenmode::Pixels: json["lenmode"] = "pixels"; break;
    }
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::minexponent(double f) {
    json["minexponent"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::nticks(int f) {
    json["nticks"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::orientation(enum Orientation f) {
    switch(f) {
        case Orientation::H: json["orientation"] = "h"; break;
        case Orientation::V: json["orientation"] = "v"; break;
    }
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::outlinecolor(std::string f) {
    json["outlinecolor"] = std::move(f);
    return *this;
}
inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::outlinecolor(double f) {
    json["outlinecolor"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::outlinewidth(double f) {
    json["outlinewidth"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::separatethousands(bool f) {
    json["separatethousands"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::showexponent(enum Showexponent f) {
    switch(f) {
        case Showexponent::All: json["showexponent"] = "all"; break;
        case Showexponent::First: json["showexponent"] = "first"; break;
        case Showexponent::Last: json["showexponent"] = "last"; break;
        case Showexponent::None: json["showexponent"] = "none"; break;
    }
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::showticklabels(bool f) {
    json["showticklabels"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::showtickprefix(enum Showtickprefix f) {
    switch(f) {
        case Showtickprefix::All: json["showtickprefix"] = "all"; break;
        case Showtickprefix::First: json["showtickprefix"] = "first"; break;
        case Showtickprefix::Last: json["showtickprefix"] = "last"; break;
        case Showtickprefix::None: json["showtickprefix"] = "none"; break;
    }
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::showticksuffix(enum Showticksuffix f) {
    switch(f) {
        case Showticksuffix::All: json["showticksuffix"] = "all"; break;
        case Showticksuffix::First: json["showticksuffix"] = "first"; break;
        case Showticksuffix::Last: json["showticksuffix"] = "last"; break;
        case Showticksuffix::None: json["showticksuffix"] = "none"; break;
    }
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::thickness(double f) {
    json["thickness"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::thicknessmode(enum Thicknessmode f) {
    switch(f) {
        case Thicknessmode::Fraction: json["thicknessmode"] = "fraction"; break;
        case Thicknessmode::Pixels: json["thicknessmode"] = "pixels"; break;
    }
    return *this;
}

template <typename T>
inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::tick0(T f) {
    json["tick0"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::tickangle(double f) {
    json["tickangle"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::tickcolor(std::string f) {
    json["tickcolor"] = std::move(f);
    return *this;
}
inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::tickcolor(double f) {
    json["tickcolor"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::tickfont(Tickfont f) {
    json["tickfont"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::tickfont(Callable&& c) {
    Tickfont f{};
    std::forward<Callable>(c)(f);
    return tickfont(std::move(f));
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::tickformat(std::string f) {
    json["tickformat"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::tickformatstops(const std::vector<Tickformatstop>& f) {
    std::vector<Json> jsonified(f.size());
    std::transform(f.begin(), f.end(), jsonified.begin(), [](auto& e){ return e.json; });
    json["tickformatstops"] = std::move(jsonified);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::ticklabeloverflow(enum Ticklabeloverflow f) {
    switch(f) {
        case Ticklabeloverflow::Allow: json["ticklabeloverflow"] = "allow"; break;
        case Ticklabeloverflow::HidePastDiv: json["ticklabeloverflow"] = "hide past div"; break;
        case Ticklabeloverflow::HidePastDomain: json["ticklabeloverflow"] = "hide past domain"; break;
    }
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::ticklabelposition(enum Ticklabelposition f) {
    switch(f) {
        case Ticklabelposition::Outside: json["ticklabelposition"] = "outside"; break;
        case Ticklabelposition::Inside: json["ticklabelposition"] = "inside"; break;
        case Ticklabelposition::OutsideTop: json["ticklabelposition"] = "outside top"; break;
        case Ticklabelposition::InsideTop: json["ticklabelposition"] = "inside top"; break;
        case Ticklabelposition::OutsideLeft: json["ticklabelposition"] = "outside left"; break;
        case Ticklabelposition::InsideLeft: json["ticklabelposition"] = "inside left"; break;
        case Ticklabelposition::OutsideRight: json["ticklabelposition"] = "outside right"; break;
        case Ticklabelposition::InsideRight: json["ticklabelposition"] = "inside right"; break;
        case Ticklabelposition::OutsideBottom: json["ticklabelposition"] = "outside bottom"; break;
        case Ticklabelposition::InsideBottom: json["ticklabelposition"] = "inside bottom"; break;
    }
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::ticklabelstep(int f) {
    json["ticklabelstep"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::ticklen(double f) {
    json["ticklen"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::tickmode(enum Tickmode f) {
    switch(f) {
        case Tickmode::Auto: json["tickmode"] = "auto"; break;
        case Tickmode::Linear: json["tickmode"] = "linear"; break;
        case Tickmode::Array: json["tickmode"] = "array"; break;
    }
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::tickprefix(std::string f) {
    json["tickprefix"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::ticks(enum Ticks f) {
    switch(f) {
        case Ticks::Outside: json["ticks"] = "outside"; break;
        case Ticks::Inside: json["ticks"] = "inside"; break;
        case Ticks::Empty: json["ticks"] = ""; break;
    }
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::ticksuffix(std::string f) {
    json["ticksuffix"] = std::move(f);
    return *this;
}

template <typename Range, typename>
inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::ticktext(Range&& f) {
    json["ticktext"] = f;
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::ticktextsrc(std::string f) {
    json["ticktextsrc"] = std::move(f);
    return *this;
}

template <typename Range, typename>
inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::tickvals(Range&& f) {
    json["tickvals"] = f;
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::tickvalssrc(std::string f) {
    json["tickvalssrc"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::tickwidth(double f) {
    json["tickwidth"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::title(Title f) {
    json["title"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::title(Callable&& c) {
    Title f{};
    std::forward<Callable>(c)(f);
    return title(std::move(f));
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::x(double f) {
    json["x"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::xanchor(enum Xanchor f) {
    switch(f) {
        case Xanchor::Left: json["xanchor"] = "left"; break;
        case Xanchor::Center: json["xanchor"] = "center"; break;
        case Xanchor::Right: json["xanchor"] = "right"; break;
    }
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::xpad(double f) {
    json["xpad"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::xref(enum Xref f) {
    switch(f) {
        case Xref::Container: json["xref"] = "container"; break;
        case Xref::Paper: json["xref"] = "paper"; break;
    }
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::y(double f) {
    json["y"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::yanchor(enum Yanchor f) {
    switch(f) {
        case Yanchor::Top: json["yanchor"] = "top"; break;
        case Yanchor::Middle: json["yanchor"] = "middle"; break;
        case Yanchor::Bottom: json["yanchor"] = "bottom"; break;
    }
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::ypad(double f) {
    json["ypad"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar& Funnel::Marker::Colorbar::yref(enum Yref f) {
    switch(f) {
        case Yref::Container: json["yref"] = "container"; break;
        case Yref::Paper: json["yref"] = "paper"; break;
    }
    return *this;
}

inline std::string Funnel::Marker::Colorbar::Tickfont::to_string(Lineposition e) {
    switch(e) {
        case Lineposition::Under: return "under";
        case Lineposition::Over: return "over";
        case Lineposition::Through: return "through";
    }
    throw std::invalid_argument{"Unknown flag value for lineposition."};
}
inline std::string Funnel::Marker::Colorbar::Tickfont::to_string(LinepositionExtra e) {
    switch(e) {
        case LinepositionExtra::None: return "none";
    }
    throw std::invalid_argument{"Unknown extra value for lineposition."};
}

inline Funnel::Marker::Colorbar::Tickfont& Funnel::Marker::Colorbar::Tickfont::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Funnel::Marker::Colorbar::Tickfont& Funnel::Marker::Colorbar::Tickfont::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar::Tickfont& Funnel::Marker::Colorbar::Tickfont::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar::Tickfont& Funnel::Marker::Colorbar::Tickfont::lineposition(std::initializer_list<Lineposition> flags) {
    json["lineposition"] = detail::joinFlaglist(flags, [](auto f){ return to_string(f); });
    return *this;
}
inline Funnel::Marker::Colorbar::Tickfont& Funnel::Marker::Colorbar::Tickfont::lineposition(LinepositionExtra extra) {
    json["lineposition"] = to_string(extra);
    return *this;
}

inline Funnel::Marker::Colorbar::Tickfont& Funnel::Marker::Colorbar::Tickfont::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar::Tickfont& Funnel::Marker::Colorbar::Tickfont::size(double f) {
    json["size"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar::Tickfont& Funnel::Marker::Colorbar::Tickfont::style(enum Style f) {
    switch(f) {
        case Style::Normal: json["style"] = "normal"; break;
        case Style::Italic: json["style"] = "italic"; break;
    }
    return *this;
}

inline Funnel::Marker::Colorbar::Tickfont& Funnel::Marker::Colorbar::Tickfont::textcase(enum Textcase f) {
    switch(f) {
        case Textcase::Normal: json["textcase"] = "normal"; break;
        case Textcase::WordCaps: json["textcase"] = "word caps"; break;
        case Textcase::Upper: json["textcase"] = "upper"; break;
        case Textcase::Lower: json["textcase"] = "lower"; break;
    }
    return *this;
}

inline Funnel::Marker::Colorbar::Tickfont& Funnel::Marker::Colorbar::Tickfont::variant(enum Variant f) {
    switch(f) {
        case Variant::Normal: json["variant"] = "normal"; break;
        case Variant::SmallCaps: json["variant"] = "small-caps"; break;
        case Variant::AllSmallCaps: json["variant"] = "all-small-caps"; break;
        case Variant::AllPetiteCaps: json["variant"] = "all-petite-caps"; break;
        case Variant::PetiteCaps: json["variant"] = "petite-caps"; break;
        case Variant::Unicase: json["variant"] = "unicase"; break;
    }
    return *this;
}

inline Funnel::Marker::Colorbar::Tickfont& Funnel::Marker::Colorbar::Tickfont::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}


inline Funnel::Marker::Colorbar::Tickformatstop& Funnel::Marker::Colorbar::Tickformatstop::dtickrange(const std::vector<double>& f) {
    json["dtickrange"] = f;
    return *this;
}
inline Funnel::Marker::Colorbar::Tickformatstop& Funnel::Marker::Colorbar::Tickformatstop::dtickrange(const std::vector<std::string>& f) {
    json["dtickrange"] = f;
    return *this;
}
inline Funnel::Marker::Colorbar::Tickformatstop& Funnel::Marker::Colorbar::Tickformatstop::dtickrange(const std::vector<std::vector<std::string>>& f) {
    json["dtickrange"] = f;
    return *this;
}
inline Funnel::Marker::Colorbar::Tickformatstop& Funnel::Marker::Colorbar::Tickformatstop::dtickrange(const std::vector<std::vector<double>>& f) {
    json["dtickrange"] = f;
    return *this;
}

inline Funnel::Marker::Colorbar::Tickformatstop& Funnel::Marker::Colorbar::Tickformatstop::enabled(bool f) {
    json["enabled"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar::Tickformatstop& Funnel::Marker::Colorbar::Tickformatstop::name(std::string f) {
    json["name"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar::Tickformatstop& Funnel::Marker::Colorbar::Tickformatstop::templateitemname(std::string f) {
    json["templateitemname"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar::Tickformatstop& Funnel::Marker::Colorbar::Tickformatstop::value(std::string f) {
    json["value"] = std::move(f);
    return *this;
}


inline Funnel::Marker::Colorbar::Title& Funnel::Marker::Colorbar::Title::font(Font f) {
    json["font"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Funnel::Marker::Colorbar::Title& Funnel::Marker::Colorbar::Title::font(Callable&& c) {
    Font f{};
    std::forward<Callable>(c)(f);
    return font(std::move(f));
}

inline Funnel::Marker::Colorbar::Title& Funnel::Marker::Colorbar::Title::side(enum Side f) {
    switch(f) {
        case Side::Right: json["side"] = "right"; break;
        case Side::Top: json["side"] = "top"; break;
        case Side::Bottom: json["side"] = "bottom"; break;
    }
    return *this;
}

inline Funnel::Marker::Colorbar::Title& Funnel::Marker::Colorbar::Title::text(std::string f) {
    json["text"] = std::move(f);
    return *this;
}

inline std::string Funnel::Marker::Colorbar::Title::Font::to_string(Lineposition e) {
    switch(e) {
        case Lineposition::Under: return "under";
        case Lineposition::Over: return "over";
        case Lineposition::Through: return "through";
    }
    throw std::invalid_argument{"Unknown flag value for lineposition."};
}
inline std::string Funnel::Marker::Colorbar::Title::Font::to_string(LinepositionExtra e) {
    switch(e) {
        case LinepositionExtra::None: return "none";
    }
    throw std::invalid_argument{"Unknown extra value for lineposition."};
}

inline Funnel::Marker::Colorbar::Title::Font& Funnel::Marker::Colorbar::Title::Font::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Funnel::Marker::Colorbar::Title::Font& Funnel::Marker::Colorbar::Title::Font::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar::Title::Font& Funnel::Marker::Colorbar::Title::Font::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar::Title::Font& Funnel::Marker::Colorbar::Title::Font::lineposition(std::initializer_list<Lineposition> flags) {
    json["lineposition"] = detail::joinFlaglist(flags, [](auto f){ return to_string(f); });
    return *this;
}
inline Funnel::Marker::Colorbar::Title::Font& Funnel::Marker::Colorbar::Title::Font::lineposition(LinepositionExtra extra) {
    json["lineposition"] = to_string(extra);
    return *this;
}

inline Funnel::Marker::Colorbar::Title::Font& Funnel::Marker::Colorbar::Title::Font::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar::Title::Font& Funnel::Marker::Colorbar::Title::Font::size(double f) {
    json["size"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Colorbar::Title::Font& Funnel::Marker::Colorbar::Title::Font::style(enum Style f) {
    switch(f) {
        case Style::Normal: json["style"] = "normal"; break;
        case Style::Italic: json["style"] = "italic"; break;
    }
    return *this;
}

inline Funnel::Marker::Colorbar::Title::Font& Funnel::Marker::Colorbar::Title::Font::textcase(enum Textcase f) {
    switch(f) {
        case Textcase::Normal: json["textcase"] = "normal"; break;
        case Textcase::WordCaps: json["textcase"] = "word caps"; break;
        case Textcase::Upper: json["textcase"] = "upper"; break;
        case Textcase::Lower: json["textcase"] = "lower"; break;
    }
    return *this;
}

inline Funnel::Marker::Colorbar::Title::Font& Funnel::Marker::Colorbar::Title::Font::variant(enum Variant f) {
    switch(f) {
        case Variant::Normal: json["variant"] = "normal"; break;
        case Variant::SmallCaps: json["variant"] = "small-caps"; break;
        case Variant::AllSmallCaps: json["variant"] = "all-small-caps"; break;
        case Variant::AllPetiteCaps: json["variant"] = "all-petite-caps"; break;
        case Variant::PetiteCaps: json["variant"] = "petite-caps"; break;
        case Variant::Unicase: json["variant"] = "unicase"; break;
    }
    return *this;
}

inline Funnel::Marker::Colorbar::Title::Font& Funnel::Marker::Colorbar::Title::Font::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}


inline Funnel::Marker::Line& Funnel::Marker::Line::autocolorscale(bool f) {
    json["autocolorscale"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Line& Funnel::Marker::Line::cauto(bool f) {
    json["cauto"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Line& Funnel::Marker::Line::cmax(double f) {
    json["cmax"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Line& Funnel::Marker::Line::cmid(double f) {
    json["cmid"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Line& Funnel::Marker::Line::cmin(double f) {
    json["cmin"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Line& Funnel::Marker::Line::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Funnel::Marker::Line& Funnel::Marker::Line::color(double f) {
    json["color"] = std::move(f);
    return *this;
}
inline Funnel::Marker::Line& Funnel::Marker::Line::color(const std::vector<std::string>& f) {
    json["color"] = f;
    return *this;
}
inline Funnel::Marker::Line& Funnel::Marker::Line::color(const std::vector<double>& f) {
    json["color"] = f;
    return *this;
}

inline Funnel::Marker::Line& Funnel::Marker::Line::coloraxis(std::string f) {
    json["coloraxis"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Line& Funnel::Marker::Line::colorscale(std::string f) {
    json["colorscale"] = std::move(f);
    return *this;
}
inline Funnel::Marker::Line& Funnel::Marker::Line::colorscale(const std::vector<std::pair<double, std::string>>& f) {
    json["colorscale"] = f;
    return *this;
}

inline Funnel::Marker::Line& Funnel::Marker::Line::colorsrc(std::string f) {
    json["colorsrc"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Line& Funnel::Marker::Line::reversescale(bool f) {
    json["reversescale"] = std::move(f);
    return *this;
}

inline Funnel::Marker::Line& Funnel::Marker::Line::width(double f) {
    json["width"] = std::move(f);
    return *this;
}
inline Funnel::Marker::Line& Funnel::Marker::Line::width(const std::vector<double>& f) {
    json["width"] = f;
    return *this;
}

inline Funnel::Marker::Line& Funnel::Marker::Line::widthsrc(std::string f) {
    json["widthsrc"] = std::move(f);
    return *this;
}

inline std::string Funnel::Outsidetextfont::to_string(Lineposition e) {
    switch(e) {
        case Lineposition::Under: return "under";
        case Lineposition::Over: return "over";
        case Lineposition::Through: return "through";
    }
    throw std::invalid_argument{"Unknown flag value for lineposition."};
}
inline std::string Funnel::Outsidetextfont::to_string(LinepositionExtra e) {
    switch(e) {
        case LinepositionExtra::None: return "none";
    }
    throw std::invalid_argument{"Unknown extra value for lineposition."};
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::color(double f) {
    json["color"] = std::move(f);
    return *this;
}
inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::color(const std::vector<std::string>& f) {
    json["color"] = f;
    return *this;
}
inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::color(const std::vector<double>& f) {
    json["color"] = f;
    return *this;
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::colorsrc(std::string f) {
    json["colorsrc"] = std::move(f);
    return *this;
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}
inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::family(const std::vector<std::string>& f) {
    json["family"] = f;
    return *this;
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::familysrc(std::string f) {
    json["familysrc"] = std::move(f);
    return *this;
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::lineposition(std::initializer_list<Lineposition> flags) {
    json["lineposition"] = detail::joinFlaglist(flags, [](auto f){ return to_string(f); });
    return *this;
}
inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::lineposition(LinepositionExtra extra) {
    json["lineposition"] = to_string(extra);
    return *this;
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::linepositionsrc(std::string f) {
    json["linepositionsrc"] = std::move(f);
    return *this;
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}
inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::shadow(const std::vector<std::string>& f) {
    json["shadow"] = f;
    return *this;
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::shadowsrc(std::string f) {
    json["shadowsrc"] = std::move(f);
    return *this;
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::size(double f) {
    json["size"] = std::move(f);
    return *this;
}
inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::size(const std::vector<double>& f) {
    json["size"] = f;
    return *this;
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::sizesrc(std::string f) {
    json["sizesrc"] = std::move(f);
    return *this;
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::style(enum Style f) {
    switch(f) {
        case Style::Normal: json["style"] = "normal"; break;
        case Style::Italic: json["style"] = "italic"; break;
    }
    return *this;
}
inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::style(const std::vector<enum Style>& f) {
    Json arr = Json::array();
    for(const auto& e : f) {
        switch(e) {
            case Style::Normal: arr.push_back("normal"); break;
            case Style::Italic: arr.push_back("italic"); break;
        }
    }
    json["style"] = std::move(arr);
    return *this;
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::stylesrc(std::string f) {
    json["stylesrc"] = std::move(f);
    return *this;
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::textcase(enum Textcase f) {
    switch(f) {
        case Textcase::Normal: json["textcase"] = "normal"; break;
        case Textcase::WordCaps: json["textcase"] = "word caps"; break;
        case Textcase::Upper: json["textcase"] = "upper"; break;
        case Textcase::Lower: json["textcase"] = "lower"; break;
    }
    return *this;
}
inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::textcase(const std::vector<enum Textcase>& f) {
    Json arr = Json::array();
    for(const auto& e : f) {
        switch(e) {
            case Textcase::Normal: arr.push_back("normal"); break;
            case Textcase::WordCaps: arr.push_back("word caps"); break;
            case Textcase::Upper: arr.push_back("upper"); break;
            case Textcase::Lower: arr.push_back("lower"); break;
        }
    }
    json["textcase"] = std::move(arr);
    return *this;
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::textcasesrc(std::string f) {
    json["textcasesrc"] = std::move(f);
    return *this;
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::variant(enum Variant f) {
    switch(f) {
        case Variant::Normal: json["variant"] = "normal"; break;
        case Variant::SmallCaps: json["variant"] = "small-caps"; break;
        case Variant::AllSmallCaps: json["variant"] = "all-small-caps"; break;
        case Variant::AllPetiteCaps: json["variant"] = "all-petite-caps"; break;
        case Variant::PetiteCaps: json["variant"] = "petite-caps"; break;
        case Variant::Unicase: json["variant"] = "unicase"; break;
    }
    return *this;
}
inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::variant(const std::vector<enum Variant>& f) {
    Json arr = Json::array();
    for(const auto& e : f) {
        switch(e) {
            case Variant::Normal: arr.push_back("normal"); break;
            case Variant::SmallCaps: arr.push_back("small-caps"); break;
            case Variant::AllSmallCaps: arr.push_back("all-small-caps"); break;
            case Variant::AllPetiteCaps: arr.push_back("all-petite-caps"); break;
            case Variant::PetiteCaps: arr.push_back("petite-caps"); break;
            case Variant::Unicase: arr.push_back("unicase"); break;
        }
    }
    json["variant"] = std::move(arr);
    return *this;
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::variantsrc(std::string f) {
    json["variantsrc"] = std::move(f);
    return *this;
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}
inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::weight(const std::vector<int>& f) {
    json["weight"] = f;
    return *this;
}

inline Funnel::Outsidetextfont& Funnel::Outsidetextfont::weightsrc(std::string f) {
    json["weightsrc"] = std::move(f);
    return *this;
}


inline Funnel::Stream& Funnel::Stream::maxpoints(double f) {
    json["maxpoints"] = std::move(f);
    return *this;
}

inline Funnel::Stream& Funnel::Stream::token(std::string f) {
    json["token"] = std::move(f);
    return *this;
}

inline std::string Funnel::Textfont::to_string(Lineposition e) {
    switch(e) {
        case Lineposition::Under: return "under";
        case Lineposition::Over: return "over";
        case Lineposition::Through: return "through";
    }
    throw std::invalid_argument{"Unknown flag value for lineposition."};
}
inline std::string Funnel::Textfont::to_string(LinepositionExtra e) {
    switch(e) {
        case LinepositionExtra::None: return "none";
    }
    throw std::invalid_argument{"Unknown extra value for lineposition."};
}

inline Funnel::Textfont& Funnel::Textfont::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Funnel::Textfont& Funnel::Textfont::color(double f) {
    json["color"] = std::move(f);
    return *this;
}
inline Funnel::Textfont& Funnel::Textfont::color(const std::vector<std::string>& f) {
    json["color"] = f;
    return *this;
}
inline Funnel::Textfont& Funnel::Textfont::color(const std::vector<double>& f) {
    json["color"] = f;
    return *this;
}

inline Funnel::Textfont& Funnel::Textfont::colorsrc(std::string f) {
    json["colorsrc"] = std::move(f);
    return *this;
}

inline Funnel::Textfont& Funnel::Textfont::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}
inline Funnel::Textfont& Funnel::Textfont::family(const std::vector<std::string>& f) {
    json["family"] = f;
    return *this;
}

inline Funnel::Textfont& Funnel::Textfont::familysrc(std::string f) {
    json["familysrc"] = std::move(f);
    return *this;
}

inline Funnel::Textfont& Funnel::Textfont::lineposition(std::initializer_list<Lineposition> flags) {
    json["lineposition"] = detail::joinFlaglist(flags, [](auto f){ return to_string(f); });
    return *this;
}
inline Funnel::Textfont& Funnel::Textfont::lineposition(LinepositionExtra extra) {
    json["lineposition"] = to_string(extra);
    return *this;
}

inline Funnel::Textfont& Funnel::Textfont::linepositionsrc(std::string f) {
    json["linepositionsrc"] = std::move(f);
    return *this;
}

inline Funnel::Textfont& Funnel::Textfont::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}
inline Funnel::Textfont& Funnel::Textfont::shadow(const std::vector<std::string>& f) {
    json["shadow"] = f;
    return *this;
}

inline Funnel::Textfont& Funnel::Textfont::shadowsrc(std::string f) {
    json["shadowsrc"] = std::move(f);
    return *this;
}

inline Funnel::Textfont& Funnel::Textfont::size(double f) {
    json["size"] = std::move(f);
    return *this;
}
inline Funnel::Textfont& Funnel::Textfont::size(const std::vector<double>& f) {
    json["size"] = f;
    return *this;
}

inline Funnel::Textfont& Funnel::Textfont::sizesrc(std::string f) {
    json["sizesrc"] = std::move(f);
    return *this;
}

inline Funnel::Textfont& Funnel::Textfont::style(enum Style f) {
    switch(f) {
        case Style::Normal: json["style"] = "normal"; break;
        case Style::Italic: json["style"] = "italic"; break;
    }
    return *this;
}
inline Funnel::Textfont& Funnel::Textfont::style(const std::vector<enum Style>& f) {
    Json arr = Json::array();
    for(const auto& e : f) {
        switch(e) {
            case Style::Normal: arr.push_back("normal"); break;
            case Style::Italic: arr.push_back("italic"); break;
        }
    }
    json["style"] = std::move(arr);
    return *this;
}

inline Funnel::Textfont& Funnel::Textfont::stylesrc(std::string f) {
    json["stylesrc"] = std::move(f);
    return *this;
}

inline Funnel::Textfont& Funnel::Textfont::textcase(enum Textcase f) {
    switch(f) {
        case Textcase::Normal: json["textcase"] = "normal"; break;
        case Textcase::WordCaps: json["textcase"] = "word caps"; break;
        case Textcase::Upper: json["textcase"] = "upper"; break;
        case Textcase::Lower: json["textcase"] = "lower"; break;
    }
    return *this;
}
inline Funnel::Textfont& Funnel::Textfont::textcase(const std::vector<enum Textcase>& f) {
    Json arr = Json::array();
    for(const auto& e : f) {
        switch(e) {
            case Textcase::Normal: arr.push_back("normal"); break;
            case Textcase::WordCaps: arr.push_back("word caps"); break;
            case Textcase::Upper: arr.push_back("upper"); break;
            case Textcase::Lower: arr.push_back("lower"); break;
        }
    }
    json["textcase"] = std::move(arr);
    return *this;
}

inline Funnel::Textfont& Funnel::Textfont::textcasesrc(std::string f) {
    json["textcasesrc"] = std::move(f);
    return *this;
}

inline Funnel::Textfont& Funnel::Textfont::variant(enum Variant f) {
    switch(f) {
        case Variant::Normal: json["variant"] = "normal"; break;
        case Variant::SmallCaps: json["variant"] = "small-caps"; break;
        case Variant::AllSmallCaps: json["variant"] = "all-small-caps"; break;
        case Variant::AllPetiteCaps: json["variant"] = "all-petite-caps"; break;
        case Variant::PetiteCaps: json["variant"] = "petite-caps"; break;
        case Variant::Unicase: json["variant"] = "unicase"; break;
    }
    return *this;
}
inline Funnel::Textfont& Funnel::Textfont::variant(const std::vector<enum Variant>& f) {
    Json arr = Json::array();
    for(const auto& e : f) {
        switch(e) {
            case Variant::Normal: arr.push_back("normal"); break;
            case Variant::SmallCaps: arr.push_back("small-caps"); break;
            case Variant::AllSmallCaps: arr.push_back("all-small-caps"); break;
            case Variant::AllPetiteCaps: arr.push_back("all-petite-caps"); break;
            case Variant::PetiteCaps: arr.push_back("petite-caps"); break;
            case Variant::Unicase: arr.push_back("unicase"); break;
        }
    }
    json["variant"] = std::move(arr);
    return *this;
}

inline Funnel::Textfont& Funnel::Textfont::variantsrc(std::string f) {
    json["variantsrc"] = std::move(f);
    return *this;
}

inline Funnel::Textfont& Funnel::Textfont::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}
inline Funnel::Textfont& Funnel::Textfont::weight(const std::vector<int>& f) {
    json["weight"] = f;
    return *this;
}

inline Funnel::Textfont& Funnel::Textfont::weightsrc(std::string f) {
    json["weightsrc"] = std::move(f);
    return *this;
}

} // namespace plotlypp

