// Copyright (c) 2025-2026 Jimmy O'Rourke
// Licensed under and subject to the terms of the LICENSE file accompanying this distribution.
// Official repository: https://github.com/jimmyorourke/plotlypp

// Autogenerated by plotlypp/generator, from official Plotly sources.
// See https://plotly.com/graphing-libraries.
// Do not edit, changes may be overwritten!

#pragma once

#include <plotlypp/detail/flaglist_helpers.hpp>

namespace plotlypp {

inline std::string Mesh3D::to_string(Hoverinfo e) {
    switch(e) {
        case Hoverinfo::X: return "x";
        case Hoverinfo::Y: return "y";
        case Hoverinfo::Z: return "z";
        case Hoverinfo::Text: return "text";
        case Hoverinfo::Name: return "name";
    }
    throw std::invalid_argument{"Unknown flag value for hoverinfo."};
}
inline std::string Mesh3D::to_string(HoverinfoExtra e) {
    switch(e) {
        case HoverinfoExtra::All: return "all";
        case HoverinfoExtra::None: return "none";
        case HoverinfoExtra::Skip: return "skip";
    }
    throw std::invalid_argument{"Unknown extra value for hoverinfo."};
}

inline Mesh3D& Mesh3D::alphahull(double f) {
    json["alphahull"] = std::move(f);
    return *this;
}

inline Mesh3D& Mesh3D::autocolorscale(bool f) {
    json["autocolorscale"] = std::move(f);
    return *this;
}

inline Mesh3D& Mesh3D::cauto(bool f) {
    json["cauto"] = std::move(f);
    return *this;
}

inline Mesh3D& Mesh3D::cmax(double f) {
    json["cmax"] = std::move(f);
    return *this;
}

inline Mesh3D& Mesh3D::cmid(double f) {
    json["cmid"] = std::move(f);
    return *this;
}

inline Mesh3D& Mesh3D::cmin(double f) {
    json["cmin"] = std::move(f);
    return *this;
}

inline Mesh3D& Mesh3D::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Mesh3D& Mesh3D::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

inline Mesh3D& Mesh3D::coloraxis(std::string f) {
    json["coloraxis"] = std::move(f);
    return *this;
}

inline Mesh3D& Mesh3D::colorbar(Colorbar f) {
    json["colorbar"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Mesh3D& Mesh3D::colorbar(Callable&& c) {
    Colorbar f{};
    std::forward<Callable>(c)(f);
    return colorbar(std::move(f));
}

inline Mesh3D& Mesh3D::colorscale(std::string f) {
    json["colorscale"] = std::move(f);
    return *this;
}
inline Mesh3D& Mesh3D::colorscale(const std::vector<std::pair<double, std::string>>& f) {
    json["colorscale"] = f;
    return *this;
}

inline Mesh3D& Mesh3D::contour(Contour f) {
    json["contour"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Mesh3D& Mesh3D::contour(Callable&& c) {
    Contour f{};
    std::forward<Callable>(c)(f);
    return contour(std::move(f));
}

template <typename Range, typename>
inline Mesh3D& Mesh3D::customdata(Range&& f) {
    json["customdata"] = f;
    return *this;
}

inline Mesh3D& Mesh3D::customdatasrc(std::string f) {
    json["customdatasrc"] = std::move(f);
    return *this;
}

inline Mesh3D& Mesh3D::delaunayaxis(enum Delaunayaxis f) {
    switch(f) {
        case Delaunayaxis::X: json["delaunayaxis"] = "x"; break;
        case Delaunayaxis::Y: json["delaunayaxis"] = "y"; break;
        case Delaunayaxis::Z: json["delaunayaxis"] = "z"; break;
    }
    return *this;
}

template <typename Range, typename>
inline Mesh3D& Mesh3D::facecolor(Range&& f) {
    json["facecolor"] = f;
    return *this;
}

inline Mesh3D& Mesh3D::facecolorsrc(std::string f) {
    json["facecolorsrc"] = std::move(f);
    return *this;
}

inline Mesh3D& Mesh3D::flatshading(bool f) {
    json["flatshading"] = std::move(f);
    return *this;
}

inline Mesh3D& Mesh3D::hoverinfo(std::initializer_list<Hoverinfo> flags) {
    json["hoverinfo"] = detail::joinFlaglist(flags, [](auto f){ return to_string(f); });
    return *this;
}
inline Mesh3D& Mesh3D::hoverinfo(HoverinfoExtra extra) {
    json["hoverinfo"] = to_string(extra);
    return *this;
}

inline Mesh3D& Mesh3D::hoverinfosrc(std::string f) {
    json["hoverinfosrc"] = std::move(f);
    return *this;
}

inline Mesh3D& Mesh3D::hoverlabel(Hoverlabel f) {
    json["hoverlabel"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Mesh3D& Mesh3D::hoverlabel(Callable&& c) {
    Hoverlabel f{};
    std::forward<Callable>(c)(f);
    return hoverlabel(std::move(f));
}

inline Mesh3D& Mesh3D::hovertemplate(std::string f) {
    json["hovertemplate"] = std::move(f);
    return *this;
}
inline Mesh3D& Mesh3D::hovertemplate(const std::vector<std::string>& f) {
    json["hovertemplate"] = f;
    return *this;
}

inline Mesh3D& Mesh3D::hovertemplatesrc(std::string f) {
    json["hovertemplatesrc"] = std::move(f);
    return *this;
}

inline Mesh3D& Mesh3D::hovertext(std::string f) {
    json["hovertext"] = std::move(f);
    return *this;
}
inline Mesh3D& Mesh3D::hovertext(const std::vector<std::string>& f) {
    json["hovertext"] = f;
    return *this;
}

inline Mesh3D& Mesh3D::hovertextsrc(std::string f) {
    json["hovertextsrc"] = std::move(f);
    return *this;
}

template <typename Range, typename>
inline Mesh3D& Mesh3D::i(Range&& f) {
    json["i"] = f;
    return *this;
}

template <typename Range, typename>
inline Mesh3D& Mesh3D::ids(Range&& f) {
    json["ids"] = f;
    return *this;
}

inline Mesh3D& Mesh3D::idssrc(std::string f) {
    json["idssrc"] = std::move(f);
    return *this;
}

template <typename Range, typename>
inline Mesh3D& Mesh3D::intensity(Range&& f) {
    json["intensity"] = f;
    return *this;
}

inline Mesh3D& Mesh3D::intensitymode(enum Intensitymode f) {
    switch(f) {
        case Intensitymode::Vertex: json["intensitymode"] = "vertex"; break;
        case Intensitymode::Cell: json["intensitymode"] = "cell"; break;
    }
    return *this;
}

inline Mesh3D& Mesh3D::intensitysrc(std::string f) {
    json["intensitysrc"] = std::move(f);
    return *this;
}

inline Mesh3D& Mesh3D::isrc(std::string f) {
    json["isrc"] = std::move(f);
    return *this;
}

template <typename Range, typename>
inline Mesh3D& Mesh3D::j(Range&& f) {
    json["j"] = f;
    return *this;
}

inline Mesh3D& Mesh3D::jsrc(std::string f) {
    json["jsrc"] = std::move(f);
    return *this;
}

template <typename Range, typename>
inline Mesh3D& Mesh3D::k(Range&& f) {
    json["k"] = f;
    return *this;
}

inline Mesh3D& Mesh3D::ksrc(std::string f) {
    json["ksrc"] = std::move(f);
    return *this;
}

inline Mesh3D& Mesh3D::legend(std::string f) {
    json["legend"] = std::move(f);
    return *this;
}

inline Mesh3D& Mesh3D::legendgroup(std::string f) {
    json["legendgroup"] = std::move(f);
    return *this;
}

inline Mesh3D& Mesh3D::legendgrouptitle(Legendgrouptitle f) {
    json["legendgrouptitle"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Mesh3D& Mesh3D::legendgrouptitle(Callable&& c) {
    Legendgrouptitle f{};
    std::forward<Callable>(c)(f);
    return legendgrouptitle(std::move(f));
}

inline Mesh3D& Mesh3D::legendrank(double f) {
    json["legendrank"] = std::move(f);
    return *this;
}

inline Mesh3D& Mesh3D::legendwidth(double f) {
    json["legendwidth"] = std::move(f);
    return *this;
}

inline Mesh3D& Mesh3D::lighting(Lighting f) {
    json["lighting"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Mesh3D& Mesh3D::lighting(Callable&& c) {
    Lighting f{};
    std::forward<Callable>(c)(f);
    return lighting(std::move(f));
}

inline Mesh3D& Mesh3D::lightposition(Lightposition f) {
    json["lightposition"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Mesh3D& Mesh3D::lightposition(Callable&& c) {
    Lightposition f{};
    std::forward<Callable>(c)(f);
    return lightposition(std::move(f));
}

template <typename T>
inline Mesh3D& Mesh3D::meta(T f) {
    json["meta"] = std::move(f);
    return *this;
}
template <typename T>
inline Mesh3D& Mesh3D::meta(const std::vector<T>& f) {
    json["meta"] = f;
    return *this;
}

inline Mesh3D& Mesh3D::metasrc(std::string f) {
    json["metasrc"] = std::move(f);
    return *this;
}

inline Mesh3D& Mesh3D::name(std::string f) {
    json["name"] = std::move(f);
    return *this;
}

inline Mesh3D& Mesh3D::opacity(double f) {
    json["opacity"] = std::move(f);
    return *this;
}

inline Mesh3D& Mesh3D::reversescale(bool f) {
    json["reversescale"] = std::move(f);
    return *this;
}

inline Mesh3D& Mesh3D::scene(std::string f) {
    json["scene"] = std::move(f);
    return *this;
}

inline Mesh3D& Mesh3D::showlegend(bool f) {
    json["showlegend"] = std::move(f);
    return *this;
}

inline Mesh3D& Mesh3D::showscale(bool f) {
    json["showscale"] = std::move(f);
    return *this;
}

inline Mesh3D& Mesh3D::stream(Stream f) {
    json["stream"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Mesh3D& Mesh3D::stream(Callable&& c) {
    Stream f{};
    std::forward<Callable>(c)(f);
    return stream(std::move(f));
}

inline Mesh3D& Mesh3D::text(std::string f) {
    json["text"] = std::move(f);
    return *this;
}
inline Mesh3D& Mesh3D::text(const std::vector<std::string>& f) {
    json["text"] = f;
    return *this;
}

inline Mesh3D& Mesh3D::textsrc(std::string f) {
    json["textsrc"] = std::move(f);
    return *this;
}

inline Mesh3D& Mesh3D::uid(std::string f) {
    json["uid"] = std::move(f);
    return *this;
}

template <typename T>
inline Mesh3D& Mesh3D::uirevision(T f) {
    json["uirevision"] = std::move(f);
    return *this;
}

template <typename Range, typename>
inline Mesh3D& Mesh3D::vertexcolor(Range&& f) {
    json["vertexcolor"] = f;
    return *this;
}

inline Mesh3D& Mesh3D::vertexcolorsrc(std::string f) {
    json["vertexcolorsrc"] = std::move(f);
    return *this;
}

inline Mesh3D& Mesh3D::visible(enum Visible f) {
    switch(f) {
        case Visible::True: json["visible"] = true; break;
        case Visible::False: json["visible"] = false; break;
        case Visible::Legendonly: json["visible"] = "legendonly"; break;
    }
    return *this;
}

template <typename Range, typename>
inline Mesh3D& Mesh3D::x(Range&& f) {
    json["x"] = f;
    return *this;
}

inline Mesh3D& Mesh3D::xcalendar(enum Xcalendar f) {
    switch(f) {
        case Xcalendar::Chinese: json["xcalendar"] = "chinese"; break;
        case Xcalendar::Coptic: json["xcalendar"] = "coptic"; break;
        case Xcalendar::Discworld: json["xcalendar"] = "discworld"; break;
        case Xcalendar::Ethiopian: json["xcalendar"] = "ethiopian"; break;
        case Xcalendar::Gregorian: json["xcalendar"] = "gregorian"; break;
        case Xcalendar::Hebrew: json["xcalendar"] = "hebrew"; break;
        case Xcalendar::Islamic: json["xcalendar"] = "islamic"; break;
        case Xcalendar::Jalali: json["xcalendar"] = "jalali"; break;
        case Xcalendar::Julian: json["xcalendar"] = "julian"; break;
        case Xcalendar::Mayan: json["xcalendar"] = "mayan"; break;
        case Xcalendar::Nanakshahi: json["xcalendar"] = "nanakshahi"; break;
        case Xcalendar::Nepali: json["xcalendar"] = "nepali"; break;
        case Xcalendar::Persian: json["xcalendar"] = "persian"; break;
        case Xcalendar::Taiwan: json["xcalendar"] = "taiwan"; break;
        case Xcalendar::Thai: json["xcalendar"] = "thai"; break;
        case Xcalendar::Ummalqura: json["xcalendar"] = "ummalqura"; break;
    }
    return *this;
}

inline Mesh3D& Mesh3D::xhoverformat(std::string f) {
    json["xhoverformat"] = std::move(f);
    return *this;
}

inline Mesh3D& Mesh3D::xsrc(std::string f) {
    json["xsrc"] = std::move(f);
    return *this;
}

template <typename Range, typename>
inline Mesh3D& Mesh3D::y(Range&& f) {
    json["y"] = f;
    return *this;
}

inline Mesh3D& Mesh3D::ycalendar(enum Ycalendar f) {
    switch(f) {
        case Ycalendar::Chinese: json["ycalendar"] = "chinese"; break;
        case Ycalendar::Coptic: json["ycalendar"] = "coptic"; break;
        case Ycalendar::Discworld: json["ycalendar"] = "discworld"; break;
        case Ycalendar::Ethiopian: json["ycalendar"] = "ethiopian"; break;
        case Ycalendar::Gregorian: json["ycalendar"] = "gregorian"; break;
        case Ycalendar::Hebrew: json["ycalendar"] = "hebrew"; break;
        case Ycalendar::Islamic: json["ycalendar"] = "islamic"; break;
        case Ycalendar::Jalali: json["ycalendar"] = "jalali"; break;
        case Ycalendar::Julian: json["ycalendar"] = "julian"; break;
        case Ycalendar::Mayan: json["ycalendar"] = "mayan"; break;
        case Ycalendar::Nanakshahi: json["ycalendar"] = "nanakshahi"; break;
        case Ycalendar::Nepali: json["ycalendar"] = "nepali"; break;
        case Ycalendar::Persian: json["ycalendar"] = "persian"; break;
        case Ycalendar::Taiwan: json["ycalendar"] = "taiwan"; break;
        case Ycalendar::Thai: json["ycalendar"] = "thai"; break;
        case Ycalendar::Ummalqura: json["ycalendar"] = "ummalqura"; break;
    }
    return *this;
}

inline Mesh3D& Mesh3D::yhoverformat(std::string f) {
    json["yhoverformat"] = std::move(f);
    return *this;
}

inline Mesh3D& Mesh3D::ysrc(std::string f) {
    json["ysrc"] = std::move(f);
    return *this;
}

template <typename Range, typename>
inline Mesh3D& Mesh3D::z(Range&& f) {
    json["z"] = f;
    return *this;
}

inline Mesh3D& Mesh3D::zcalendar(enum Zcalendar f) {
    switch(f) {
        case Zcalendar::Chinese: json["zcalendar"] = "chinese"; break;
        case Zcalendar::Coptic: json["zcalendar"] = "coptic"; break;
        case Zcalendar::Discworld: json["zcalendar"] = "discworld"; break;
        case Zcalendar::Ethiopian: json["zcalendar"] = "ethiopian"; break;
        case Zcalendar::Gregorian: json["zcalendar"] = "gregorian"; break;
        case Zcalendar::Hebrew: json["zcalendar"] = "hebrew"; break;
        case Zcalendar::Islamic: json["zcalendar"] = "islamic"; break;
        case Zcalendar::Jalali: json["zcalendar"] = "jalali"; break;
        case Zcalendar::Julian: json["zcalendar"] = "julian"; break;
        case Zcalendar::Mayan: json["zcalendar"] = "mayan"; break;
        case Zcalendar::Nanakshahi: json["zcalendar"] = "nanakshahi"; break;
        case Zcalendar::Nepali: json["zcalendar"] = "nepali"; break;
        case Zcalendar::Persian: json["zcalendar"] = "persian"; break;
        case Zcalendar::Taiwan: json["zcalendar"] = "taiwan"; break;
        case Zcalendar::Thai: json["zcalendar"] = "thai"; break;
        case Zcalendar::Ummalqura: json["zcalendar"] = "ummalqura"; break;
    }
    return *this;
}

inline Mesh3D& Mesh3D::zhoverformat(std::string f) {
    json["zhoverformat"] = std::move(f);
    return *this;
}

inline Mesh3D& Mesh3D::zsrc(std::string f) {
    json["zsrc"] = std::move(f);
    return *this;
}


inline Mesh3D::Colorbar& Mesh3D::Colorbar::bgcolor(std::string f) {
    json["bgcolor"] = std::move(f);
    return *this;
}
inline Mesh3D::Colorbar& Mesh3D::Colorbar::bgcolor(double f) {
    json["bgcolor"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::bordercolor(std::string f) {
    json["bordercolor"] = std::move(f);
    return *this;
}
inline Mesh3D::Colorbar& Mesh3D::Colorbar::bordercolor(double f) {
    json["bordercolor"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::borderwidth(double f) {
    json["borderwidth"] = std::move(f);
    return *this;
}

template <typename T>
inline Mesh3D::Colorbar& Mesh3D::Colorbar::dtick(T f) {
    json["dtick"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::exponentformat(enum Exponentformat f) {
    switch(f) {
        case Exponentformat::None: json["exponentformat"] = "none"; break;
        case Exponentformat::E: json["exponentformat"] = "E"; break;
        case Exponentformat::Power: json["exponentformat"] = "power"; break;
        case Exponentformat::Si: json["exponentformat"] = "SI"; break;
        case Exponentformat::B: json["exponentformat"] = "B"; break;
    }
    return *this;
}

template <typename T>
inline Mesh3D::Colorbar& Mesh3D::Colorbar::labelalias(T f) {
    json["labelalias"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::len(double f) {
    json["len"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::lenmode(enum Lenmode f) {
    switch(f) {
        case Lenmode::Fraction: json["lenmode"] = "fraction"; break;
        case Lenmode::Pixels: json["lenmode"] = "pixels"; break;
    }
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::minexponent(double f) {
    json["minexponent"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::nticks(int f) {
    json["nticks"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::orientation(enum Orientation f) {
    switch(f) {
        case Orientation::H: json["orientation"] = "h"; break;
        case Orientation::V: json["orientation"] = "v"; break;
    }
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::outlinecolor(std::string f) {
    json["outlinecolor"] = std::move(f);
    return *this;
}
inline Mesh3D::Colorbar& Mesh3D::Colorbar::outlinecolor(double f) {
    json["outlinecolor"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::outlinewidth(double f) {
    json["outlinewidth"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::separatethousands(bool f) {
    json["separatethousands"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::showexponent(enum Showexponent f) {
    switch(f) {
        case Showexponent::All: json["showexponent"] = "all"; break;
        case Showexponent::First: json["showexponent"] = "first"; break;
        case Showexponent::Last: json["showexponent"] = "last"; break;
        case Showexponent::None: json["showexponent"] = "none"; break;
    }
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::showticklabels(bool f) {
    json["showticklabels"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::showtickprefix(enum Showtickprefix f) {
    switch(f) {
        case Showtickprefix::All: json["showtickprefix"] = "all"; break;
        case Showtickprefix::First: json["showtickprefix"] = "first"; break;
        case Showtickprefix::Last: json["showtickprefix"] = "last"; break;
        case Showtickprefix::None: json["showtickprefix"] = "none"; break;
    }
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::showticksuffix(enum Showticksuffix f) {
    switch(f) {
        case Showticksuffix::All: json["showticksuffix"] = "all"; break;
        case Showticksuffix::First: json["showticksuffix"] = "first"; break;
        case Showticksuffix::Last: json["showticksuffix"] = "last"; break;
        case Showticksuffix::None: json["showticksuffix"] = "none"; break;
    }
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::thickness(double f) {
    json["thickness"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::thicknessmode(enum Thicknessmode f) {
    switch(f) {
        case Thicknessmode::Fraction: json["thicknessmode"] = "fraction"; break;
        case Thicknessmode::Pixels: json["thicknessmode"] = "pixels"; break;
    }
    return *this;
}

template <typename T>
inline Mesh3D::Colorbar& Mesh3D::Colorbar::tick0(T f) {
    json["tick0"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::tickangle(double f) {
    json["tickangle"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::tickcolor(std::string f) {
    json["tickcolor"] = std::move(f);
    return *this;
}
inline Mesh3D::Colorbar& Mesh3D::Colorbar::tickcolor(double f) {
    json["tickcolor"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::tickfont(Tickfont f) {
    json["tickfont"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Mesh3D::Colorbar& Mesh3D::Colorbar::tickfont(Callable&& c) {
    Tickfont f{};
    std::forward<Callable>(c)(f);
    return tickfont(std::move(f));
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::tickformat(std::string f) {
    json["tickformat"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::tickformatstops(const std::vector<Tickformatstop>& f) {
    std::vector<Json> jsonified(f.size());
    std::transform(f.begin(), f.end(), jsonified.begin(), [](auto& e){ return e.json; });
    json["tickformatstops"] = std::move(jsonified);
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::ticklabeloverflow(enum Ticklabeloverflow f) {
    switch(f) {
        case Ticklabeloverflow::Allow: json["ticklabeloverflow"] = "allow"; break;
        case Ticklabeloverflow::HidePastDiv: json["ticklabeloverflow"] = "hide past div"; break;
        case Ticklabeloverflow::HidePastDomain: json["ticklabeloverflow"] = "hide past domain"; break;
    }
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::ticklabelposition(enum Ticklabelposition f) {
    switch(f) {
        case Ticklabelposition::Outside: json["ticklabelposition"] = "outside"; break;
        case Ticklabelposition::Inside: json["ticklabelposition"] = "inside"; break;
        case Ticklabelposition::OutsideTop: json["ticklabelposition"] = "outside top"; break;
        case Ticklabelposition::InsideTop: json["ticklabelposition"] = "inside top"; break;
        case Ticklabelposition::OutsideLeft: json["ticklabelposition"] = "outside left"; break;
        case Ticklabelposition::InsideLeft: json["ticklabelposition"] = "inside left"; break;
        case Ticklabelposition::OutsideRight: json["ticklabelposition"] = "outside right"; break;
        case Ticklabelposition::InsideRight: json["ticklabelposition"] = "inside right"; break;
        case Ticklabelposition::OutsideBottom: json["ticklabelposition"] = "outside bottom"; break;
        case Ticklabelposition::InsideBottom: json["ticklabelposition"] = "inside bottom"; break;
    }
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::ticklabelstep(int f) {
    json["ticklabelstep"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::ticklen(double f) {
    json["ticklen"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::tickmode(enum Tickmode f) {
    switch(f) {
        case Tickmode::Auto: json["tickmode"] = "auto"; break;
        case Tickmode::Linear: json["tickmode"] = "linear"; break;
        case Tickmode::Array: json["tickmode"] = "array"; break;
    }
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::tickprefix(std::string f) {
    json["tickprefix"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::ticks(enum Ticks f) {
    switch(f) {
        case Ticks::Outside: json["ticks"] = "outside"; break;
        case Ticks::Inside: json["ticks"] = "inside"; break;
        case Ticks::Empty: json["ticks"] = ""; break;
    }
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::ticksuffix(std::string f) {
    json["ticksuffix"] = std::move(f);
    return *this;
}

template <typename Range, typename>
inline Mesh3D::Colorbar& Mesh3D::Colorbar::ticktext(Range&& f) {
    json["ticktext"] = f;
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::ticktextsrc(std::string f) {
    json["ticktextsrc"] = std::move(f);
    return *this;
}

template <typename Range, typename>
inline Mesh3D::Colorbar& Mesh3D::Colorbar::tickvals(Range&& f) {
    json["tickvals"] = f;
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::tickvalssrc(std::string f) {
    json["tickvalssrc"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::tickwidth(double f) {
    json["tickwidth"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::title(Title f) {
    json["title"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Mesh3D::Colorbar& Mesh3D::Colorbar::title(Callable&& c) {
    Title f{};
    std::forward<Callable>(c)(f);
    return title(std::move(f));
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::x(double f) {
    json["x"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::xanchor(enum Xanchor f) {
    switch(f) {
        case Xanchor::Left: json["xanchor"] = "left"; break;
        case Xanchor::Center: json["xanchor"] = "center"; break;
        case Xanchor::Right: json["xanchor"] = "right"; break;
    }
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::xpad(double f) {
    json["xpad"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::xref(enum Xref f) {
    switch(f) {
        case Xref::Container: json["xref"] = "container"; break;
        case Xref::Paper: json["xref"] = "paper"; break;
    }
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::y(double f) {
    json["y"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::yanchor(enum Yanchor f) {
    switch(f) {
        case Yanchor::Top: json["yanchor"] = "top"; break;
        case Yanchor::Middle: json["yanchor"] = "middle"; break;
        case Yanchor::Bottom: json["yanchor"] = "bottom"; break;
    }
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::ypad(double f) {
    json["ypad"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar& Mesh3D::Colorbar::yref(enum Yref f) {
    switch(f) {
        case Yref::Container: json["yref"] = "container"; break;
        case Yref::Paper: json["yref"] = "paper"; break;
    }
    return *this;
}

inline std::string Mesh3D::Colorbar::Tickfont::to_string(Lineposition e) {
    switch(e) {
        case Lineposition::Under: return "under";
        case Lineposition::Over: return "over";
        case Lineposition::Through: return "through";
    }
    throw std::invalid_argument{"Unknown flag value for lineposition."};
}
inline std::string Mesh3D::Colorbar::Tickfont::to_string(LinepositionExtra e) {
    switch(e) {
        case LinepositionExtra::None: return "none";
    }
    throw std::invalid_argument{"Unknown extra value for lineposition."};
}

inline Mesh3D::Colorbar::Tickfont& Mesh3D::Colorbar::Tickfont::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Mesh3D::Colorbar::Tickfont& Mesh3D::Colorbar::Tickfont::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar::Tickfont& Mesh3D::Colorbar::Tickfont::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar::Tickfont& Mesh3D::Colorbar::Tickfont::lineposition(std::initializer_list<Lineposition> flags) {
    json["lineposition"] = detail::joinFlaglist(flags, [](auto f){ return to_string(f); });
    return *this;
}
inline Mesh3D::Colorbar::Tickfont& Mesh3D::Colorbar::Tickfont::lineposition(LinepositionExtra extra) {
    json["lineposition"] = to_string(extra);
    return *this;
}

inline Mesh3D::Colorbar::Tickfont& Mesh3D::Colorbar::Tickfont::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar::Tickfont& Mesh3D::Colorbar::Tickfont::size(double f) {
    json["size"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar::Tickfont& Mesh3D::Colorbar::Tickfont::style(enum Style f) {
    switch(f) {
        case Style::Normal: json["style"] = "normal"; break;
        case Style::Italic: json["style"] = "italic"; break;
    }
    return *this;
}

inline Mesh3D::Colorbar::Tickfont& Mesh3D::Colorbar::Tickfont::textcase(enum Textcase f) {
    switch(f) {
        case Textcase::Normal: json["textcase"] = "normal"; break;
        case Textcase::WordCaps: json["textcase"] = "word caps"; break;
        case Textcase::Upper: json["textcase"] = "upper"; break;
        case Textcase::Lower: json["textcase"] = "lower"; break;
    }
    return *this;
}

inline Mesh3D::Colorbar::Tickfont& Mesh3D::Colorbar::Tickfont::variant(enum Variant f) {
    switch(f) {
        case Variant::Normal: json["variant"] = "normal"; break;
        case Variant::SmallCaps: json["variant"] = "small-caps"; break;
        case Variant::AllSmallCaps: json["variant"] = "all-small-caps"; break;
        case Variant::AllPetiteCaps: json["variant"] = "all-petite-caps"; break;
        case Variant::PetiteCaps: json["variant"] = "petite-caps"; break;
        case Variant::Unicase: json["variant"] = "unicase"; break;
    }
    return *this;
}

inline Mesh3D::Colorbar::Tickfont& Mesh3D::Colorbar::Tickfont::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}


inline Mesh3D::Colorbar::Tickformatstop& Mesh3D::Colorbar::Tickformatstop::dtickrange(const std::vector<double>& f) {
    json["dtickrange"] = f;
    return *this;
}
inline Mesh3D::Colorbar::Tickformatstop& Mesh3D::Colorbar::Tickformatstop::dtickrange(const std::vector<std::string>& f) {
    json["dtickrange"] = f;
    return *this;
}
inline Mesh3D::Colorbar::Tickformatstop& Mesh3D::Colorbar::Tickformatstop::dtickrange(const std::vector<std::vector<std::string>>& f) {
    json["dtickrange"] = f;
    return *this;
}
inline Mesh3D::Colorbar::Tickformatstop& Mesh3D::Colorbar::Tickformatstop::dtickrange(const std::vector<std::vector<double>>& f) {
    json["dtickrange"] = f;
    return *this;
}

inline Mesh3D::Colorbar::Tickformatstop& Mesh3D::Colorbar::Tickformatstop::enabled(bool f) {
    json["enabled"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar::Tickformatstop& Mesh3D::Colorbar::Tickformatstop::name(std::string f) {
    json["name"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar::Tickformatstop& Mesh3D::Colorbar::Tickformatstop::templateitemname(std::string f) {
    json["templateitemname"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar::Tickformatstop& Mesh3D::Colorbar::Tickformatstop::value(std::string f) {
    json["value"] = std::move(f);
    return *this;
}


inline Mesh3D::Colorbar::Title& Mesh3D::Colorbar::Title::font(Font f) {
    json["font"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Mesh3D::Colorbar::Title& Mesh3D::Colorbar::Title::font(Callable&& c) {
    Font f{};
    std::forward<Callable>(c)(f);
    return font(std::move(f));
}

inline Mesh3D::Colorbar::Title& Mesh3D::Colorbar::Title::side(enum Side f) {
    switch(f) {
        case Side::Right: json["side"] = "right"; break;
        case Side::Top: json["side"] = "top"; break;
        case Side::Bottom: json["side"] = "bottom"; break;
    }
    return *this;
}

inline Mesh3D::Colorbar::Title& Mesh3D::Colorbar::Title::text(std::string f) {
    json["text"] = std::move(f);
    return *this;
}

inline std::string Mesh3D::Colorbar::Title::Font::to_string(Lineposition e) {
    switch(e) {
        case Lineposition::Under: return "under";
        case Lineposition::Over: return "over";
        case Lineposition::Through: return "through";
    }
    throw std::invalid_argument{"Unknown flag value for lineposition."};
}
inline std::string Mesh3D::Colorbar::Title::Font::to_string(LinepositionExtra e) {
    switch(e) {
        case LinepositionExtra::None: return "none";
    }
    throw std::invalid_argument{"Unknown extra value for lineposition."};
}

inline Mesh3D::Colorbar::Title::Font& Mesh3D::Colorbar::Title::Font::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Mesh3D::Colorbar::Title::Font& Mesh3D::Colorbar::Title::Font::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar::Title::Font& Mesh3D::Colorbar::Title::Font::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar::Title::Font& Mesh3D::Colorbar::Title::Font::lineposition(std::initializer_list<Lineposition> flags) {
    json["lineposition"] = detail::joinFlaglist(flags, [](auto f){ return to_string(f); });
    return *this;
}
inline Mesh3D::Colorbar::Title::Font& Mesh3D::Colorbar::Title::Font::lineposition(LinepositionExtra extra) {
    json["lineposition"] = to_string(extra);
    return *this;
}

inline Mesh3D::Colorbar::Title::Font& Mesh3D::Colorbar::Title::Font::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar::Title::Font& Mesh3D::Colorbar::Title::Font::size(double f) {
    json["size"] = std::move(f);
    return *this;
}

inline Mesh3D::Colorbar::Title::Font& Mesh3D::Colorbar::Title::Font::style(enum Style f) {
    switch(f) {
        case Style::Normal: json["style"] = "normal"; break;
        case Style::Italic: json["style"] = "italic"; break;
    }
    return *this;
}

inline Mesh3D::Colorbar::Title::Font& Mesh3D::Colorbar::Title::Font::textcase(enum Textcase f) {
    switch(f) {
        case Textcase::Normal: json["textcase"] = "normal"; break;
        case Textcase::WordCaps: json["textcase"] = "word caps"; break;
        case Textcase::Upper: json["textcase"] = "upper"; break;
        case Textcase::Lower: json["textcase"] = "lower"; break;
    }
    return *this;
}

inline Mesh3D::Colorbar::Title::Font& Mesh3D::Colorbar::Title::Font::variant(enum Variant f) {
    switch(f) {
        case Variant::Normal: json["variant"] = "normal"; break;
        case Variant::SmallCaps: json["variant"] = "small-caps"; break;
        case Variant::AllSmallCaps: json["variant"] = "all-small-caps"; break;
        case Variant::AllPetiteCaps: json["variant"] = "all-petite-caps"; break;
        case Variant::PetiteCaps: json["variant"] = "petite-caps"; break;
        case Variant::Unicase: json["variant"] = "unicase"; break;
    }
    return *this;
}

inline Mesh3D::Colorbar::Title::Font& Mesh3D::Colorbar::Title::Font::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}


inline Mesh3D::Contour& Mesh3D::Contour::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Mesh3D::Contour& Mesh3D::Contour::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

inline Mesh3D::Contour& Mesh3D::Contour::show(bool f) {
    json["show"] = std::move(f);
    return *this;
}

inline Mesh3D::Contour& Mesh3D::Contour::width(double f) {
    json["width"] = std::move(f);
    return *this;
}


inline Mesh3D::Hoverlabel& Mesh3D::Hoverlabel::align(enum Align f) {
    switch(f) {
        case Align::Left: json["align"] = "left"; break;
        case Align::Right: json["align"] = "right"; break;
        case Align::Auto: json["align"] = "auto"; break;
    }
    return *this;
}
inline Mesh3D::Hoverlabel& Mesh3D::Hoverlabel::align(const std::vector<enum Align>& f) {
    Json arr = Json::array();
    for(const auto& e : f) {
        switch(e) {
            case Align::Left: arr.push_back("left"); break;
            case Align::Right: arr.push_back("right"); break;
            case Align::Auto: arr.push_back("auto"); break;
        }
    }
    json["align"] = std::move(arr);
    return *this;
}

inline Mesh3D::Hoverlabel& Mesh3D::Hoverlabel::alignsrc(std::string f) {
    json["alignsrc"] = std::move(f);
    return *this;
}

inline Mesh3D::Hoverlabel& Mesh3D::Hoverlabel::bgcolor(std::string f) {
    json["bgcolor"] = std::move(f);
    return *this;
}
inline Mesh3D::Hoverlabel& Mesh3D::Hoverlabel::bgcolor(double f) {
    json["bgcolor"] = std::move(f);
    return *this;
}
inline Mesh3D::Hoverlabel& Mesh3D::Hoverlabel::bgcolor(const std::vector<std::string>& f) {
    json["bgcolor"] = f;
    return *this;
}
inline Mesh3D::Hoverlabel& Mesh3D::Hoverlabel::bgcolor(const std::vector<double>& f) {
    json["bgcolor"] = f;
    return *this;
}

inline Mesh3D::Hoverlabel& Mesh3D::Hoverlabel::bgcolorsrc(std::string f) {
    json["bgcolorsrc"] = std::move(f);
    return *this;
}

inline Mesh3D::Hoverlabel& Mesh3D::Hoverlabel::bordercolor(std::string f) {
    json["bordercolor"] = std::move(f);
    return *this;
}
inline Mesh3D::Hoverlabel& Mesh3D::Hoverlabel::bordercolor(double f) {
    json["bordercolor"] = std::move(f);
    return *this;
}
inline Mesh3D::Hoverlabel& Mesh3D::Hoverlabel::bordercolor(const std::vector<std::string>& f) {
    json["bordercolor"] = f;
    return *this;
}
inline Mesh3D::Hoverlabel& Mesh3D::Hoverlabel::bordercolor(const std::vector<double>& f) {
    json["bordercolor"] = f;
    return *this;
}

inline Mesh3D::Hoverlabel& Mesh3D::Hoverlabel::bordercolorsrc(std::string f) {
    json["bordercolorsrc"] = std::move(f);
    return *this;
}

inline Mesh3D::Hoverlabel& Mesh3D::Hoverlabel::font(Font f) {
    json["font"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Mesh3D::Hoverlabel& Mesh3D::Hoverlabel::font(Callable&& c) {
    Font f{};
    std::forward<Callable>(c)(f);
    return font(std::move(f));
}

inline Mesh3D::Hoverlabel& Mesh3D::Hoverlabel::namelength(int f) {
    json["namelength"] = std::move(f);
    return *this;
}
inline Mesh3D::Hoverlabel& Mesh3D::Hoverlabel::namelength(const std::vector<int>& f) {
    json["namelength"] = f;
    return *this;
}

inline Mesh3D::Hoverlabel& Mesh3D::Hoverlabel::namelengthsrc(std::string f) {
    json["namelengthsrc"] = std::move(f);
    return *this;
}

inline std::string Mesh3D::Hoverlabel::Font::to_string(Lineposition e) {
    switch(e) {
        case Lineposition::Under: return "under";
        case Lineposition::Over: return "over";
        case Lineposition::Through: return "through";
    }
    throw std::invalid_argument{"Unknown flag value for lineposition."};
}
inline std::string Mesh3D::Hoverlabel::Font::to_string(LinepositionExtra e) {
    switch(e) {
        case LinepositionExtra::None: return "none";
    }
    throw std::invalid_argument{"Unknown extra value for lineposition."};
}

inline Mesh3D::Hoverlabel::Font& Mesh3D::Hoverlabel::Font::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Mesh3D::Hoverlabel::Font& Mesh3D::Hoverlabel::Font::color(double f) {
    json["color"] = std::move(f);
    return *this;
}
inline Mesh3D::Hoverlabel::Font& Mesh3D::Hoverlabel::Font::color(const std::vector<std::string>& f) {
    json["color"] = f;
    return *this;
}
inline Mesh3D::Hoverlabel::Font& Mesh3D::Hoverlabel::Font::color(const std::vector<double>& f) {
    json["color"] = f;
    return *this;
}

inline Mesh3D::Hoverlabel::Font& Mesh3D::Hoverlabel::Font::colorsrc(std::string f) {
    json["colorsrc"] = std::move(f);
    return *this;
}

inline Mesh3D::Hoverlabel::Font& Mesh3D::Hoverlabel::Font::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}
inline Mesh3D::Hoverlabel::Font& Mesh3D::Hoverlabel::Font::family(const std::vector<std::string>& f) {
    json["family"] = f;
    return *this;
}

inline Mesh3D::Hoverlabel::Font& Mesh3D::Hoverlabel::Font::familysrc(std::string f) {
    json["familysrc"] = std::move(f);
    return *this;
}

inline Mesh3D::Hoverlabel::Font& Mesh3D::Hoverlabel::Font::lineposition(std::initializer_list<Lineposition> flags) {
    json["lineposition"] = detail::joinFlaglist(flags, [](auto f){ return to_string(f); });
    return *this;
}
inline Mesh3D::Hoverlabel::Font& Mesh3D::Hoverlabel::Font::lineposition(LinepositionExtra extra) {
    json["lineposition"] = to_string(extra);
    return *this;
}

inline Mesh3D::Hoverlabel::Font& Mesh3D::Hoverlabel::Font::linepositionsrc(std::string f) {
    json["linepositionsrc"] = std::move(f);
    return *this;
}

inline Mesh3D::Hoverlabel::Font& Mesh3D::Hoverlabel::Font::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}
inline Mesh3D::Hoverlabel::Font& Mesh3D::Hoverlabel::Font::shadow(const std::vector<std::string>& f) {
    json["shadow"] = f;
    return *this;
}

inline Mesh3D::Hoverlabel::Font& Mesh3D::Hoverlabel::Font::shadowsrc(std::string f) {
    json["shadowsrc"] = std::move(f);
    return *this;
}

inline Mesh3D::Hoverlabel::Font& Mesh3D::Hoverlabel::Font::size(double f) {
    json["size"] = std::move(f);
    return *this;
}
inline Mesh3D::Hoverlabel::Font& Mesh3D::Hoverlabel::Font::size(const std::vector<double>& f) {
    json["size"] = f;
    return *this;
}

inline Mesh3D::Hoverlabel::Font& Mesh3D::Hoverlabel::Font::sizesrc(std::string f) {
    json["sizesrc"] = std::move(f);
    return *this;
}

inline Mesh3D::Hoverlabel::Font& Mesh3D::Hoverlabel::Font::style(enum Style f) {
    switch(f) {
        case Style::Normal: json["style"] = "normal"; break;
        case Style::Italic: json["style"] = "italic"; break;
    }
    return *this;
}
inline Mesh3D::Hoverlabel::Font& Mesh3D::Hoverlabel::Font::style(const std::vector<enum Style>& f) {
    Json arr = Json::array();
    for(const auto& e : f) {
        switch(e) {
            case Style::Normal: arr.push_back("normal"); break;
            case Style::Italic: arr.push_back("italic"); break;
        }
    }
    json["style"] = std::move(arr);
    return *this;
}

inline Mesh3D::Hoverlabel::Font& Mesh3D::Hoverlabel::Font::stylesrc(std::string f) {
    json["stylesrc"] = std::move(f);
    return *this;
}

inline Mesh3D::Hoverlabel::Font& Mesh3D::Hoverlabel::Font::textcase(enum Textcase f) {
    switch(f) {
        case Textcase::Normal: json["textcase"] = "normal"; break;
        case Textcase::WordCaps: json["textcase"] = "word caps"; break;
        case Textcase::Upper: json["textcase"] = "upper"; break;
        case Textcase::Lower: json["textcase"] = "lower"; break;
    }
    return *this;
}
inline Mesh3D::Hoverlabel::Font& Mesh3D::Hoverlabel::Font::textcase(const std::vector<enum Textcase>& f) {
    Json arr = Json::array();
    for(const auto& e : f) {
        switch(e) {
            case Textcase::Normal: arr.push_back("normal"); break;
            case Textcase::WordCaps: arr.push_back("word caps"); break;
            case Textcase::Upper: arr.push_back("upper"); break;
            case Textcase::Lower: arr.push_back("lower"); break;
        }
    }
    json["textcase"] = std::move(arr);
    return *this;
}

inline Mesh3D::Hoverlabel::Font& Mesh3D::Hoverlabel::Font::textcasesrc(std::string f) {
    json["textcasesrc"] = std::move(f);
    return *this;
}

inline Mesh3D::Hoverlabel::Font& Mesh3D::Hoverlabel::Font::variant(enum Variant f) {
    switch(f) {
        case Variant::Normal: json["variant"] = "normal"; break;
        case Variant::SmallCaps: json["variant"] = "small-caps"; break;
        case Variant::AllSmallCaps: json["variant"] = "all-small-caps"; break;
        case Variant::AllPetiteCaps: json["variant"] = "all-petite-caps"; break;
        case Variant::PetiteCaps: json["variant"] = "petite-caps"; break;
        case Variant::Unicase: json["variant"] = "unicase"; break;
    }
    return *this;
}
inline Mesh3D::Hoverlabel::Font& Mesh3D::Hoverlabel::Font::variant(const std::vector<enum Variant>& f) {
    Json arr = Json::array();
    for(const auto& e : f) {
        switch(e) {
            case Variant::Normal: arr.push_back("normal"); break;
            case Variant::SmallCaps: arr.push_back("small-caps"); break;
            case Variant::AllSmallCaps: arr.push_back("all-small-caps"); break;
            case Variant::AllPetiteCaps: arr.push_back("all-petite-caps"); break;
            case Variant::PetiteCaps: arr.push_back("petite-caps"); break;
            case Variant::Unicase: arr.push_back("unicase"); break;
        }
    }
    json["variant"] = std::move(arr);
    return *this;
}

inline Mesh3D::Hoverlabel::Font& Mesh3D::Hoverlabel::Font::variantsrc(std::string f) {
    json["variantsrc"] = std::move(f);
    return *this;
}

inline Mesh3D::Hoverlabel::Font& Mesh3D::Hoverlabel::Font::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}
inline Mesh3D::Hoverlabel::Font& Mesh3D::Hoverlabel::Font::weight(const std::vector<int>& f) {
    json["weight"] = f;
    return *this;
}

inline Mesh3D::Hoverlabel::Font& Mesh3D::Hoverlabel::Font::weightsrc(std::string f) {
    json["weightsrc"] = std::move(f);
    return *this;
}


inline Mesh3D::Legendgrouptitle& Mesh3D::Legendgrouptitle::font(Font f) {
    json["font"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Mesh3D::Legendgrouptitle& Mesh3D::Legendgrouptitle::font(Callable&& c) {
    Font f{};
    std::forward<Callable>(c)(f);
    return font(std::move(f));
}

inline Mesh3D::Legendgrouptitle& Mesh3D::Legendgrouptitle::text(std::string f) {
    json["text"] = std::move(f);
    return *this;
}

inline std::string Mesh3D::Legendgrouptitle::Font::to_string(Lineposition e) {
    switch(e) {
        case Lineposition::Under: return "under";
        case Lineposition::Over: return "over";
        case Lineposition::Through: return "through";
    }
    throw std::invalid_argument{"Unknown flag value for lineposition."};
}
inline std::string Mesh3D::Legendgrouptitle::Font::to_string(LinepositionExtra e) {
    switch(e) {
        case LinepositionExtra::None: return "none";
    }
    throw std::invalid_argument{"Unknown extra value for lineposition."};
}

inline Mesh3D::Legendgrouptitle::Font& Mesh3D::Legendgrouptitle::Font::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Mesh3D::Legendgrouptitle::Font& Mesh3D::Legendgrouptitle::Font::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

inline Mesh3D::Legendgrouptitle::Font& Mesh3D::Legendgrouptitle::Font::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}

inline Mesh3D::Legendgrouptitle::Font& Mesh3D::Legendgrouptitle::Font::lineposition(std::initializer_list<Lineposition> flags) {
    json["lineposition"] = detail::joinFlaglist(flags, [](auto f){ return to_string(f); });
    return *this;
}
inline Mesh3D::Legendgrouptitle::Font& Mesh3D::Legendgrouptitle::Font::lineposition(LinepositionExtra extra) {
    json["lineposition"] = to_string(extra);
    return *this;
}

inline Mesh3D::Legendgrouptitle::Font& Mesh3D::Legendgrouptitle::Font::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}

inline Mesh3D::Legendgrouptitle::Font& Mesh3D::Legendgrouptitle::Font::size(double f) {
    json["size"] = std::move(f);
    return *this;
}

inline Mesh3D::Legendgrouptitle::Font& Mesh3D::Legendgrouptitle::Font::style(enum Style f) {
    switch(f) {
        case Style::Normal: json["style"] = "normal"; break;
        case Style::Italic: json["style"] = "italic"; break;
    }
    return *this;
}

inline Mesh3D::Legendgrouptitle::Font& Mesh3D::Legendgrouptitle::Font::textcase(enum Textcase f) {
    switch(f) {
        case Textcase::Normal: json["textcase"] = "normal"; break;
        case Textcase::WordCaps: json["textcase"] = "word caps"; break;
        case Textcase::Upper: json["textcase"] = "upper"; break;
        case Textcase::Lower: json["textcase"] = "lower"; break;
    }
    return *this;
}

inline Mesh3D::Legendgrouptitle::Font& Mesh3D::Legendgrouptitle::Font::variant(enum Variant f) {
    switch(f) {
        case Variant::Normal: json["variant"] = "normal"; break;
        case Variant::SmallCaps: json["variant"] = "small-caps"; break;
        case Variant::AllSmallCaps: json["variant"] = "all-small-caps"; break;
        case Variant::AllPetiteCaps: json["variant"] = "all-petite-caps"; break;
        case Variant::PetiteCaps: json["variant"] = "petite-caps"; break;
        case Variant::Unicase: json["variant"] = "unicase"; break;
    }
    return *this;
}

inline Mesh3D::Legendgrouptitle::Font& Mesh3D::Legendgrouptitle::Font::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}


inline Mesh3D::Lighting& Mesh3D::Lighting::ambient(double f) {
    json["ambient"] = std::move(f);
    return *this;
}

inline Mesh3D::Lighting& Mesh3D::Lighting::diffuse(double f) {
    json["diffuse"] = std::move(f);
    return *this;
}

inline Mesh3D::Lighting& Mesh3D::Lighting::facenormalsepsilon(double f) {
    json["facenormalsepsilon"] = std::move(f);
    return *this;
}

inline Mesh3D::Lighting& Mesh3D::Lighting::fresnel(double f) {
    json["fresnel"] = std::move(f);
    return *this;
}

inline Mesh3D::Lighting& Mesh3D::Lighting::roughness(double f) {
    json["roughness"] = std::move(f);
    return *this;
}

inline Mesh3D::Lighting& Mesh3D::Lighting::specular(double f) {
    json["specular"] = std::move(f);
    return *this;
}

inline Mesh3D::Lighting& Mesh3D::Lighting::vertexnormalsepsilon(double f) {
    json["vertexnormalsepsilon"] = std::move(f);
    return *this;
}


inline Mesh3D::Lightposition& Mesh3D::Lightposition::x(double f) {
    json["x"] = std::move(f);
    return *this;
}

inline Mesh3D::Lightposition& Mesh3D::Lightposition::y(double f) {
    json["y"] = std::move(f);
    return *this;
}

inline Mesh3D::Lightposition& Mesh3D::Lightposition::z(double f) {
    json["z"] = std::move(f);
    return *this;
}


inline Mesh3D::Stream& Mesh3D::Stream::maxpoints(double f) {
    json["maxpoints"] = std::move(f);
    return *this;
}

inline Mesh3D::Stream& Mesh3D::Stream::token(std::string f) {
    json["token"] = std::move(f);
    return *this;
}

} // namespace plotlypp

