// Copyright (c) 2025 Jimmy O'Rourke
// Licensed under and subject to the terms of the LICENSE file accompanying this distribution.
// Official repository: https://github.com/jimmyorourke/plotlypp

// Autogenerated by plotlypp/generator, from official Plotly sources.
// See https://plotly.com/graphing-libraries.
// Do not edit, changes may be overwritten!

#pragma once

namespace plotlypp {

inline std::string Sunburst::to_string(Branchvalues e) {
    switch(e) {
        case Branchvalues::Remainder: return "remainder";
        case Branchvalues::Total: return "total";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Sunburst::to_string(Insidetextorientation e) {
    switch(e) {
        case Insidetextorientation::Horizontal: return "horizontal";
        case Insidetextorientation::Radial: return "radial";
        case Insidetextorientation::Tangential: return "tangential";
        case Insidetextorientation::Auto: return "auto";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Sunburst::to_string(Visible e) {
    switch(e) {
        case Visible::True: return "True";
        case Visible::False: return "False";
        case Visible::Legendonly: return "legendonly";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

inline Sunburst& Sunburst::branchvalues(enum Branchvalues f) {
    json["branchvalues"] = to_string(f);
    return *this;
}

inline Sunburst& Sunburst::count(std::string f) {
    json["count"] = std::move(f);
    return *this;
}

template <typename Range, typename>
inline Sunburst& Sunburst::customdata(Range&& f) {
    json["customdata"] = f;
    return *this;
}

inline Sunburst& Sunburst::customdatasrc(std::string f) {
    json["customdatasrc"] = std::move(f);
    return *this;
}

inline Sunburst& Sunburst::domain(Domain f) {
    json["domain"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Sunburst& Sunburst::domain(Callable&& c) {
    Domain f{};
    std::forward<Callable>(c)(f);
    return domain(std::move(f));
}

inline Sunburst& Sunburst::hoverinfo(std::string f) {
    json["hoverinfo"] = std::move(f);
    return *this;
}
inline Sunburst& Sunburst::hoverinfo(const std::vector<std::string>& f) {
    json["hoverinfo"] = f;
    return *this;
}

inline Sunburst& Sunburst::hoverinfosrc(std::string f) {
    json["hoverinfosrc"] = std::move(f);
    return *this;
}

inline Sunburst& Sunburst::hoverlabel(Hoverlabel f) {
    json["hoverlabel"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Sunburst& Sunburst::hoverlabel(Callable&& c) {
    Hoverlabel f{};
    std::forward<Callable>(c)(f);
    return hoverlabel(std::move(f));
}

inline Sunburst& Sunburst::hovertemplate(std::string f) {
    json["hovertemplate"] = std::move(f);
    return *this;
}
inline Sunburst& Sunburst::hovertemplate(const std::vector<std::string>& f) {
    json["hovertemplate"] = f;
    return *this;
}

inline Sunburst& Sunburst::hovertemplatesrc(std::string f) {
    json["hovertemplatesrc"] = std::move(f);
    return *this;
}

inline Sunburst& Sunburst::hovertext(std::string f) {
    json["hovertext"] = std::move(f);
    return *this;
}
inline Sunburst& Sunburst::hovertext(const std::vector<std::string>& f) {
    json["hovertext"] = f;
    return *this;
}

inline Sunburst& Sunburst::hovertextsrc(std::string f) {
    json["hovertextsrc"] = std::move(f);
    return *this;
}

template <typename Range, typename>
inline Sunburst& Sunburst::ids(Range&& f) {
    json["ids"] = f;
    return *this;
}

inline Sunburst& Sunburst::idssrc(std::string f) {
    json["idssrc"] = std::move(f);
    return *this;
}

inline Sunburst& Sunburst::insidetextfont(Insidetextfont f) {
    json["insidetextfont"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Sunburst& Sunburst::insidetextfont(Callable&& c) {
    Insidetextfont f{};
    std::forward<Callable>(c)(f);
    return insidetextfont(std::move(f));
}

inline Sunburst& Sunburst::insidetextorientation(enum Insidetextorientation f) {
    json["insidetextorientation"] = to_string(f);
    return *this;
}

template <typename Range, typename>
inline Sunburst& Sunburst::labels(Range&& f) {
    json["labels"] = f;
    return *this;
}

inline Sunburst& Sunburst::labelssrc(std::string f) {
    json["labelssrc"] = std::move(f);
    return *this;
}

inline Sunburst& Sunburst::leaf(Leaf f) {
    json["leaf"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Sunburst& Sunburst::leaf(Callable&& c) {
    Leaf f{};
    std::forward<Callable>(c)(f);
    return leaf(std::move(f));
}

inline Sunburst& Sunburst::legend(std::string f) {
    json["legend"] = std::move(f);
    return *this;
}

inline Sunburst& Sunburst::legendgrouptitle(Legendgrouptitle f) {
    json["legendgrouptitle"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Sunburst& Sunburst::legendgrouptitle(Callable&& c) {
    Legendgrouptitle f{};
    std::forward<Callable>(c)(f);
    return legendgrouptitle(std::move(f));
}

inline Sunburst& Sunburst::legendrank(double f) {
    json["legendrank"] = std::move(f);
    return *this;
}

inline Sunburst& Sunburst::legendwidth(double f) {
    json["legendwidth"] = std::move(f);
    return *this;
}

template <typename T>
inline Sunburst& Sunburst::level(T f) {
    json["level"] = std::move(f);
    return *this;
}

inline Sunburst& Sunburst::marker(Marker f) {
    json["marker"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Sunburst& Sunburst::marker(Callable&& c) {
    Marker f{};
    std::forward<Callable>(c)(f);
    return marker(std::move(f));
}

inline Sunburst& Sunburst::maxdepth(int f) {
    json["maxdepth"] = std::move(f);
    return *this;
}

template <typename T>
inline Sunburst& Sunburst::meta(T f) {
    json["meta"] = std::move(f);
    return *this;
}
template <typename T>
inline Sunburst& Sunburst::meta(const std::vector<T>& f) {
    json["meta"] = f;
    return *this;
}

inline Sunburst& Sunburst::metasrc(std::string f) {
    json["metasrc"] = std::move(f);
    return *this;
}

inline Sunburst& Sunburst::name(std::string f) {
    json["name"] = std::move(f);
    return *this;
}

inline Sunburst& Sunburst::opacity(double f) {
    json["opacity"] = std::move(f);
    return *this;
}

inline Sunburst& Sunburst::outsidetextfont(Outsidetextfont f) {
    json["outsidetextfont"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Sunburst& Sunburst::outsidetextfont(Callable&& c) {
    Outsidetextfont f{};
    std::forward<Callable>(c)(f);
    return outsidetextfont(std::move(f));
}

template <typename Range, typename>
inline Sunburst& Sunburst::parents(Range&& f) {
    json["parents"] = f;
    return *this;
}

inline Sunburst& Sunburst::parentssrc(std::string f) {
    json["parentssrc"] = std::move(f);
    return *this;
}

inline Sunburst& Sunburst::root(Root f) {
    json["root"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Sunburst& Sunburst::root(Callable&& c) {
    Root f{};
    std::forward<Callable>(c)(f);
    return root(std::move(f));
}

inline Sunburst& Sunburst::rotation(double f) {
    json["rotation"] = std::move(f);
    return *this;
}

inline Sunburst& Sunburst::sort(bool f) {
    json["sort"] = std::move(f);
    return *this;
}

inline Sunburst& Sunburst::stream(Stream f) {
    json["stream"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Sunburst& Sunburst::stream(Callable&& c) {
    Stream f{};
    std::forward<Callable>(c)(f);
    return stream(std::move(f));
}

template <typename Range, typename>
inline Sunburst& Sunburst::text(Range&& f) {
    json["text"] = f;
    return *this;
}

inline Sunburst& Sunburst::textfont(Textfont f) {
    json["textfont"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Sunburst& Sunburst::textfont(Callable&& c) {
    Textfont f{};
    std::forward<Callable>(c)(f);
    return textfont(std::move(f));
}

inline Sunburst& Sunburst::textinfo(std::string f) {
    json["textinfo"] = std::move(f);
    return *this;
}

inline Sunburst& Sunburst::textsrc(std::string f) {
    json["textsrc"] = std::move(f);
    return *this;
}

inline Sunburst& Sunburst::texttemplate(std::string f) {
    json["texttemplate"] = std::move(f);
    return *this;
}
inline Sunburst& Sunburst::texttemplate(const std::vector<std::string>& f) {
    json["texttemplate"] = f;
    return *this;
}

inline Sunburst& Sunburst::texttemplatesrc(std::string f) {
    json["texttemplatesrc"] = std::move(f);
    return *this;
}

inline Sunburst& Sunburst::uid(std::string f) {
    json["uid"] = std::move(f);
    return *this;
}

template <typename T>
inline Sunburst& Sunburst::uirevision(T f) {
    json["uirevision"] = std::move(f);
    return *this;
}

template <typename Range, typename>
inline Sunburst& Sunburst::values(Range&& f) {
    json["values"] = f;
    return *this;
}

inline Sunburst& Sunburst::valuessrc(std::string f) {
    json["valuessrc"] = std::move(f);
    return *this;
}

inline Sunburst& Sunburst::visible(enum Visible f) {
    json["visible"] = to_string(f);
    return *this;
}


inline Sunburst::Domain& Sunburst::Domain::column(int f) {
    json["column"] = std::move(f);
    return *this;
}

inline Sunburst::Domain& Sunburst::Domain::row(int f) {
    json["row"] = std::move(f);
    return *this;
}

inline Sunburst::Domain& Sunburst::Domain::x(const std::vector<double>& f) {
    json["x"] = f;
    return *this;
}
inline Sunburst::Domain& Sunburst::Domain::x(const std::vector<std::string>& f) {
    json["x"] = f;
    return *this;
}
inline Sunburst::Domain& Sunburst::Domain::x(const std::vector<std::vector<std::string>>& f) {
    json["x"] = f;
    return *this;
}
inline Sunburst::Domain& Sunburst::Domain::x(const std::vector<std::vector<double>>& f) {
    json["x"] = f;
    return *this;
}

inline Sunburst::Domain& Sunburst::Domain::y(const std::vector<double>& f) {
    json["y"] = f;
    return *this;
}
inline Sunburst::Domain& Sunburst::Domain::y(const std::vector<std::string>& f) {
    json["y"] = f;
    return *this;
}
inline Sunburst::Domain& Sunburst::Domain::y(const std::vector<std::vector<std::string>>& f) {
    json["y"] = f;
    return *this;
}
inline Sunburst::Domain& Sunburst::Domain::y(const std::vector<std::vector<double>>& f) {
    json["y"] = f;
    return *this;
}

inline std::string Sunburst::Hoverlabel::to_string(Align e) {
    switch(e) {
        case Align::Left: return "left";
        case Align::Right: return "right";
        case Align::Auto: return "auto";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

inline Sunburst::Hoverlabel& Sunburst::Hoverlabel::align(enum Align f) {
    json["align"] = to_string(f);
    return *this;
}
inline Sunburst::Hoverlabel& Sunburst::Hoverlabel::align(const std::vector<enum Align>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["align"] = std::move(stringified);
    return *this;
}

inline Sunburst::Hoverlabel& Sunburst::Hoverlabel::alignsrc(std::string f) {
    json["alignsrc"] = std::move(f);
    return *this;
}

inline Sunburst::Hoverlabel& Sunburst::Hoverlabel::bgcolor(std::string f) {
    json["bgcolor"] = std::move(f);
    return *this;
}
inline Sunburst::Hoverlabel& Sunburst::Hoverlabel::bgcolor(double f) {
    json["bgcolor"] = std::move(f);
    return *this;
}
inline Sunburst::Hoverlabel& Sunburst::Hoverlabel::bgcolor(const std::vector<std::string>& f) {
    json["bgcolor"] = f;
    return *this;
}
inline Sunburst::Hoverlabel& Sunburst::Hoverlabel::bgcolor(const std::vector<double>& f) {
    json["bgcolor"] = f;
    return *this;
}

inline Sunburst::Hoverlabel& Sunburst::Hoverlabel::bgcolorsrc(std::string f) {
    json["bgcolorsrc"] = std::move(f);
    return *this;
}

inline Sunburst::Hoverlabel& Sunburst::Hoverlabel::bordercolor(std::string f) {
    json["bordercolor"] = std::move(f);
    return *this;
}
inline Sunburst::Hoverlabel& Sunburst::Hoverlabel::bordercolor(double f) {
    json["bordercolor"] = std::move(f);
    return *this;
}
inline Sunburst::Hoverlabel& Sunburst::Hoverlabel::bordercolor(const std::vector<std::string>& f) {
    json["bordercolor"] = f;
    return *this;
}
inline Sunburst::Hoverlabel& Sunburst::Hoverlabel::bordercolor(const std::vector<double>& f) {
    json["bordercolor"] = f;
    return *this;
}

inline Sunburst::Hoverlabel& Sunburst::Hoverlabel::bordercolorsrc(std::string f) {
    json["bordercolorsrc"] = std::move(f);
    return *this;
}

inline Sunburst::Hoverlabel& Sunburst::Hoverlabel::font(Font f) {
    json["font"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Sunburst::Hoverlabel& Sunburst::Hoverlabel::font(Callable&& c) {
    Font f{};
    std::forward<Callable>(c)(f);
    return font(std::move(f));
}

inline Sunburst::Hoverlabel& Sunburst::Hoverlabel::namelength(int f) {
    json["namelength"] = std::move(f);
    return *this;
}
inline Sunburst::Hoverlabel& Sunburst::Hoverlabel::namelength(const std::vector<int>& f) {
    json["namelength"] = f;
    return *this;
}

inline Sunburst::Hoverlabel& Sunburst::Hoverlabel::namelengthsrc(std::string f) {
    json["namelengthsrc"] = std::move(f);
    return *this;
}

inline std::string Sunburst::Hoverlabel::Font::to_string(Style e) {
    switch(e) {
        case Style::Normal: return "normal";
        case Style::Italic: return "italic";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Sunburst::Hoverlabel::Font::to_string(Textcase e) {
    switch(e) {
        case Textcase::Normal: return "normal";
        case Textcase::WordCaps: return "word caps";
        case Textcase::Upper: return "upper";
        case Textcase::Lower: return "lower";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Sunburst::Hoverlabel::Font::to_string(Variant e) {
    switch(e) {
        case Variant::Normal: return "normal";
        case Variant::SmallCaps: return "small-caps";
        case Variant::AllSmallCaps: return "all-small-caps";
        case Variant::AllPetiteCaps: return "all-petite-caps";
        case Variant::PetiteCaps: return "petite-caps";
        case Variant::Unicase: return "unicase";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

inline Sunburst::Hoverlabel::Font& Sunburst::Hoverlabel::Font::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Sunburst::Hoverlabel::Font& Sunburst::Hoverlabel::Font::color(double f) {
    json["color"] = std::move(f);
    return *this;
}
inline Sunburst::Hoverlabel::Font& Sunburst::Hoverlabel::Font::color(const std::vector<std::string>& f) {
    json["color"] = f;
    return *this;
}
inline Sunburst::Hoverlabel::Font& Sunburst::Hoverlabel::Font::color(const std::vector<double>& f) {
    json["color"] = f;
    return *this;
}

inline Sunburst::Hoverlabel::Font& Sunburst::Hoverlabel::Font::colorsrc(std::string f) {
    json["colorsrc"] = std::move(f);
    return *this;
}

inline Sunburst::Hoverlabel::Font& Sunburst::Hoverlabel::Font::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}
inline Sunburst::Hoverlabel::Font& Sunburst::Hoverlabel::Font::family(const std::vector<std::string>& f) {
    json["family"] = f;
    return *this;
}

inline Sunburst::Hoverlabel::Font& Sunburst::Hoverlabel::Font::familysrc(std::string f) {
    json["familysrc"] = std::move(f);
    return *this;
}

inline Sunburst::Hoverlabel::Font& Sunburst::Hoverlabel::Font::lineposition(std::string f) {
    json["lineposition"] = std::move(f);
    return *this;
}
inline Sunburst::Hoverlabel::Font& Sunburst::Hoverlabel::Font::lineposition(const std::vector<std::string>& f) {
    json["lineposition"] = f;
    return *this;
}

inline Sunburst::Hoverlabel::Font& Sunburst::Hoverlabel::Font::linepositionsrc(std::string f) {
    json["linepositionsrc"] = std::move(f);
    return *this;
}

inline Sunburst::Hoverlabel::Font& Sunburst::Hoverlabel::Font::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}
inline Sunburst::Hoverlabel::Font& Sunburst::Hoverlabel::Font::shadow(const std::vector<std::string>& f) {
    json["shadow"] = f;
    return *this;
}

inline Sunburst::Hoverlabel::Font& Sunburst::Hoverlabel::Font::shadowsrc(std::string f) {
    json["shadowsrc"] = std::move(f);
    return *this;
}

inline Sunburst::Hoverlabel::Font& Sunburst::Hoverlabel::Font::size(double f) {
    json["size"] = std::move(f);
    return *this;
}
inline Sunburst::Hoverlabel::Font& Sunburst::Hoverlabel::Font::size(const std::vector<double>& f) {
    json["size"] = f;
    return *this;
}

inline Sunburst::Hoverlabel::Font& Sunburst::Hoverlabel::Font::sizesrc(std::string f) {
    json["sizesrc"] = std::move(f);
    return *this;
}

inline Sunburst::Hoverlabel::Font& Sunburst::Hoverlabel::Font::style(enum Style f) {
    json["style"] = to_string(f);
    return *this;
}
inline Sunburst::Hoverlabel::Font& Sunburst::Hoverlabel::Font::style(const std::vector<enum Style>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["style"] = std::move(stringified);
    return *this;
}

inline Sunburst::Hoverlabel::Font& Sunburst::Hoverlabel::Font::stylesrc(std::string f) {
    json["stylesrc"] = std::move(f);
    return *this;
}

inline Sunburst::Hoverlabel::Font& Sunburst::Hoverlabel::Font::textcase(enum Textcase f) {
    json["textcase"] = to_string(f);
    return *this;
}
inline Sunburst::Hoverlabel::Font& Sunburst::Hoverlabel::Font::textcase(const std::vector<enum Textcase>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["textcase"] = std::move(stringified);
    return *this;
}

inline Sunburst::Hoverlabel::Font& Sunburst::Hoverlabel::Font::textcasesrc(std::string f) {
    json["textcasesrc"] = std::move(f);
    return *this;
}

inline Sunburst::Hoverlabel::Font& Sunburst::Hoverlabel::Font::variant(enum Variant f) {
    json["variant"] = to_string(f);
    return *this;
}
inline Sunburst::Hoverlabel::Font& Sunburst::Hoverlabel::Font::variant(const std::vector<enum Variant>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["variant"] = std::move(stringified);
    return *this;
}

inline Sunburst::Hoverlabel::Font& Sunburst::Hoverlabel::Font::variantsrc(std::string f) {
    json["variantsrc"] = std::move(f);
    return *this;
}

inline Sunburst::Hoverlabel::Font& Sunburst::Hoverlabel::Font::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}
inline Sunburst::Hoverlabel::Font& Sunburst::Hoverlabel::Font::weight(const std::vector<int>& f) {
    json["weight"] = f;
    return *this;
}

inline Sunburst::Hoverlabel::Font& Sunburst::Hoverlabel::Font::weightsrc(std::string f) {
    json["weightsrc"] = std::move(f);
    return *this;
}

inline std::string Sunburst::Insidetextfont::to_string(Style e) {
    switch(e) {
        case Style::Normal: return "normal";
        case Style::Italic: return "italic";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Sunburst::Insidetextfont::to_string(Textcase e) {
    switch(e) {
        case Textcase::Normal: return "normal";
        case Textcase::WordCaps: return "word caps";
        case Textcase::Upper: return "upper";
        case Textcase::Lower: return "lower";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Sunburst::Insidetextfont::to_string(Variant e) {
    switch(e) {
        case Variant::Normal: return "normal";
        case Variant::SmallCaps: return "small-caps";
        case Variant::AllSmallCaps: return "all-small-caps";
        case Variant::AllPetiteCaps: return "all-petite-caps";
        case Variant::PetiteCaps: return "petite-caps";
        case Variant::Unicase: return "unicase";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

inline Sunburst::Insidetextfont& Sunburst::Insidetextfont::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Sunburst::Insidetextfont& Sunburst::Insidetextfont::color(double f) {
    json["color"] = std::move(f);
    return *this;
}
inline Sunburst::Insidetextfont& Sunburst::Insidetextfont::color(const std::vector<std::string>& f) {
    json["color"] = f;
    return *this;
}
inline Sunburst::Insidetextfont& Sunburst::Insidetextfont::color(const std::vector<double>& f) {
    json["color"] = f;
    return *this;
}

inline Sunburst::Insidetextfont& Sunburst::Insidetextfont::colorsrc(std::string f) {
    json["colorsrc"] = std::move(f);
    return *this;
}

inline Sunburst::Insidetextfont& Sunburst::Insidetextfont::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}
inline Sunburst::Insidetextfont& Sunburst::Insidetextfont::family(const std::vector<std::string>& f) {
    json["family"] = f;
    return *this;
}

inline Sunburst::Insidetextfont& Sunburst::Insidetextfont::familysrc(std::string f) {
    json["familysrc"] = std::move(f);
    return *this;
}

inline Sunburst::Insidetextfont& Sunburst::Insidetextfont::lineposition(std::string f) {
    json["lineposition"] = std::move(f);
    return *this;
}
inline Sunburst::Insidetextfont& Sunburst::Insidetextfont::lineposition(const std::vector<std::string>& f) {
    json["lineposition"] = f;
    return *this;
}

inline Sunburst::Insidetextfont& Sunburst::Insidetextfont::linepositionsrc(std::string f) {
    json["linepositionsrc"] = std::move(f);
    return *this;
}

inline Sunburst::Insidetextfont& Sunburst::Insidetextfont::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}
inline Sunburst::Insidetextfont& Sunburst::Insidetextfont::shadow(const std::vector<std::string>& f) {
    json["shadow"] = f;
    return *this;
}

inline Sunburst::Insidetextfont& Sunburst::Insidetextfont::shadowsrc(std::string f) {
    json["shadowsrc"] = std::move(f);
    return *this;
}

inline Sunburst::Insidetextfont& Sunburst::Insidetextfont::size(double f) {
    json["size"] = std::move(f);
    return *this;
}
inline Sunburst::Insidetextfont& Sunburst::Insidetextfont::size(const std::vector<double>& f) {
    json["size"] = f;
    return *this;
}

inline Sunburst::Insidetextfont& Sunburst::Insidetextfont::sizesrc(std::string f) {
    json["sizesrc"] = std::move(f);
    return *this;
}

inline Sunburst::Insidetextfont& Sunburst::Insidetextfont::style(enum Style f) {
    json["style"] = to_string(f);
    return *this;
}
inline Sunburst::Insidetextfont& Sunburst::Insidetextfont::style(const std::vector<enum Style>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["style"] = std::move(stringified);
    return *this;
}

inline Sunburst::Insidetextfont& Sunburst::Insidetextfont::stylesrc(std::string f) {
    json["stylesrc"] = std::move(f);
    return *this;
}

inline Sunburst::Insidetextfont& Sunburst::Insidetextfont::textcase(enum Textcase f) {
    json["textcase"] = to_string(f);
    return *this;
}
inline Sunburst::Insidetextfont& Sunburst::Insidetextfont::textcase(const std::vector<enum Textcase>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["textcase"] = std::move(stringified);
    return *this;
}

inline Sunburst::Insidetextfont& Sunburst::Insidetextfont::textcasesrc(std::string f) {
    json["textcasesrc"] = std::move(f);
    return *this;
}

inline Sunburst::Insidetextfont& Sunburst::Insidetextfont::variant(enum Variant f) {
    json["variant"] = to_string(f);
    return *this;
}
inline Sunburst::Insidetextfont& Sunburst::Insidetextfont::variant(const std::vector<enum Variant>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["variant"] = std::move(stringified);
    return *this;
}

inline Sunburst::Insidetextfont& Sunburst::Insidetextfont::variantsrc(std::string f) {
    json["variantsrc"] = std::move(f);
    return *this;
}

inline Sunburst::Insidetextfont& Sunburst::Insidetextfont::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}
inline Sunburst::Insidetextfont& Sunburst::Insidetextfont::weight(const std::vector<int>& f) {
    json["weight"] = f;
    return *this;
}

inline Sunburst::Insidetextfont& Sunburst::Insidetextfont::weightsrc(std::string f) {
    json["weightsrc"] = std::move(f);
    return *this;
}


inline Sunburst::Leaf& Sunburst::Leaf::opacity(double f) {
    json["opacity"] = std::move(f);
    return *this;
}


inline Sunburst::Legendgrouptitle& Sunburst::Legendgrouptitle::font(Font f) {
    json["font"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Sunburst::Legendgrouptitle& Sunburst::Legendgrouptitle::font(Callable&& c) {
    Font f{};
    std::forward<Callable>(c)(f);
    return font(std::move(f));
}

inline Sunburst::Legendgrouptitle& Sunburst::Legendgrouptitle::text(std::string f) {
    json["text"] = std::move(f);
    return *this;
}

inline std::string Sunburst::Legendgrouptitle::Font::to_string(Style e) {
    switch(e) {
        case Style::Normal: return "normal";
        case Style::Italic: return "italic";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Sunburst::Legendgrouptitle::Font::to_string(Textcase e) {
    switch(e) {
        case Textcase::Normal: return "normal";
        case Textcase::WordCaps: return "word caps";
        case Textcase::Upper: return "upper";
        case Textcase::Lower: return "lower";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Sunburst::Legendgrouptitle::Font::to_string(Variant e) {
    switch(e) {
        case Variant::Normal: return "normal";
        case Variant::SmallCaps: return "small-caps";
        case Variant::AllSmallCaps: return "all-small-caps";
        case Variant::AllPetiteCaps: return "all-petite-caps";
        case Variant::PetiteCaps: return "petite-caps";
        case Variant::Unicase: return "unicase";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

inline Sunburst::Legendgrouptitle::Font& Sunburst::Legendgrouptitle::Font::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Sunburst::Legendgrouptitle::Font& Sunburst::Legendgrouptitle::Font::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

inline Sunburst::Legendgrouptitle::Font& Sunburst::Legendgrouptitle::Font::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}

inline Sunburst::Legendgrouptitle::Font& Sunburst::Legendgrouptitle::Font::lineposition(std::string f) {
    json["lineposition"] = std::move(f);
    return *this;
}

inline Sunburst::Legendgrouptitle::Font& Sunburst::Legendgrouptitle::Font::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}

inline Sunburst::Legendgrouptitle::Font& Sunburst::Legendgrouptitle::Font::size(double f) {
    json["size"] = std::move(f);
    return *this;
}

inline Sunburst::Legendgrouptitle::Font& Sunburst::Legendgrouptitle::Font::style(enum Style f) {
    json["style"] = to_string(f);
    return *this;
}

inline Sunburst::Legendgrouptitle::Font& Sunburst::Legendgrouptitle::Font::textcase(enum Textcase f) {
    json["textcase"] = to_string(f);
    return *this;
}

inline Sunburst::Legendgrouptitle::Font& Sunburst::Legendgrouptitle::Font::variant(enum Variant f) {
    json["variant"] = to_string(f);
    return *this;
}

inline Sunburst::Legendgrouptitle::Font& Sunburst::Legendgrouptitle::Font::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}


inline Sunburst::Marker& Sunburst::Marker::autocolorscale(bool f) {
    json["autocolorscale"] = std::move(f);
    return *this;
}

inline Sunburst::Marker& Sunburst::Marker::cauto(bool f) {
    json["cauto"] = std::move(f);
    return *this;
}

inline Sunburst::Marker& Sunburst::Marker::cmax(double f) {
    json["cmax"] = std::move(f);
    return *this;
}

inline Sunburst::Marker& Sunburst::Marker::cmid(double f) {
    json["cmid"] = std::move(f);
    return *this;
}

inline Sunburst::Marker& Sunburst::Marker::cmin(double f) {
    json["cmin"] = std::move(f);
    return *this;
}

inline Sunburst::Marker& Sunburst::Marker::coloraxis(std::string f) {
    json["coloraxis"] = std::move(f);
    return *this;
}

inline Sunburst::Marker& Sunburst::Marker::colorbar(Colorbar f) {
    json["colorbar"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Sunburst::Marker& Sunburst::Marker::colorbar(Callable&& c) {
    Colorbar f{};
    std::forward<Callable>(c)(f);
    return colorbar(std::move(f));
}

template <typename Range, typename>
inline Sunburst::Marker& Sunburst::Marker::colors(Range&& f) {
    json["colors"] = f;
    return *this;
}

inline Sunburst::Marker& Sunburst::Marker::colorscale(std::string f) {
    json["colorscale"] = std::move(f);
    return *this;
}
inline Sunburst::Marker& Sunburst::Marker::colorscale(const std::vector<std::pair<double, std::string>>& f) {
    json["colorscale"] = f;
    return *this;
}

inline Sunburst::Marker& Sunburst::Marker::colorssrc(std::string f) {
    json["colorssrc"] = std::move(f);
    return *this;
}

inline Sunburst::Marker& Sunburst::Marker::line(Line f) {
    json["line"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Sunburst::Marker& Sunburst::Marker::line(Callable&& c) {
    Line f{};
    std::forward<Callable>(c)(f);
    return line(std::move(f));
}

inline Sunburst::Marker& Sunburst::Marker::pattern(Pattern f) {
    json["pattern"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Sunburst::Marker& Sunburst::Marker::pattern(Callable&& c) {
    Pattern f{};
    std::forward<Callable>(c)(f);
    return pattern(std::move(f));
}

inline Sunburst::Marker& Sunburst::Marker::reversescale(bool f) {
    json["reversescale"] = std::move(f);
    return *this;
}

inline Sunburst::Marker& Sunburst::Marker::showscale(bool f) {
    json["showscale"] = std::move(f);
    return *this;
}

inline std::string Sunburst::Marker::Colorbar::to_string(Exponentformat e) {
    switch(e) {
        case Exponentformat::None: return "none";
        case Exponentformat::E: return "E";
        case Exponentformat::Power: return "power";
        case Exponentformat::Si: return "SI";
        case Exponentformat::B: return "B";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Sunburst::Marker::Colorbar::to_string(Lenmode e) {
    switch(e) {
        case Lenmode::Fraction: return "fraction";
        case Lenmode::Pixels: return "pixels";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Sunburst::Marker::Colorbar::to_string(Orientation e) {
    switch(e) {
        case Orientation::H: return "h";
        case Orientation::V: return "v";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Sunburst::Marker::Colorbar::to_string(Showexponent e) {
    switch(e) {
        case Showexponent::All: return "all";
        case Showexponent::First: return "first";
        case Showexponent::Last: return "last";
        case Showexponent::None: return "none";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Sunburst::Marker::Colorbar::to_string(Showtickprefix e) {
    switch(e) {
        case Showtickprefix::All: return "all";
        case Showtickprefix::First: return "first";
        case Showtickprefix::Last: return "last";
        case Showtickprefix::None: return "none";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Sunburst::Marker::Colorbar::to_string(Showticksuffix e) {
    switch(e) {
        case Showticksuffix::All: return "all";
        case Showticksuffix::First: return "first";
        case Showticksuffix::Last: return "last";
        case Showticksuffix::None: return "none";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Sunburst::Marker::Colorbar::to_string(Thicknessmode e) {
    switch(e) {
        case Thicknessmode::Fraction: return "fraction";
        case Thicknessmode::Pixels: return "pixels";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Sunburst::Marker::Colorbar::to_string(Ticklabeloverflow e) {
    switch(e) {
        case Ticklabeloverflow::Allow: return "allow";
        case Ticklabeloverflow::HidePastDiv: return "hide past div";
        case Ticklabeloverflow::HidePastDomain: return "hide past domain";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Sunburst::Marker::Colorbar::to_string(Ticklabelposition e) {
    switch(e) {
        case Ticklabelposition::Outside: return "outside";
        case Ticklabelposition::Inside: return "inside";
        case Ticklabelposition::OutsideTop: return "outside top";
        case Ticklabelposition::InsideTop: return "inside top";
        case Ticklabelposition::OutsideLeft: return "outside left";
        case Ticklabelposition::InsideLeft: return "inside left";
        case Ticklabelposition::OutsideRight: return "outside right";
        case Ticklabelposition::InsideRight: return "inside right";
        case Ticklabelposition::OutsideBottom: return "outside bottom";
        case Ticklabelposition::InsideBottom: return "inside bottom";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Sunburst::Marker::Colorbar::to_string(Tickmode e) {
    switch(e) {
        case Tickmode::Auto: return "auto";
        case Tickmode::Linear: return "linear";
        case Tickmode::Array: return "array";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Sunburst::Marker::Colorbar::to_string(Ticks e) {
    switch(e) {
        case Ticks::Outside: return "outside";
        case Ticks::Inside: return "inside";
        case Ticks::Empty: return "";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Sunburst::Marker::Colorbar::to_string(Xanchor e) {
    switch(e) {
        case Xanchor::Left: return "left";
        case Xanchor::Center: return "center";
        case Xanchor::Right: return "right";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Sunburst::Marker::Colorbar::to_string(Xref e) {
    switch(e) {
        case Xref::Container: return "container";
        case Xref::Paper: return "paper";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Sunburst::Marker::Colorbar::to_string(Yanchor e) {
    switch(e) {
        case Yanchor::Top: return "top";
        case Yanchor::Middle: return "middle";
        case Yanchor::Bottom: return "bottom";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Sunburst::Marker::Colorbar::to_string(Yref e) {
    switch(e) {
        case Yref::Container: return "container";
        case Yref::Paper: return "paper";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::bgcolor(std::string f) {
    json["bgcolor"] = std::move(f);
    return *this;
}
inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::bgcolor(double f) {
    json["bgcolor"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::bordercolor(std::string f) {
    json["bordercolor"] = std::move(f);
    return *this;
}
inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::bordercolor(double f) {
    json["bordercolor"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::borderwidth(double f) {
    json["borderwidth"] = std::move(f);
    return *this;
}

template <typename T>
inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::dtick(T f) {
    json["dtick"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::exponentformat(enum Exponentformat f) {
    json["exponentformat"] = to_string(f);
    return *this;
}

template <typename T>
inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::labelalias(T f) {
    json["labelalias"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::len(double f) {
    json["len"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::lenmode(enum Lenmode f) {
    json["lenmode"] = to_string(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::minexponent(double f) {
    json["minexponent"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::nticks(int f) {
    json["nticks"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::orientation(enum Orientation f) {
    json["orientation"] = to_string(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::outlinecolor(std::string f) {
    json["outlinecolor"] = std::move(f);
    return *this;
}
inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::outlinecolor(double f) {
    json["outlinecolor"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::outlinewidth(double f) {
    json["outlinewidth"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::separatethousands(bool f) {
    json["separatethousands"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::showexponent(enum Showexponent f) {
    json["showexponent"] = to_string(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::showticklabels(bool f) {
    json["showticklabels"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::showtickprefix(enum Showtickprefix f) {
    json["showtickprefix"] = to_string(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::showticksuffix(enum Showticksuffix f) {
    json["showticksuffix"] = to_string(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::thickness(double f) {
    json["thickness"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::thicknessmode(enum Thicknessmode f) {
    json["thicknessmode"] = to_string(f);
    return *this;
}

template <typename T>
inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::tick0(T f) {
    json["tick0"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::tickangle(double f) {
    json["tickangle"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::tickcolor(std::string f) {
    json["tickcolor"] = std::move(f);
    return *this;
}
inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::tickcolor(double f) {
    json["tickcolor"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::tickfont(Tickfont f) {
    json["tickfont"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::tickfont(Callable&& c) {
    Tickfont f{};
    std::forward<Callable>(c)(f);
    return tickfont(std::move(f));
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::tickformat(std::string f) {
    json["tickformat"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::tickformatstops(const std::vector<Tickformatstop>& f) {
    std::vector<Json> jsonified(f.size());
    std::transform(f.begin(), f.end(), jsonified.begin(), [](auto& e){ return e.json; });
    json["tickformatstops"] = std::move(jsonified);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::ticklabeloverflow(enum Ticklabeloverflow f) {
    json["ticklabeloverflow"] = to_string(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::ticklabelposition(enum Ticklabelposition f) {
    json["ticklabelposition"] = to_string(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::ticklabelstep(int f) {
    json["ticklabelstep"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::ticklen(double f) {
    json["ticklen"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::tickmode(enum Tickmode f) {
    json["tickmode"] = to_string(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::tickprefix(std::string f) {
    json["tickprefix"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::ticks(enum Ticks f) {
    json["ticks"] = to_string(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::ticksuffix(std::string f) {
    json["ticksuffix"] = std::move(f);
    return *this;
}

template <typename Range, typename>
inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::ticktext(Range&& f) {
    json["ticktext"] = f;
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::ticktextsrc(std::string f) {
    json["ticktextsrc"] = std::move(f);
    return *this;
}

template <typename Range, typename>
inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::tickvals(Range&& f) {
    json["tickvals"] = f;
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::tickvalssrc(std::string f) {
    json["tickvalssrc"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::tickwidth(double f) {
    json["tickwidth"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::title(Title f) {
    json["title"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::title(Callable&& c) {
    Title f{};
    std::forward<Callable>(c)(f);
    return title(std::move(f));
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::x(double f) {
    json["x"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::xanchor(enum Xanchor f) {
    json["xanchor"] = to_string(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::xpad(double f) {
    json["xpad"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::xref(enum Xref f) {
    json["xref"] = to_string(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::y(double f) {
    json["y"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::yanchor(enum Yanchor f) {
    json["yanchor"] = to_string(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::ypad(double f) {
    json["ypad"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar& Sunburst::Marker::Colorbar::yref(enum Yref f) {
    json["yref"] = to_string(f);
    return *this;
}

inline std::string Sunburst::Marker::Colorbar::Tickfont::to_string(Style e) {
    switch(e) {
        case Style::Normal: return "normal";
        case Style::Italic: return "italic";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Sunburst::Marker::Colorbar::Tickfont::to_string(Textcase e) {
    switch(e) {
        case Textcase::Normal: return "normal";
        case Textcase::WordCaps: return "word caps";
        case Textcase::Upper: return "upper";
        case Textcase::Lower: return "lower";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Sunburst::Marker::Colorbar::Tickfont::to_string(Variant e) {
    switch(e) {
        case Variant::Normal: return "normal";
        case Variant::SmallCaps: return "small-caps";
        case Variant::AllSmallCaps: return "all-small-caps";
        case Variant::AllPetiteCaps: return "all-petite-caps";
        case Variant::PetiteCaps: return "petite-caps";
        case Variant::Unicase: return "unicase";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

inline Sunburst::Marker::Colorbar::Tickfont& Sunburst::Marker::Colorbar::Tickfont::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Sunburst::Marker::Colorbar::Tickfont& Sunburst::Marker::Colorbar::Tickfont::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar::Tickfont& Sunburst::Marker::Colorbar::Tickfont::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar::Tickfont& Sunburst::Marker::Colorbar::Tickfont::lineposition(std::string f) {
    json["lineposition"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar::Tickfont& Sunburst::Marker::Colorbar::Tickfont::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar::Tickfont& Sunburst::Marker::Colorbar::Tickfont::size(double f) {
    json["size"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar::Tickfont& Sunburst::Marker::Colorbar::Tickfont::style(enum Style f) {
    json["style"] = to_string(f);
    return *this;
}

inline Sunburst::Marker::Colorbar::Tickfont& Sunburst::Marker::Colorbar::Tickfont::textcase(enum Textcase f) {
    json["textcase"] = to_string(f);
    return *this;
}

inline Sunburst::Marker::Colorbar::Tickfont& Sunburst::Marker::Colorbar::Tickfont::variant(enum Variant f) {
    json["variant"] = to_string(f);
    return *this;
}

inline Sunburst::Marker::Colorbar::Tickfont& Sunburst::Marker::Colorbar::Tickfont::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}


inline Sunburst::Marker::Colorbar::Tickformatstop& Sunburst::Marker::Colorbar::Tickformatstop::dtickrange(const std::vector<double>& f) {
    json["dtickrange"] = f;
    return *this;
}
inline Sunburst::Marker::Colorbar::Tickformatstop& Sunburst::Marker::Colorbar::Tickformatstop::dtickrange(const std::vector<std::string>& f) {
    json["dtickrange"] = f;
    return *this;
}
inline Sunburst::Marker::Colorbar::Tickformatstop& Sunburst::Marker::Colorbar::Tickformatstop::dtickrange(const std::vector<std::vector<std::string>>& f) {
    json["dtickrange"] = f;
    return *this;
}
inline Sunburst::Marker::Colorbar::Tickformatstop& Sunburst::Marker::Colorbar::Tickformatstop::dtickrange(const std::vector<std::vector<double>>& f) {
    json["dtickrange"] = f;
    return *this;
}

inline Sunburst::Marker::Colorbar::Tickformatstop& Sunburst::Marker::Colorbar::Tickformatstop::enabled(bool f) {
    json["enabled"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar::Tickformatstop& Sunburst::Marker::Colorbar::Tickformatstop::name(std::string f) {
    json["name"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar::Tickformatstop& Sunburst::Marker::Colorbar::Tickformatstop::templateitemname(std::string f) {
    json["templateitemname"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar::Tickformatstop& Sunburst::Marker::Colorbar::Tickformatstop::value(std::string f) {
    json["value"] = std::move(f);
    return *this;
}

inline std::string Sunburst::Marker::Colorbar::Title::to_string(Side e) {
    switch(e) {
        case Side::Right: return "right";
        case Side::Top: return "top";
        case Side::Bottom: return "bottom";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

inline Sunburst::Marker::Colorbar::Title& Sunburst::Marker::Colorbar::Title::font(Font f) {
    json["font"] = std::move(f.json);
    return *this;
}
template <typename Callable, typename>
inline Sunburst::Marker::Colorbar::Title& Sunburst::Marker::Colorbar::Title::font(Callable&& c) {
    Font f{};
    std::forward<Callable>(c)(f);
    return font(std::move(f));
}

inline Sunburst::Marker::Colorbar::Title& Sunburst::Marker::Colorbar::Title::side(enum Side f) {
    json["side"] = to_string(f);
    return *this;
}

inline Sunburst::Marker::Colorbar::Title& Sunburst::Marker::Colorbar::Title::text(std::string f) {
    json["text"] = std::move(f);
    return *this;
}

inline std::string Sunburst::Marker::Colorbar::Title::Font::to_string(Style e) {
    switch(e) {
        case Style::Normal: return "normal";
        case Style::Italic: return "italic";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Sunburst::Marker::Colorbar::Title::Font::to_string(Textcase e) {
    switch(e) {
        case Textcase::Normal: return "normal";
        case Textcase::WordCaps: return "word caps";
        case Textcase::Upper: return "upper";
        case Textcase::Lower: return "lower";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Sunburst::Marker::Colorbar::Title::Font::to_string(Variant e) {
    switch(e) {
        case Variant::Normal: return "normal";
        case Variant::SmallCaps: return "small-caps";
        case Variant::AllSmallCaps: return "all-small-caps";
        case Variant::AllPetiteCaps: return "all-petite-caps";
        case Variant::PetiteCaps: return "petite-caps";
        case Variant::Unicase: return "unicase";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

inline Sunburst::Marker::Colorbar::Title::Font& Sunburst::Marker::Colorbar::Title::Font::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Sunburst::Marker::Colorbar::Title::Font& Sunburst::Marker::Colorbar::Title::Font::color(double f) {
    json["color"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar::Title::Font& Sunburst::Marker::Colorbar::Title::Font::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar::Title::Font& Sunburst::Marker::Colorbar::Title::Font::lineposition(std::string f) {
    json["lineposition"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar::Title::Font& Sunburst::Marker::Colorbar::Title::Font::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar::Title::Font& Sunburst::Marker::Colorbar::Title::Font::size(double f) {
    json["size"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Colorbar::Title::Font& Sunburst::Marker::Colorbar::Title::Font::style(enum Style f) {
    json["style"] = to_string(f);
    return *this;
}

inline Sunburst::Marker::Colorbar::Title::Font& Sunburst::Marker::Colorbar::Title::Font::textcase(enum Textcase f) {
    json["textcase"] = to_string(f);
    return *this;
}

inline Sunburst::Marker::Colorbar::Title::Font& Sunburst::Marker::Colorbar::Title::Font::variant(enum Variant f) {
    json["variant"] = to_string(f);
    return *this;
}

inline Sunburst::Marker::Colorbar::Title::Font& Sunburst::Marker::Colorbar::Title::Font::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}


inline Sunburst::Marker::Line& Sunburst::Marker::Line::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Sunburst::Marker::Line& Sunburst::Marker::Line::color(double f) {
    json["color"] = std::move(f);
    return *this;
}
inline Sunburst::Marker::Line& Sunburst::Marker::Line::color(const std::vector<std::string>& f) {
    json["color"] = f;
    return *this;
}
inline Sunburst::Marker::Line& Sunburst::Marker::Line::color(const std::vector<double>& f) {
    json["color"] = f;
    return *this;
}

inline Sunburst::Marker::Line& Sunburst::Marker::Line::colorsrc(std::string f) {
    json["colorsrc"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Line& Sunburst::Marker::Line::width(double f) {
    json["width"] = std::move(f);
    return *this;
}
inline Sunburst::Marker::Line& Sunburst::Marker::Line::width(const std::vector<double>& f) {
    json["width"] = f;
    return *this;
}

inline Sunburst::Marker::Line& Sunburst::Marker::Line::widthsrc(std::string f) {
    json["widthsrc"] = std::move(f);
    return *this;
}

inline std::string Sunburst::Marker::Pattern::to_string(Fillmode e) {
    switch(e) {
        case Fillmode::Replace: return "replace";
        case Fillmode::Overlay: return "overlay";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

inline Sunburst::Marker::Pattern& Sunburst::Marker::Pattern::bgcolor(std::string f) {
    json["bgcolor"] = std::move(f);
    return *this;
}
inline Sunburst::Marker::Pattern& Sunburst::Marker::Pattern::bgcolor(double f) {
    json["bgcolor"] = std::move(f);
    return *this;
}
inline Sunburst::Marker::Pattern& Sunburst::Marker::Pattern::bgcolor(const std::vector<std::string>& f) {
    json["bgcolor"] = f;
    return *this;
}
inline Sunburst::Marker::Pattern& Sunburst::Marker::Pattern::bgcolor(const std::vector<double>& f) {
    json["bgcolor"] = f;
    return *this;
}

inline Sunburst::Marker::Pattern& Sunburst::Marker::Pattern::bgcolorsrc(std::string f) {
    json["bgcolorsrc"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Pattern& Sunburst::Marker::Pattern::fgcolor(std::string f) {
    json["fgcolor"] = std::move(f);
    return *this;
}
inline Sunburst::Marker::Pattern& Sunburst::Marker::Pattern::fgcolor(double f) {
    json["fgcolor"] = std::move(f);
    return *this;
}
inline Sunburst::Marker::Pattern& Sunburst::Marker::Pattern::fgcolor(const std::vector<std::string>& f) {
    json["fgcolor"] = f;
    return *this;
}
inline Sunburst::Marker::Pattern& Sunburst::Marker::Pattern::fgcolor(const std::vector<double>& f) {
    json["fgcolor"] = f;
    return *this;
}

inline Sunburst::Marker::Pattern& Sunburst::Marker::Pattern::fgcolorsrc(std::string f) {
    json["fgcolorsrc"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Pattern& Sunburst::Marker::Pattern::fgopacity(double f) {
    json["fgopacity"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Pattern& Sunburst::Marker::Pattern::fillmode(enum Fillmode f) {
    json["fillmode"] = to_string(f);
    return *this;
}

inline Sunburst::Marker::Pattern& Sunburst::Marker::Pattern::shape(std::string f) {
    json["shape"] = std::move(f);
    return *this;
}
inline Sunburst::Marker::Pattern& Sunburst::Marker::Pattern::shape(const std::vector<std::string>& f) {
    json["shape"] = f;
    return *this;
}

inline Sunburst::Marker::Pattern& Sunburst::Marker::Pattern::shapesrc(std::string f) {
    json["shapesrc"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Pattern& Sunburst::Marker::Pattern::size(double f) {
    json["size"] = std::move(f);
    return *this;
}
inline Sunburst::Marker::Pattern& Sunburst::Marker::Pattern::size(const std::vector<double>& f) {
    json["size"] = f;
    return *this;
}

inline Sunburst::Marker::Pattern& Sunburst::Marker::Pattern::sizesrc(std::string f) {
    json["sizesrc"] = std::move(f);
    return *this;
}

inline Sunburst::Marker::Pattern& Sunburst::Marker::Pattern::solidity(double f) {
    json["solidity"] = std::move(f);
    return *this;
}
inline Sunburst::Marker::Pattern& Sunburst::Marker::Pattern::solidity(const std::vector<double>& f) {
    json["solidity"] = f;
    return *this;
}

inline Sunburst::Marker::Pattern& Sunburst::Marker::Pattern::soliditysrc(std::string f) {
    json["soliditysrc"] = std::move(f);
    return *this;
}

inline std::string Sunburst::Outsidetextfont::to_string(Style e) {
    switch(e) {
        case Style::Normal: return "normal";
        case Style::Italic: return "italic";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Sunburst::Outsidetextfont::to_string(Textcase e) {
    switch(e) {
        case Textcase::Normal: return "normal";
        case Textcase::WordCaps: return "word caps";
        case Textcase::Upper: return "upper";
        case Textcase::Lower: return "lower";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Sunburst::Outsidetextfont::to_string(Variant e) {
    switch(e) {
        case Variant::Normal: return "normal";
        case Variant::SmallCaps: return "small-caps";
        case Variant::AllSmallCaps: return "all-small-caps";
        case Variant::AllPetiteCaps: return "all-petite-caps";
        case Variant::PetiteCaps: return "petite-caps";
        case Variant::Unicase: return "unicase";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

inline Sunburst::Outsidetextfont& Sunburst::Outsidetextfont::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Sunburst::Outsidetextfont& Sunburst::Outsidetextfont::color(double f) {
    json["color"] = std::move(f);
    return *this;
}
inline Sunburst::Outsidetextfont& Sunburst::Outsidetextfont::color(const std::vector<std::string>& f) {
    json["color"] = f;
    return *this;
}
inline Sunburst::Outsidetextfont& Sunburst::Outsidetextfont::color(const std::vector<double>& f) {
    json["color"] = f;
    return *this;
}

inline Sunburst::Outsidetextfont& Sunburst::Outsidetextfont::colorsrc(std::string f) {
    json["colorsrc"] = std::move(f);
    return *this;
}

inline Sunburst::Outsidetextfont& Sunburst::Outsidetextfont::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}
inline Sunburst::Outsidetextfont& Sunburst::Outsidetextfont::family(const std::vector<std::string>& f) {
    json["family"] = f;
    return *this;
}

inline Sunburst::Outsidetextfont& Sunburst::Outsidetextfont::familysrc(std::string f) {
    json["familysrc"] = std::move(f);
    return *this;
}

inline Sunburst::Outsidetextfont& Sunburst::Outsidetextfont::lineposition(std::string f) {
    json["lineposition"] = std::move(f);
    return *this;
}
inline Sunburst::Outsidetextfont& Sunburst::Outsidetextfont::lineposition(const std::vector<std::string>& f) {
    json["lineposition"] = f;
    return *this;
}

inline Sunburst::Outsidetextfont& Sunburst::Outsidetextfont::linepositionsrc(std::string f) {
    json["linepositionsrc"] = std::move(f);
    return *this;
}

inline Sunburst::Outsidetextfont& Sunburst::Outsidetextfont::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}
inline Sunburst::Outsidetextfont& Sunburst::Outsidetextfont::shadow(const std::vector<std::string>& f) {
    json["shadow"] = f;
    return *this;
}

inline Sunburst::Outsidetextfont& Sunburst::Outsidetextfont::shadowsrc(std::string f) {
    json["shadowsrc"] = std::move(f);
    return *this;
}

inline Sunburst::Outsidetextfont& Sunburst::Outsidetextfont::size(double f) {
    json["size"] = std::move(f);
    return *this;
}
inline Sunburst::Outsidetextfont& Sunburst::Outsidetextfont::size(const std::vector<double>& f) {
    json["size"] = f;
    return *this;
}

inline Sunburst::Outsidetextfont& Sunburst::Outsidetextfont::sizesrc(std::string f) {
    json["sizesrc"] = std::move(f);
    return *this;
}

inline Sunburst::Outsidetextfont& Sunburst::Outsidetextfont::style(enum Style f) {
    json["style"] = to_string(f);
    return *this;
}
inline Sunburst::Outsidetextfont& Sunburst::Outsidetextfont::style(const std::vector<enum Style>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["style"] = std::move(stringified);
    return *this;
}

inline Sunburst::Outsidetextfont& Sunburst::Outsidetextfont::stylesrc(std::string f) {
    json["stylesrc"] = std::move(f);
    return *this;
}

inline Sunburst::Outsidetextfont& Sunburst::Outsidetextfont::textcase(enum Textcase f) {
    json["textcase"] = to_string(f);
    return *this;
}
inline Sunburst::Outsidetextfont& Sunburst::Outsidetextfont::textcase(const std::vector<enum Textcase>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["textcase"] = std::move(stringified);
    return *this;
}

inline Sunburst::Outsidetextfont& Sunburst::Outsidetextfont::textcasesrc(std::string f) {
    json["textcasesrc"] = std::move(f);
    return *this;
}

inline Sunburst::Outsidetextfont& Sunburst::Outsidetextfont::variant(enum Variant f) {
    json["variant"] = to_string(f);
    return *this;
}
inline Sunburst::Outsidetextfont& Sunburst::Outsidetextfont::variant(const std::vector<enum Variant>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["variant"] = std::move(stringified);
    return *this;
}

inline Sunburst::Outsidetextfont& Sunburst::Outsidetextfont::variantsrc(std::string f) {
    json["variantsrc"] = std::move(f);
    return *this;
}

inline Sunburst::Outsidetextfont& Sunburst::Outsidetextfont::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}
inline Sunburst::Outsidetextfont& Sunburst::Outsidetextfont::weight(const std::vector<int>& f) {
    json["weight"] = f;
    return *this;
}

inline Sunburst::Outsidetextfont& Sunburst::Outsidetextfont::weightsrc(std::string f) {
    json["weightsrc"] = std::move(f);
    return *this;
}


inline Sunburst::Root& Sunburst::Root::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Sunburst::Root& Sunburst::Root::color(double f) {
    json["color"] = std::move(f);
    return *this;
}


inline Sunburst::Stream& Sunburst::Stream::maxpoints(double f) {
    json["maxpoints"] = std::move(f);
    return *this;
}

inline Sunburst::Stream& Sunburst::Stream::token(std::string f) {
    json["token"] = std::move(f);
    return *this;
}

inline std::string Sunburst::Textfont::to_string(Style e) {
    switch(e) {
        case Style::Normal: return "normal";
        case Style::Italic: return "italic";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Sunburst::Textfont::to_string(Textcase e) {
    switch(e) {
        case Textcase::Normal: return "normal";
        case Textcase::WordCaps: return "word caps";
        case Textcase::Upper: return "upper";
        case Textcase::Lower: return "lower";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}
inline std::string Sunburst::Textfont::to_string(Variant e) {
    switch(e) {
        case Variant::Normal: return "normal";
        case Variant::SmallCaps: return "small-caps";
        case Variant::AllSmallCaps: return "all-small-caps";
        case Variant::AllPetiteCaps: return "all-petite-caps";
        case Variant::PetiteCaps: return "petite-caps";
        case Variant::Unicase: return "unicase";
    }
    // Should be unreachable.
    throw std::invalid_argument{"Unknown enumerator value " + std::to_string(static_cast<int>(e))};
}

inline Sunburst::Textfont& Sunburst::Textfont::color(std::string f) {
    json["color"] = std::move(f);
    return *this;
}
inline Sunburst::Textfont& Sunburst::Textfont::color(double f) {
    json["color"] = std::move(f);
    return *this;
}
inline Sunburst::Textfont& Sunburst::Textfont::color(const std::vector<std::string>& f) {
    json["color"] = f;
    return *this;
}
inline Sunburst::Textfont& Sunburst::Textfont::color(const std::vector<double>& f) {
    json["color"] = f;
    return *this;
}

inline Sunburst::Textfont& Sunburst::Textfont::colorsrc(std::string f) {
    json["colorsrc"] = std::move(f);
    return *this;
}

inline Sunburst::Textfont& Sunburst::Textfont::family(std::string f) {
    json["family"] = std::move(f);
    return *this;
}
inline Sunburst::Textfont& Sunburst::Textfont::family(const std::vector<std::string>& f) {
    json["family"] = f;
    return *this;
}

inline Sunburst::Textfont& Sunburst::Textfont::familysrc(std::string f) {
    json["familysrc"] = std::move(f);
    return *this;
}

inline Sunburst::Textfont& Sunburst::Textfont::lineposition(std::string f) {
    json["lineposition"] = std::move(f);
    return *this;
}
inline Sunburst::Textfont& Sunburst::Textfont::lineposition(const std::vector<std::string>& f) {
    json["lineposition"] = f;
    return *this;
}

inline Sunburst::Textfont& Sunburst::Textfont::linepositionsrc(std::string f) {
    json["linepositionsrc"] = std::move(f);
    return *this;
}

inline Sunburst::Textfont& Sunburst::Textfont::shadow(std::string f) {
    json["shadow"] = std::move(f);
    return *this;
}
inline Sunburst::Textfont& Sunburst::Textfont::shadow(const std::vector<std::string>& f) {
    json["shadow"] = f;
    return *this;
}

inline Sunburst::Textfont& Sunburst::Textfont::shadowsrc(std::string f) {
    json["shadowsrc"] = std::move(f);
    return *this;
}

inline Sunburst::Textfont& Sunburst::Textfont::size(double f) {
    json["size"] = std::move(f);
    return *this;
}
inline Sunburst::Textfont& Sunburst::Textfont::size(const std::vector<double>& f) {
    json["size"] = f;
    return *this;
}

inline Sunburst::Textfont& Sunburst::Textfont::sizesrc(std::string f) {
    json["sizesrc"] = std::move(f);
    return *this;
}

inline Sunburst::Textfont& Sunburst::Textfont::style(enum Style f) {
    json["style"] = to_string(f);
    return *this;
}
inline Sunburst::Textfont& Sunburst::Textfont::style(const std::vector<enum Style>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["style"] = std::move(stringified);
    return *this;
}

inline Sunburst::Textfont& Sunburst::Textfont::stylesrc(std::string f) {
    json["stylesrc"] = std::move(f);
    return *this;
}

inline Sunburst::Textfont& Sunburst::Textfont::textcase(enum Textcase f) {
    json["textcase"] = to_string(f);
    return *this;
}
inline Sunburst::Textfont& Sunburst::Textfont::textcase(const std::vector<enum Textcase>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["textcase"] = std::move(stringified);
    return *this;
}

inline Sunburst::Textfont& Sunburst::Textfont::textcasesrc(std::string f) {
    json["textcasesrc"] = std::move(f);
    return *this;
}

inline Sunburst::Textfont& Sunburst::Textfont::variant(enum Variant f) {
    json["variant"] = to_string(f);
    return *this;
}
inline Sunburst::Textfont& Sunburst::Textfont::variant(const std::vector<enum Variant>& f) {
    std::vector<std::string> stringified(f.size());
    std::transform(f.begin(), f.end(), stringified.begin(), [this](const auto& e){return to_string(e);});
    json["variant"] = std::move(stringified);
    return *this;
}

inline Sunburst::Textfont& Sunburst::Textfont::variantsrc(std::string f) {
    json["variantsrc"] = std::move(f);
    return *this;
}

inline Sunburst::Textfont& Sunburst::Textfont::weight(int f) {
    json["weight"] = std::move(f);
    return *this;
}
inline Sunburst::Textfont& Sunburst::Textfont::weight(const std::vector<int>& f) {
    json["weight"] = f;
    return *this;
}

inline Sunburst::Textfont& Sunburst::Textfont::weightsrc(std::string f) {
    json["weightsrc"] = std::move(f);
    return *this;
}

} // namespace plotlypp

