// Copyright (c) 2025 Jimmy O'Rourke
// Licensed under and subject to the terms of the LICENSE file accompanying this distribution.
// Official repository: https://github.com/jimmyorourke/plotlypp

// Autogenerated by plotlypp/generator, from official Plotly sources.
// See https://plotly.com/graphing-libraries.
// Do not edit, changes may be overwritten!

#pragma once

#include <initializer_list>
#include <string>
#include <type_traits>
#include <utility>
#include <vector>

#include <plotlypp/json.hpp>
#include <plotlypp/trace.hpp>
#include <plotlypp/traits.hpp>

namespace plotlypp {

class Box : public Trace {
 public:
    Box()
    : Trace() {
        json["type"] = "box";
    }
    Box(std::string jsonStr)
    : Trace(std::move(jsonStr)) {}

    enum class Boxmean {
        True,
        Sd,
        False,
    };
    static std::string to_string(Boxmean e);

    enum class Boxpoints {
        All,
        Outliers,
        Suspectedoutliers,
        False,
    };
    static std::string to_string(Boxpoints e);

    enum class Orientation {
        V,
        H,
    };
    static std::string to_string(Orientation e);

    enum class Quartilemethod {
        Linear,
        Exclusive,
        Inclusive,
    };
    static std::string to_string(Quartilemethod e);

    enum class Sizemode {
        Quartiles,
        Sd,
    };
    static std::string to_string(Sizemode e);

    enum class Visible {
        True,
        False,
        Legendonly,
    };
    static std::string to_string(Visible e);

    enum class Xcalendar {
        Chinese,
        Coptic,
        Discworld,
        Ethiopian,
        Gregorian,
        Hebrew,
        Islamic,
        Jalali,
        Julian,
        Mayan,
        Nanakshahi,
        Nepali,
        Persian,
        Taiwan,
        Thai,
        Ummalqura,
    };
    static std::string to_string(Xcalendar e);

    enum class Xperiodalignment {
        Start,
        Middle,
        End,
    };
    static std::string to_string(Xperiodalignment e);

    enum class Ycalendar {
        Chinese,
        Coptic,
        Discworld,
        Ethiopian,
        Gregorian,
        Hebrew,
        Islamic,
        Jalali,
        Julian,
        Mayan,
        Nanakshahi,
        Nepali,
        Persian,
        Taiwan,
        Thai,
        Ummalqura,
    };
    static std::string to_string(Ycalendar e);

    enum class Yperiodalignment {
        Start,
        Middle,
        End,
    };
    static std::string to_string(Yperiodalignment e);

    enum class Hoverinfo {
        X,
        Y,
        Z,
        Text,
        Name,
    };
    enum class HoverinfoExtra {
        All,
        None,
        Skip,
    };
    static std::string to_string(Hoverinfo e);
    static std::string to_string(HoverinfoExtra e);

    enum class Hoveron {
        Boxes,
        Points,
    };
    enum class HoveronExtra {};
    static std::string to_string(Hoveron e);
    static std::string to_string(HoveronExtra e);

    class Hoverlabel;
    class Legendgrouptitle;
    class Line;
    class Marker;
    class Selected;
    class Stream;
    class Unselected;

    // Set several traces linked to the same position axis or matching axes to the same alignmentgroup. This controls
    // whether bars compute their positional range dependently or independently.
    Box& alignmentgroup(std::string f);

    // If *true*, the mean of the box(es)' underlying distribution is drawn as a dashed line inside the box(es). If *sd*
    // the standard deviation is also drawn. Defaults to *true* when `mean` is set. Defaults to *sd* when `sd` is set
    // Otherwise defaults to *false*.
    Box& boxmean(enum Boxmean f);

    // If *outliers*, only the sample points lying outside the whiskers are shown If *suspectedoutliers*, the outlier
    // points are shown and points either less than 4*Q1-3*Q3 or greater than 4*Q3-3*Q1 are highlighted (see
    // `outliercolor`) If *all*, all sample points are shown If *false*, only the box(es) are shown with no sample
    // points Defaults to *suspectedoutliers* when `marker.outliercolor` or `marker.line.outliercolor` is set. Defaults
    // to *all* under the q1/median/q3 signature. Otherwise defaults to *outliers*.
    Box& boxpoints(enum Boxpoints f);

    // Assigns extra data each datum. This may be useful when listening to hover, click and selection events. Note that,
    // *scatter* traces also appends customdata items in the markers DOM elements
    template <typename Range, typename = std::enable_if_t<is_data_array_v<Range>>>
    Box& customdata(Range&& f);

    // Sets the source reference on Chart Studio Cloud for `customdata`.
    Box& customdatasrc(std::string f);

    // Sets the x coordinate step for multi-box traces set using q1/median/q3.
    Box& dx(double f);

    // Sets the y coordinate step for multi-box traces set using q1/median/q3.
    Box& dy(double f);

    // Sets the fill color. Defaults to a half-transparent variant of the line color, marker color, or marker line
    // color, whichever is available.
    Box& fillcolor(std::string f);
    Box& fillcolor(double f);

    // Determines which trace information appear on hover. If `none` or `skip` are set, no information is displayed upon
    // hovering. But, if `none` is set, click and hover events are still fired.
    // - Default: all
    // - Flags: ['x', 'y', 'z', 'text', 'name']
    // - Extras ['all', 'none', 'skip']
    Box& hoverinfo(std::initializer_list<Hoverinfo> flags);
    Box& hoverinfo(HoverinfoExtra extra);

    // Sets the source reference on Chart Studio Cloud for `hoverinfo`.
    Box& hoverinfosrc(std::string f);

    Box& hoverlabel(Hoverlabel f);
    template <typename Callable, typename = std::enable_if_t<std::is_invocable_v<Callable, Hoverlabel&>>>
    Box& hoverlabel(Callable&& c);

    // Do the hover effects highlight individual boxes  or sample points or both?
    // - Default: boxes+points
    // - Flags: ['boxes', 'points']
    Box& hoveron(std::initializer_list<Hoveron> flags);
    Box& hoveron(HoveronExtra extra);

    // Template string used for rendering the information that appear on hover box. Note that this will override
    // `hoverinfo`. Variables are inserted using %{variable}, for example "y: %{y}" as well as %{xother}, {%_xother},
    // {%_xother_}, {%xother_}. When showing info for several points, *xother* will be added to those with different x
    // positions from the first point. An underscore before or after *(x|y)other* will add a space on that side, only
    // when this field is shown. Numbers are formatted using d3-format's syntax %{variable:d3-format}, for example
    // "Price: %{y:$.2f}". https://github.com/d3/d3-format/tree/v1.4.5#d3-format for details on the formatting syntax.
    // Dates are formatted using d3-time-format's syntax %{variable|d3-time-format}, for example "Day:
    // %{2019-01-01|%A}". https://github.com/d3/d3-time-format/tree/v2.2.3#locale_format for details on the date
    // formatting syntax. The variables available in `hovertemplate` are the ones emitted as event data described at
    // this link https://plotly.com/javascript/plotlyjs-events/#event-data. Additionally, every attributes that can be
    // specified per-point (the ones that are `arrayOk: true`) are available.  Anything contained in tag `<extra>` is
    // displayed in the secondary box, for example "<extra>{fullData.name}</extra>". To hide the secondary box
    // completely, use an empty tag `<extra></extra>`.
    Box& hovertemplate(std::string f);
    Box& hovertemplate(const std::vector<std::string>& f);

    // Sets the source reference on Chart Studio Cloud for `hovertemplate`.
    Box& hovertemplatesrc(std::string f);

    // Same as `text`.
    Box& hovertext(std::string f);
    Box& hovertext(const std::vector<std::string>& f);

    // Sets the source reference on Chart Studio Cloud for `hovertext`.
    Box& hovertextsrc(std::string f);

    // Assigns id labels to each datum. These ids for object constancy of data points during animation. Should be an
    // array of strings, not numbers or any other type.
    template <typename Range, typename = std::enable_if_t<is_data_array_v<Range>>>
    Box& ids(Range&& f);

    // Sets the source reference on Chart Studio Cloud for `ids`.
    Box& idssrc(std::string f);

    // Sets the amount of jitter in the sample points drawn. If *0*, the sample points align along the distribution
    // axis. If *1*, the sample points are drawn in a random jitter of width equal to the width of the box(es).
    Box& jitter(double f);

    // Sets the reference to a legend to show this trace in. References to these legends are *legend*, *legend2*,
    // *legend3*, etc. Settings for these legends are set in the layout, under `layout.legend`, `layout.legend2`, etc.
    Box& legend(std::string f);

    // Sets the legend group for this trace. Traces and shapes part of the same legend group hide/show at the same time
    // when toggling legend items.
    Box& legendgroup(std::string f);

    Box& legendgrouptitle(Legendgrouptitle f);
    template <typename Callable, typename = std::enable_if_t<std::is_invocable_v<Callable, Legendgrouptitle&>>>
    Box& legendgrouptitle(Callable&& c);

    // Sets the legend rank for this trace. Items and groups with smaller ranks are presented on top/left side while
    // with *reversed* `legend.traceorder` they are on bottom/right side. The default legendrank is 1000, so that you
    // can use ranks less than 1000 to place certain items before all unranked items, and ranks greater than 1000 to go
    // after all unranked items. When having unranked or equal rank items shapes would be displayed after traces i.e.
    // according to their order in data and layout.
    Box& legendrank(double f);

    // Sets the width (in px or fraction) of the legend for this trace.
    Box& legendwidth(double f);

    Box& line(Line f);
    template <typename Callable, typename = std::enable_if_t<std::is_invocable_v<Callable, Line&>>>
    Box& line(Callable&& c);

    // Sets the lower fence values. There should be as many items as the number of boxes desired. This attribute has
    // effect only under the q1/median/q3 signature. If `lowerfence` is not provided but a sample (in `y` or `x`) is
    // set, we compute the lower as the last sample point below 1.5 times the IQR.
    template <typename Range, typename = std::enable_if_t<is_data_array_v<Range>>>
    Box& lowerfence(Range&& f);

    // Sets the source reference on Chart Studio Cloud for `lowerfence`.
    Box& lowerfencesrc(std::string f);

    Box& marker(Marker f);
    template <typename Callable, typename = std::enable_if_t<std::is_invocable_v<Callable, Marker&>>>
    Box& marker(Callable&& c);

    // Sets the mean values. There should be as many items as the number of boxes desired. This attribute has effect
    // only under the q1/median/q3 signature. If `mean` is not provided but a sample (in `y` or `x`) is set, we compute
    // the mean for each box using the sample values.
    template <typename Range, typename = std::enable_if_t<is_data_array_v<Range>>>
    Box& mean(Range&& f);

    // Sets the source reference on Chart Studio Cloud for `mean`.
    Box& meansrc(std::string f);

    // Sets the median values. There should be as many items as the number of boxes desired.
    template <typename Range, typename = std::enable_if_t<is_data_array_v<Range>>>
    Box& median(Range&& f);

    // Sets the source reference on Chart Studio Cloud for `median`.
    Box& mediansrc(std::string f);

    // Assigns extra meta information associated with this trace that can be used in various text attributes. Attributes
    // such as trace `name`, graph, axis and colorbar `title.text`, annotation `text` `rangeselector`, `updatemenues`
    // and `sliders` `label` text all support `meta`. To access the trace `meta` values in an attribute in the same
    // trace, simply use `%{meta[i]}` where `i` is the index or key of the `meta` item in question. To access trace
    // `meta` in layout attributes, use `%{data[n[.meta[i]}` where `i` is the index or key of the `meta` and `n` is the
    // trace index.
    template <typename T>
    Box& meta(T f);
    template <typename T>
    Box& meta(const std::vector<T>& f);

    // Sets the source reference on Chart Studio Cloud for `meta`.
    Box& metasrc(std::string f);

    // Sets the trace name. The trace name appears as the legend item and on hover. For box traces, the name will also
    // be used for the position coordinate, if `x` and `x0` (`y` and `y0` if horizontal) are missing and the position
    // axis is categorical
    Box& name(std::string f);

    // Determines whether or not notches are drawn. Notches displays a confidence interval around the median. We compute
    // the confidence interval as median +/- 1.57 * IQR / sqrt(N), where IQR is the interquartile range and N is the
    // sample size. If two boxes' notches do not overlap there is 95% confidence their medians differ. See
    // https://sites.google.com/site/davidsstatistics/home/notched-box-plots for more info. Defaults to *false* unless
    // `notchwidth` or `notchspan` is set.
    Box& notched(bool f);

    // Sets the notch span from the boxes' `median` values. There should be as many items as the number of boxes
    // desired. This attribute has effect only under the q1/median/q3 signature. If `notchspan` is not provided but a
    // sample (in `y` or `x`) is set, we compute it as 1.57 * IQR / sqrt(N), where N is the sample size.
    template <typename Range, typename = std::enable_if_t<is_data_array_v<Range>>>
    Box& notchspan(Range&& f);

    // Sets the source reference on Chart Studio Cloud for `notchspan`.
    Box& notchspansrc(std::string f);

    // Sets the width of the notches relative to the box' width. For example, with 0, the notches are as wide as the
    // box(es).
    Box& notchwidth(double f);

    // Set several traces linked to the same position axis or matching axes to the same offsetgroup where bars of the
    // same position coordinate will line up.
    Box& offsetgroup(std::string f);

    // Sets the opacity of the trace.
    Box& opacity(double f);

    // Sets the orientation of the box(es). If *v* (*h*), the distribution is visualized along the vertical
    // (horizontal).
    Box& orientation(enum Orientation f);

    // Sets the position of the sample points in relation to the box(es). If *0*, the sample points are places over the
    // center of the box(es). Positive (negative) values correspond to positions to the right (left) for vertical boxes
    // and above (below) for horizontal boxes
    Box& pointpos(double f);

    // Sets the Quartile 1 values. There should be as many items as the number of boxes desired.
    template <typename Range, typename = std::enable_if_t<is_data_array_v<Range>>>
    Box& q1(Range&& f);

    // Sets the source reference on Chart Studio Cloud for `q1`.
    Box& q1src(std::string f);

    // Sets the Quartile 3 values. There should be as many items as the number of boxes desired.
    template <typename Range, typename = std::enable_if_t<is_data_array_v<Range>>>
    Box& q3(Range&& f);

    // Sets the source reference on Chart Studio Cloud for `q3`.
    Box& q3src(std::string f);

    // Sets the method used to compute the sample's Q1 and Q3 quartiles. The *linear* method uses the 25th percentile
    // for Q1 and 75th percentile for Q3 as computed using method #10 (listed on
    // http://jse.amstat.org/v14n3/langford.html). The *exclusive* method uses the median to divide the ordered dataset
    // into two halves if the sample is odd, it does not include the median in either half - Q1 is then the median of
    // the lower half and Q3 the median of the upper half. The *inclusive* method also uses the median to divide the
    // ordered dataset into two halves but if the sample is odd, it includes the median in both halves - Q1 is then the
    // median of the lower half and Q3 the median of the upper half.
    // - Default: linear
    Box& quartilemethod(enum Quartilemethod f);

    // Sets the standard deviation values. There should be as many items as the number of boxes desired. This attribute
    // has effect only under the q1/median/q3 signature. If `sd` is not provided but a sample (in `y` or `x`) is set, we
    // compute the standard deviation for each box using the sample values.
    template <typename Range, typename = std::enable_if_t<is_data_array_v<Range>>>
    Box& sd(Range&& f);

    // Scales the box size when sizemode=sd Allowing boxes to be drawn across any stddev range For example 1-stddev,
    // 3-stddev, 5-stddev
    Box& sdmultiple(double f);

    // Sets the source reference on Chart Studio Cloud for `sd`.
    Box& sdsrc(std::string f);

    Box& selected(Selected f);
    template <typename Callable, typename = std::enable_if_t<std::is_invocable_v<Callable, Selected&>>>
    Box& selected(Callable&& c);

    // Array containing integer indices of selected points. Has an effect only for traces that support selections. Note
    // that an empty array means an empty selection where the `unselected` are turned on for all points, whereas, any
    // other non-array values means no selection all where the `selected` and `unselected` styles have no effect.
    template <typename T>
    Box& selectedpoints(T f);

    // Determines whether or not an item corresponding to this trace is shown in the legend.
    Box& showlegend(bool f);

    // Determines whether or not whiskers are visible. Defaults to true for `sizemode` *quartiles*, false for *sd*.
    Box& showwhiskers(bool f);

    // Sets the upper and lower bound for the boxes quartiles means box is drawn between Q1 and Q3 SD means the box is
    // drawn between Mean +- Standard Deviation Argument sdmultiple (default 1) to scale the box size So it could be
    // drawn 1-stddev, 3-stddev etc
    // - Default: quartiles
    Box& sizemode(enum Sizemode f);

    Box& stream(Stream f);
    template <typename Callable, typename = std::enable_if_t<std::is_invocable_v<Callable, Stream&>>>
    Box& stream(Callable&& c);

    // Sets the text elements associated with each sample value. If a single string, the same string appears over all
    // the data points. If an array of string, the items are mapped in order to the this trace's (x,y) coordinates. To
    // be seen, trace `hoverinfo` must contain a *text* flag.
    Box& text(std::string f);
    Box& text(const std::vector<std::string>& f);

    // Sets the source reference on Chart Studio Cloud for `text`.
    Box& textsrc(std::string f);

    // Assign an id to this trace, Use this to provide object constancy between traces during animations and
    // transitions.
    Box& uid(std::string f);

    // Controls persistence of some user-driven changes to the trace: `constraintrange` in `parcoords` traces, as well
    // as some `editable: true` modifications such as `name` and `colorbar.title`. Defaults to `layout.uirevision`. Note
    // that other user-driven trace attribute changes are controlled by `layout` attributes: `trace.visible` is
    // controlled by `layout.legend.uirevision`, `selectedpoints` is controlled by `layout.selectionrevision`, and
    // `colorbar.(x|y)` (accessible with `config: {editable: true}`) is controlled by `layout.editrevision`. Trace
    // changes are tracked by `uid`, which only falls back on trace index if no `uid` is provided. So if your app can
    // add/remove traces before the end of the `data` array, such that the same trace has a different index, you can
    // still preserve user-driven changes if you give each trace a `uid` that stays with it as it moves.
    template <typename T>
    Box& uirevision(T f);

    Box& unselected(Unselected f);
    template <typename Callable, typename = std::enable_if_t<std::is_invocable_v<Callable, Unselected&>>>
    Box& unselected(Callable&& c);

    // Sets the upper fence values. There should be as many items as the number of boxes desired. This attribute has
    // effect only under the q1/median/q3 signature. If `upperfence` is not provided but a sample (in `y` or `x`) is
    // set, we compute the upper as the last sample point above 1.5 times the IQR.
    template <typename Range, typename = std::enable_if_t<is_data_array_v<Range>>>
    Box& upperfence(Range&& f);

    // Sets the source reference on Chart Studio Cloud for `upperfence`.
    Box& upperfencesrc(std::string f);

    // Determines whether or not this trace is visible. If *legendonly*, the trace is not drawn, but can appear as a
    // legend item (provided that the legend itself is visible).
    // - Default: True
    Box& visible(enum Visible f);

    // Sets the width of the whiskers relative to the box' width. For example, with 1, the whiskers are as wide as the
    // box(es).
    Box& whiskerwidth(double f);

    // Sets the width of the box in data coordinate If *0* (default value) the width is automatically selected based on
    // the positions of other box traces in the same subplot.
    Box& width(double f);

    // Sets the x sample data or coordinates. See overview for more info.
    template <typename Range, typename = std::enable_if_t<is_data_array_v<Range>>>
    Box& x(Range&& f);

    // Sets the x coordinate for single-box traces or the starting coordinate for multi-box traces set using
    // q1/median/q3. See overview for more info.
    template <typename T>
    Box& x0(T f);

    // Sets a reference between this trace's x coordinates and a 2D cartesian x axis. If *x* (the default value), the x
    // coordinates refer to `layout.xaxis`. If *x2*, the x coordinates refer to `layout.xaxis2`, and so on.
    Box& xaxis(std::string f);

    // Sets the calendar system to use with `x` date data.
    // - Default: gregorian
    Box& xcalendar(enum Xcalendar f);

    // Sets the hover text formatting rulefor `x`  using d3 formatting mini-languages which are very similar to those in
    // Python. For numbers, see: https://github.com/d3/d3-format/tree/v1.4.5#d3-format. And for dates see:
    // https://github.com/d3/d3-time-format/tree/v2.2.3#locale_format. We add two items to d3's date formatter: *%h* for
    // half of the year as a decimal number as well as *%{n}f* for fractional seconds with n digits. For example,
    // *2016-10-13 09:15:23.456* with tickformat *%H~%M~%S.%2f* would display *09~15~23.46*By default the values are
    // formatted using `xaxis.hoverformat`.
    Box& xhoverformat(std::string f);

    // Only relevant when the axis `type` is *date*. Sets the period positioning in milliseconds or *M<n>* on the x
    // axis. Special values in the form of *M<n>* could be used to declare the number of months. In this case `n` must
    // be a positive integer.
    template <typename T>
    Box& xperiod(T f);

    // Only relevant when the axis `type` is *date*. Sets the base for period positioning in milliseconds or date string
    // on the x0 axis. When `x0period` is round number of weeks, the `x0period0` by default would be on a Sunday i.e.
    // 2000-01-02, otherwise it would be at 2000-01-01.
    template <typename T>
    Box& xperiod0(T f);

    // Only relevant when the axis `type` is *date*. Sets the alignment of data points on the x axis.
    // - Default: middle
    Box& xperiodalignment(enum Xperiodalignment f);

    // Sets the source reference on Chart Studio Cloud for `x`.
    Box& xsrc(std::string f);

    // Sets the y sample data or coordinates. See overview for more info.
    template <typename Range, typename = std::enable_if_t<is_data_array_v<Range>>>
    Box& y(Range&& f);

    // Sets the y coordinate for single-box traces or the starting coordinate for multi-box traces set using
    // q1/median/q3. See overview for more info.
    template <typename T>
    Box& y0(T f);

    // Sets a reference between this trace's y coordinates and a 2D cartesian y axis. If *y* (the default value), the y
    // coordinates refer to `layout.yaxis`. If *y2*, the y coordinates refer to `layout.yaxis2`, and so on.
    Box& yaxis(std::string f);

    // Sets the calendar system to use with `y` date data.
    // - Default: gregorian
    Box& ycalendar(enum Ycalendar f);

    // Sets the hover text formatting rulefor `y`  using d3 formatting mini-languages which are very similar to those in
    // Python. For numbers, see: https://github.com/d3/d3-format/tree/v1.4.5#d3-format. And for dates see:
    // https://github.com/d3/d3-time-format/tree/v2.2.3#locale_format. We add two items to d3's date formatter: *%h* for
    // half of the year as a decimal number as well as *%{n}f* for fractional seconds with n digits. For example,
    // *2016-10-13 09:15:23.456* with tickformat *%H~%M~%S.%2f* would display *09~15~23.46*By default the values are
    // formatted using `yaxis.hoverformat`.
    Box& yhoverformat(std::string f);

    // Only relevant when the axis `type` is *date*. Sets the period positioning in milliseconds or *M<n>* on the y
    // axis. Special values in the form of *M<n>* could be used to declare the number of months. In this case `n` must
    // be a positive integer.
    template <typename T>
    Box& yperiod(T f);

    // Only relevant when the axis `type` is *date*. Sets the base for period positioning in milliseconds or date string
    // on the y0 axis. When `y0period` is round number of weeks, the `y0period0` by default would be on a Sunday i.e.
    // 2000-01-02, otherwise it would be at 2000-01-01.
    template <typename T>
    Box& yperiod0(T f);

    // Only relevant when the axis `type` is *date*. Sets the alignment of data points on the y axis.
    // - Default: middle
    Box& yperiodalignment(enum Yperiodalignment f);

    // Sets the source reference on Chart Studio Cloud for `y`.
    Box& ysrc(std::string f);

    // Sets the layer on which this trace is displayed, relative to other SVG traces on the same subplot. SVG traces
    // with higher `zorder` appear in front of those with lower `zorder`.
    Box& zorder(int f);
};

class Box::Hoverlabel {
 public:
    Hoverlabel() = default;
    Hoverlabel(std::string jsonStr)
    : json(parse(std::move(jsonStr))) {}

    enum class Align {
        Left,
        Right,
        Auto,
    };
    static std::string to_string(Align e);

    // Sets the font used in hover labels.
    class Font;

    // Sets the horizontal alignment of the text content within hover label box. Has an effect only if the hover label
    // text spans more two or more lines
    // - Default: auto
    Box::Hoverlabel& align(enum Align f);
    Box::Hoverlabel& align(const std::vector<enum Align>& f);

    // Sets the source reference on Chart Studio Cloud for `align`.
    Box::Hoverlabel& alignsrc(std::string f);

    // Sets the background color of the hover labels for this trace
    Box::Hoverlabel& bgcolor(std::string f);
    Box::Hoverlabel& bgcolor(double f);
    Box::Hoverlabel& bgcolor(const std::vector<std::string>& f);
    Box::Hoverlabel& bgcolor(const std::vector<double>& f);

    // Sets the source reference on Chart Studio Cloud for `bgcolor`.
    Box::Hoverlabel& bgcolorsrc(std::string f);

    // Sets the border color of the hover labels for this trace.
    Box::Hoverlabel& bordercolor(std::string f);
    Box::Hoverlabel& bordercolor(double f);
    Box::Hoverlabel& bordercolor(const std::vector<std::string>& f);
    Box::Hoverlabel& bordercolor(const std::vector<double>& f);

    // Sets the source reference on Chart Studio Cloud for `bordercolor`.
    Box::Hoverlabel& bordercolorsrc(std::string f);

    // Sets the font used in hover labels.
    Box::Hoverlabel& font(Font f);
    template <typename Callable, typename = std::enable_if_t<std::is_invocable_v<Callable, Font&>>>
    Box::Hoverlabel& font(Callable&& c);

    // Sets the default length (in number of characters) of the trace name in the hover labels for all traces. -1 shows
    // the whole name regardless of length. 0-3 shows the first 0-3 characters, and an integer >3 will show the whole
    // name if it is less than that many characters, but if it is longer, will truncate to `namelength - 3` characters
    // and add an ellipsis.
    Box::Hoverlabel& namelength(int f);
    Box::Hoverlabel& namelength(const std::vector<int>& f);

    // Sets the source reference on Chart Studio Cloud for `namelength`.
    Box::Hoverlabel& namelengthsrc(std::string f);

    // Advanced users may modify the JSON representation directly, at their own peril!
    Json json{};
};

// Sets the font used in hover labels.
class Box::Hoverlabel::Font {
 public:
    Font() = default;
    Font(std::string jsonStr)
    : json(parse(std::move(jsonStr))) {}

    enum class Style {
        Normal,
        Italic,
    };
    static std::string to_string(Style e);

    enum class Textcase {
        Normal,
        WordCaps,
        Upper,
        Lower,
    };
    static std::string to_string(Textcase e);

    enum class Variant {
        Normal,
        SmallCaps,
        AllSmallCaps,
        AllPetiteCaps,
        PetiteCaps,
        Unicase,
    };
    static std::string to_string(Variant e);

    enum class Lineposition {
        Under,
        Over,
        Through,
    };
    enum class LinepositionExtra {
        None,
    };
    static std::string to_string(Lineposition e);
    static std::string to_string(LinepositionExtra e);

    Box::Hoverlabel::Font& color(std::string f);
    Box::Hoverlabel::Font& color(double f);
    Box::Hoverlabel::Font& color(const std::vector<std::string>& f);
    Box::Hoverlabel::Font& color(const std::vector<double>& f);

    // Sets the source reference on Chart Studio Cloud for `color`.
    Box::Hoverlabel::Font& colorsrc(std::string f);

    // HTML font family - the typeface that will be applied by the web browser. The web browser will only be able to
    // apply a font if it is available on the system which it operates. Provide multiple font families, separated by
    // commas, to indicate the preference in which to apply fonts if they aren't available on the system. The Chart
    // Studio Cloud (at https://chart-studio.plotly.com or on-premise) generates images on a server, where only a select
    // number of fonts are installed and supported. These include *Arial*, *Balto*, *Courier New*, *Droid Sans*, *Droid
    // Serif*, *Droid Sans Mono*, *Gravitas One*, *Old Standard TT*, *Open Sans*, *Overpass*, *PT Sans Narrow*,
    // *Raleway*, *Times New Roman*.
    Box::Hoverlabel::Font& family(std::string f);
    Box::Hoverlabel::Font& family(const std::vector<std::string>& f);

    // Sets the source reference on Chart Studio Cloud for `family`.
    Box::Hoverlabel::Font& familysrc(std::string f);

    // Sets the kind of decoration line(s) with text, such as an *under*, *over* or *through* as well as combinations
    // e.g. *under+over*, etc.
    // - Default: none
    // - Flags: ['under', 'over', 'through']
    // - Extras ['none']
    Box::Hoverlabel::Font& lineposition(std::initializer_list<Lineposition> flags);
    Box::Hoverlabel::Font& lineposition(LinepositionExtra extra);

    // Sets the source reference on Chart Studio Cloud for `lineposition`.
    Box::Hoverlabel::Font& linepositionsrc(std::string f);

    // Sets the shape and color of the shadow behind text. *auto* places minimal shadow and applies contrast text font
    // color. See https://developer.mozilla.org/en-US/docs/Web/CSS/text-shadow for additional options.
    Box::Hoverlabel::Font& shadow(std::string f);
    Box::Hoverlabel::Font& shadow(const std::vector<std::string>& f);

    // Sets the source reference on Chart Studio Cloud for `shadow`.
    Box::Hoverlabel::Font& shadowsrc(std::string f);

    Box::Hoverlabel::Font& size(double f);
    Box::Hoverlabel::Font& size(const std::vector<double>& f);

    // Sets the source reference on Chart Studio Cloud for `size`.
    Box::Hoverlabel::Font& sizesrc(std::string f);

    // Sets whether a font should be styled with a normal or italic face from its family.
    // - Default: normal
    Box::Hoverlabel::Font& style(enum Style f);
    Box::Hoverlabel::Font& style(const std::vector<enum Style>& f);

    // Sets the source reference on Chart Studio Cloud for `style`.
    Box::Hoverlabel::Font& stylesrc(std::string f);

    // Sets capitalization of text. It can be used to make text appear in all-uppercase or all-lowercase, or with each
    // word capitalized.
    // - Default: normal
    Box::Hoverlabel::Font& textcase(enum Textcase f);
    Box::Hoverlabel::Font& textcase(const std::vector<enum Textcase>& f);

    // Sets the source reference on Chart Studio Cloud for `textcase`.
    Box::Hoverlabel::Font& textcasesrc(std::string f);

    // Sets the variant of the font.
    // - Default: normal
    Box::Hoverlabel::Font& variant(enum Variant f);
    Box::Hoverlabel::Font& variant(const std::vector<enum Variant>& f);

    // Sets the source reference on Chart Studio Cloud for `variant`.
    Box::Hoverlabel::Font& variantsrc(std::string f);

    // Sets the weight (or boldness) of the font.
    Box::Hoverlabel::Font& weight(int f);
    Box::Hoverlabel::Font& weight(const std::vector<int>& f);

    // Sets the source reference on Chart Studio Cloud for `weight`.
    Box::Hoverlabel::Font& weightsrc(std::string f);

    // Advanced users may modify the JSON representation directly, at their own peril!
    Json json{};
};

class Box::Legendgrouptitle {
 public:
    Legendgrouptitle() = default;
    Legendgrouptitle(std::string jsonStr)
    : json(parse(std::move(jsonStr))) {}

    // Sets this legend group's title font.
    class Font;

    // Sets this legend group's title font.
    Box::Legendgrouptitle& font(Font f);
    template <typename Callable, typename = std::enable_if_t<std::is_invocable_v<Callable, Font&>>>
    Box::Legendgrouptitle& font(Callable&& c);

    // Sets the title of the legend group.
    Box::Legendgrouptitle& text(std::string f);

    // Advanced users may modify the JSON representation directly, at their own peril!
    Json json{};
};

// Sets this legend group's title font.
class Box::Legendgrouptitle::Font {
 public:
    Font() = default;
    Font(std::string jsonStr)
    : json(parse(std::move(jsonStr))) {}

    enum class Style {
        Normal,
        Italic,
    };
    static std::string to_string(Style e);

    enum class Textcase {
        Normal,
        WordCaps,
        Upper,
        Lower,
    };
    static std::string to_string(Textcase e);

    enum class Variant {
        Normal,
        SmallCaps,
        AllSmallCaps,
        AllPetiteCaps,
        PetiteCaps,
        Unicase,
    };
    static std::string to_string(Variant e);

    enum class Lineposition {
        Under,
        Over,
        Through,
    };
    enum class LinepositionExtra {
        None,
    };
    static std::string to_string(Lineposition e);
    static std::string to_string(LinepositionExtra e);

    Box::Legendgrouptitle::Font& color(std::string f);
    Box::Legendgrouptitle::Font& color(double f);

    // HTML font family - the typeface that will be applied by the web browser. The web browser will only be able to
    // apply a font if it is available on the system which it operates. Provide multiple font families, separated by
    // commas, to indicate the preference in which to apply fonts if they aren't available on the system. The Chart
    // Studio Cloud (at https://chart-studio.plotly.com or on-premise) generates images on a server, where only a select
    // number of fonts are installed and supported. These include *Arial*, *Balto*, *Courier New*, *Droid Sans*, *Droid
    // Serif*, *Droid Sans Mono*, *Gravitas One*, *Old Standard TT*, *Open Sans*, *Overpass*, *PT Sans Narrow*,
    // *Raleway*, *Times New Roman*.
    Box::Legendgrouptitle::Font& family(std::string f);

    // Sets the kind of decoration line(s) with text, such as an *under*, *over* or *through* as well as combinations
    // e.g. *under+over*, etc.
    // - Default: none
    // - Flags: ['under', 'over', 'through']
    // - Extras ['none']
    Box::Legendgrouptitle::Font& lineposition(std::initializer_list<Lineposition> flags);
    Box::Legendgrouptitle::Font& lineposition(LinepositionExtra extra);

    // Sets the shape and color of the shadow behind text. *auto* places minimal shadow and applies contrast text font
    // color. See https://developer.mozilla.org/en-US/docs/Web/CSS/text-shadow for additional options.
    Box::Legendgrouptitle::Font& shadow(std::string f);

    Box::Legendgrouptitle::Font& size(double f);

    // Sets whether a font should be styled with a normal or italic face from its family.
    // - Default: normal
    Box::Legendgrouptitle::Font& style(enum Style f);

    // Sets capitalization of text. It can be used to make text appear in all-uppercase or all-lowercase, or with each
    // word capitalized.
    // - Default: normal
    Box::Legendgrouptitle::Font& textcase(enum Textcase f);

    // Sets the variant of the font.
    // - Default: normal
    Box::Legendgrouptitle::Font& variant(enum Variant f);

    // Sets the weight (or boldness) of the font.
    Box::Legendgrouptitle::Font& weight(int f);

    // Advanced users may modify the JSON representation directly, at their own peril!
    Json json{};
};

class Box::Line {
 public:
    Line() = default;
    Line(std::string jsonStr)
    : json(parse(std::move(jsonStr))) {}

    // Sets the color of line bounding the box(es).
    Box::Line& color(std::string f);
    Box::Line& color(double f);

    // Sets the width (in px) of line bounding the box(es).
    Box::Line& width(double f);

    // Advanced users may modify the JSON representation directly, at their own peril!
    Json json{};
};

class Box::Marker {
 public:
    Marker() = default;
    Marker(std::string jsonStr)
    : json(parse(std::move(jsonStr))) {}

    enum class Symbol {
        Num_0,
        Circle,
        Num_100,
        CircleOpen,
        Num_200,
        CircleDot,
        Num_300,
        CircleOpenDot,
        Num_1,
        Square,
        Num_101,
        SquareOpen,
        Num_201,
        SquareDot,
        Num_301,
        SquareOpenDot,
        Num_2,
        Diamond,
        Num_102,
        DiamondOpen,
        Num_202,
        DiamondDot,
        Num_302,
        DiamondOpenDot,
        Num_3,
        Cross,
        Num_103,
        CrossOpen,
        Num_203,
        CrossDot,
        Num_303,
        CrossOpenDot,
        Num_4,
        X,
        Num_104,
        XOpen,
        Num_204,
        XDot,
        Num_304,
        XOpenDot,
        Num_5,
        TriangleUp,
        Num_105,
        TriangleUpOpen,
        Num_205,
        TriangleUpDot,
        Num_305,
        TriangleUpOpenDot,
        Num_6,
        TriangleDown,
        Num_106,
        TriangleDownOpen,
        Num_206,
        TriangleDownDot,
        Num_306,
        TriangleDownOpenDot,
        Num_7,
        TriangleLeft,
        Num_107,
        TriangleLeftOpen,
        Num_207,
        TriangleLeftDot,
        Num_307,
        TriangleLeftOpenDot,
        Num_8,
        TriangleRight,
        Num_108,
        TriangleRightOpen,
        Num_208,
        TriangleRightDot,
        Num_308,
        TriangleRightOpenDot,
        Num_9,
        TriangleNe,
        Num_109,
        TriangleNeOpen,
        Num_209,
        TriangleNeDot,
        Num_309,
        TriangleNeOpenDot,
        Num_10,
        TriangleSe,
        Num_110,
        TriangleSeOpen,
        Num_210,
        TriangleSeDot,
        Num_310,
        TriangleSeOpenDot,
        Num_11,
        TriangleSw,
        Num_111,
        TriangleSwOpen,
        Num_211,
        TriangleSwDot,
        Num_311,
        TriangleSwOpenDot,
        Num_12,
        TriangleNw,
        Num_112,
        TriangleNwOpen,
        Num_212,
        TriangleNwDot,
        Num_312,
        TriangleNwOpenDot,
        Num_13,
        Pentagon,
        Num_113,
        PentagonOpen,
        Num_213,
        PentagonDot,
        Num_313,
        PentagonOpenDot,
        Num_14,
        Hexagon,
        Num_114,
        HexagonOpen,
        Num_214,
        HexagonDot,
        Num_314,
        HexagonOpenDot,
        Num_15,
        Hexagon2,
        Num_115,
        Hexagon2Open,
        Num_215,
        Hexagon2Dot,
        Num_315,
        Hexagon2OpenDot,
        Num_16,
        Octagon,
        Num_116,
        OctagonOpen,
        Num_216,
        OctagonDot,
        Num_316,
        OctagonOpenDot,
        Num_17,
        Star,
        Num_117,
        StarOpen,
        Num_217,
        StarDot,
        Num_317,
        StarOpenDot,
        Num_18,
        Hexagram,
        Num_118,
        HexagramOpen,
        Num_218,
        HexagramDot,
        Num_318,
        HexagramOpenDot,
        Num_19,
        StarTriangleUp,
        Num_119,
        StarTriangleUpOpen,
        Num_219,
        StarTriangleUpDot,
        Num_319,
        StarTriangleUpOpenDot,
        Num_20,
        StarTriangleDown,
        Num_120,
        StarTriangleDownOpen,
        Num_220,
        StarTriangleDownDot,
        Num_320,
        StarTriangleDownOpenDot,
        Num_21,
        StarSquare,
        Num_121,
        StarSquareOpen,
        Num_221,
        StarSquareDot,
        Num_321,
        StarSquareOpenDot,
        Num_22,
        StarDiamond,
        Num_122,
        StarDiamondOpen,
        Num_222,
        StarDiamondDot,
        Num_322,
        StarDiamondOpenDot,
        Num_23,
        DiamondTall,
        Num_123,
        DiamondTallOpen,
        Num_223,
        DiamondTallDot,
        Num_323,
        DiamondTallOpenDot,
        Num_24,
        DiamondWide,
        Num_124,
        DiamondWideOpen,
        Num_224,
        DiamondWideDot,
        Num_324,
        DiamondWideOpenDot,
        Num_25,
        Hourglass,
        Num_125,
        HourglassOpen,
        Num_26,
        Bowtie,
        Num_126,
        BowtieOpen,
        Num_27,
        CircleCross,
        Num_127,
        CircleCrossOpen,
        Num_28,
        CircleX,
        Num_128,
        CircleXOpen,
        Num_29,
        SquareCross,
        Num_129,
        SquareCrossOpen,
        Num_30,
        SquareX,
        Num_130,
        SquareXOpen,
        Num_31,
        DiamondCross,
        Num_131,
        DiamondCrossOpen,
        Num_32,
        DiamondX,
        Num_132,
        DiamondXOpen,
        Num_33,
        CrossThin,
        Num_133,
        CrossThinOpen,
        Num_34,
        XThin,
        Num_134,
        XThinOpen,
        Num_35,
        Asterisk,
        Num_135,
        AsteriskOpen,
        Num_36,
        Hash,
        Num_136,
        HashOpen,
        Num_236,
        HashDot,
        Num_336,
        HashOpenDot,
        Num_37,
        YUp,
        Num_137,
        YUpOpen,
        Num_38,
        YDown,
        Num_138,
        YDownOpen,
        Num_39,
        YLeft,
        Num_139,
        YLeftOpen,
        Num_40,
        YRight,
        Num_140,
        YRightOpen,
        Num_41,
        LineEw,
        Num_141,
        LineEwOpen,
        Num_42,
        LineNs,
        Num_142,
        LineNsOpen,
        Num_43,
        LineNe,
        Num_143,
        LineNeOpen,
        Num_44,
        LineNw,
        Num_144,
        LineNwOpen,
        Num_45,
        ArrowUp,
        Num_145,
        ArrowUpOpen,
        Num_46,
        ArrowDown,
        Num_146,
        ArrowDownOpen,
        Num_47,
        ArrowLeft,
        Num_147,
        ArrowLeftOpen,
        Num_48,
        ArrowRight,
        Num_148,
        ArrowRightOpen,
        Num_49,
        ArrowBarUp,
        Num_149,
        ArrowBarUpOpen,
        Num_50,
        ArrowBarDown,
        Num_150,
        ArrowBarDownOpen,
        Num_51,
        ArrowBarLeft,
        Num_151,
        ArrowBarLeftOpen,
        Num_52,
        ArrowBarRight,
        Num_152,
        ArrowBarRightOpen,
        Num_53,
        Arrow,
        Num_153,
        ArrowOpen,
        Num_54,
        ArrowWide,
        Num_154,
        ArrowWideOpen,
    };
    static std::string to_string(Symbol e);

    class Line;

    // Sets the marker angle in respect to `angleref`.
    Box::Marker& angle(double f);

    // Sets the marker color. It accepts either a specific color or an array of numbers that are mapped to the
    // colorscale relative to the max and min values of the array or relative to `marker.cmin` and `marker.cmax` if set.
    Box::Marker& color(std::string f);
    Box::Marker& color(double f);

    Box::Marker& line(Line f);
    template <typename Callable, typename = std::enable_if_t<std::is_invocable_v<Callable, Line&>>>
    Box::Marker& line(Callable&& c);

    // Sets the marker opacity.
    Box::Marker& opacity(double f);

    // Sets the color of the outlier sample points.
    Box::Marker& outliercolor(std::string f);
    Box::Marker& outliercolor(double f);

    // Sets the marker size (in px).
    Box::Marker& size(double f);

    // Sets the marker symbol type. Adding 100 is equivalent to appending *-open* to a symbol name. Adding 200 is
    // equivalent to appending *-dot* to a symbol name. Adding 300 is equivalent to appending *-open-dot* or *dot-open*
    // to a symbol name.
    // - Default: circle
    Box::Marker& symbol(enum Symbol f);

    // Advanced users may modify the JSON representation directly, at their own peril!
    Json json{};
};

class Box::Marker::Line {
 public:
    Line() = default;
    Line(std::string jsonStr)
    : json(parse(std::move(jsonStr))) {}

    // Sets the marker.line color. It accepts either a specific color or an array of numbers that are mapped to the
    // colorscale relative to the max and min values of the array or relative to `marker.line.cmin` and
    // `marker.line.cmax` if set.
    Box::Marker::Line& color(std::string f);
    Box::Marker::Line& color(double f);

    // Sets the border line color of the outlier sample points. Defaults to marker.color
    Box::Marker::Line& outliercolor(std::string f);
    Box::Marker::Line& outliercolor(double f);

    // Sets the border line width (in px) of the outlier sample points.
    Box::Marker::Line& outlierwidth(double f);

    // Sets the width (in px) of the lines bounding the marker points.
    Box::Marker::Line& width(double f);

    // Advanced users may modify the JSON representation directly, at their own peril!
    Json json{};
};

class Box::Selected {
 public:
    Selected() = default;
    Selected(std::string jsonStr)
    : json(parse(std::move(jsonStr))) {}

    class Marker;

    Box::Selected& marker(Marker f);
    template <typename Callable, typename = std::enable_if_t<std::is_invocable_v<Callable, Marker&>>>
    Box::Selected& marker(Callable&& c);

    // Advanced users may modify the JSON representation directly, at their own peril!
    Json json{};
};

class Box::Selected::Marker {
 public:
    Marker() = default;
    Marker(std::string jsonStr)
    : json(parse(std::move(jsonStr))) {}

    // Sets the marker color of selected points.
    Box::Selected::Marker& color(std::string f);
    Box::Selected::Marker& color(double f);

    // Sets the marker opacity of selected points.
    Box::Selected::Marker& opacity(double f);

    // Sets the marker size of selected points.
    Box::Selected::Marker& size(double f);

    // Advanced users may modify the JSON representation directly, at their own peril!
    Json json{};
};

class Box::Stream {
 public:
    Stream() = default;
    Stream(std::string jsonStr)
    : json(parse(std::move(jsonStr))) {}

    // Sets the maximum number of points to keep on the plots from an incoming stream. If `maxpoints` is set to *50*,
    // only the newest 50 points will be displayed on the plot.
    Box::Stream& maxpoints(double f);

    // The stream id number links a data trace on a plot with a stream. See https://chart-studio.plotly.com/settings for
    // more details.
    Box::Stream& token(std::string f);

    // Advanced users may modify the JSON representation directly, at their own peril!
    Json json{};
};

class Box::Unselected {
 public:
    Unselected() = default;
    Unselected(std::string jsonStr)
    : json(parse(std::move(jsonStr))) {}

    class Marker;

    Box::Unselected& marker(Marker f);
    template <typename Callable, typename = std::enable_if_t<std::is_invocable_v<Callable, Marker&>>>
    Box::Unselected& marker(Callable&& c);

    // Advanced users may modify the JSON representation directly, at their own peril!
    Json json{};
};

class Box::Unselected::Marker {
 public:
    Marker() = default;
    Marker(std::string jsonStr)
    : json(parse(std::move(jsonStr))) {}

    // Sets the marker color of unselected points, applied only when a selection exists.
    Box::Unselected::Marker& color(std::string f);
    Box::Unselected::Marker& color(double f);

    // Sets the marker opacity of unselected points, applied only when a selection exists.
    Box::Unselected::Marker& opacity(double f);

    // Sets the marker size of unselected points, applied only when a selection exists.
    Box::Unselected::Marker& size(double f);

    // Advanced users may modify the JSON representation directly, at their own peril!
    Json json{};
};

} // namespace plotlypp

#include "impl/box_impl.hpp"
